CREATE OR REPLACE TABLE `<ENV>.STG.Tab_embargos` AS
SELECT
  deb.DEB_DEBT_USER_ID,
  deb.DEB_DEBT_ID,
  deb.DEB_DEBT_TOTAL_AMOUNT,
  deb.DEB_DEBT_PAID_AMOUNT,
  deb.DEB_DEBT_STATUS,
  deb.DEB_DEBT_CURRENCY_ID,
  deb.DEB_DEBT_SITE_ID,
  deb.DEB_DEBT_CREATED_AT,
  deb.DEB_DEBT_DEBT_TYPE_ID,
  rec.RECOVERY_DESCRIPTION,
  cus.CUS_CUST_DOC_NUMBER,
  cus.CUS_FIRST_NAME,
  cus.CUS_LAST_NAME
FROM
  meli-bi-data.WHOWNER.BT_MP_DEB_DEBT AS deb
JOIN
  meli-bi-data.WHOWNER.BT_DEBT_RECOVERY AS rec
    ON deb.DEB_DEBT_ID = rec.DEBT_ID
JOIN
  meli-bi-data.WHOWNER.LK_CUS_CUSTOMERS_DATA AS cus
    ON deb.DEB_DEBT_USER_ID = cus.CUS_CUST_ID
WHERE
  deb.DEB_DEBT_DEBT_TYPE_ID IN (77, 437, 442,459) 
  AND deb.DEB_DEBT_CREATED_AT BETWEEN DATE('2023-01-01') AND DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY);
