WITH uniao AS (

  SELECT 
    SAFE_CAST(fase_de_workflow AS STRING) AS fase_de_workflow,
    SAFE_CAST(workflow AS STRING) AS workflow
  FROM `pdme000426-c1s7scatwm0-furyid.STG.STG_INPUT_DATABASE_ELAW_ACOMPANHAMENTO_DE_TAREFAS_CORP_CX`

  UNION ALL
  SELECT 
    SAFE_CAST(fase_de_workflow AS STRING),
    SAFE_CAST(workflow AS STRING)
  FROM `pdme000426-c1s7scatwm0-furyid.STG.STG_INPUT_DATABASE_ELAW_TAREFAS_AGENDADAS_SUBSIDIOS_HISPANOS_CAP`

  UNION ALL
  SELECT 
    SAFE_CAST(fase_de_workflow AS STRING),
    SAFE_CAST(workflow AS STRING)
  FROM `pdme000426-c1s7scatwm0-furyid.STG.STG_INPUT_DATABASE_ELAW_TAREFAS_AGENDADAS_SUBSIDIOS_HISPANOS_CAP_CX`

  UNION ALL
  SELECT 
    SAFE_CAST(fase_de_workflow AS STRING),
    SAFE_CAST(workflow AS STRING)
  FROM `pdme000426-c1s7scatwm0-furyid.STG.STG_INPUT_DATABASE_ELAW_TAREFAS_AGENDADAS_SUBSIDIOS_HISPANOS_DR`

  UNION ALL
  SELECT 
    SAFE_CAST(fase_de_workflow AS STRING),
    SAFE_CAST(workflow AS STRING)
  FROM `pdme000426-c1s7scatwm0-furyid.STG.STG_INPUT_DATABASE_ELAW_TAREFAS_AGENDADAS_SUBSIDIOS_HISPANOS_OPS_ENLI`

  UNION ALL
  SELECT 
    SAFE_CAST(fase_de_workflow AS STRING),
    SAFE_CAST(workflow AS STRING)
  FROM `pdme000426-c1s7scatwm0-furyid.STG.STG_INPUT_DATABASE_ELAW_TAREFAS_AGENDADAS_SUBSIDIOS_HISPANOS_OPS_INTER`


  UNION ALL
  SELECT 
    SAFE_CAST(fase_de_workflow AS STRING),
    SAFE_CAST(workflow AS STRING)
  FROM `pdme000426-c1s7scatwm0-furyid.STG.STG_INPUT_DATABASE_ELAW_TAREFAS_AGENDAMENTOS_SUBSIDIOS_CLEAN_PENDENTES`

  UNION ALL
  SELECT 
    SAFE_CAST(fase_de_workflow AS STRING),
    SAFE_CAST(workflow AS STRING)
  FROM `pdme000426-c1s7scatwm0-furyid.STG.STG_INPUT_DATABASE_ELAW_TAREFAS_AGENDAMENTOS_SUBSIDIOS_CLEAN_AUDIENCIAS`

)

SELECT DISTINCT
  fase_de_workflow,
  workflow
FROM uniao
WHERE workflow IS NOT NULL OR fase_de_workflow IS NOT NULL
ORDER BY fase_de_workflow, workflow;
