-- TABELA EXTERNA (GOOGLE SHEETS)
CREATE
OR REPLACE EXTERNAL TABLE `<ENV>.STG.BUDGET_CORACAO` (
  Pais STRING,
  Objeto STRING,
  Anomes STRING,
  Ano STRING,
  Entradas STRING,
  Entradas_JEC STRING,
  Entradas_JC STRING,
  Entradas_Procon STRING,
  Encerrados STRING,
  Encerrados_JEC STRING,
  Encerrados_JC STRING,
  Encerrados_Procon STRING,
  TM_Provisao STRING,
  JEC_TM_Provisao STRING,
  JC_TM_Provisao STRING,
  Procon_TM_Provisao STRING,
  TM_Acordo STRING,
  JEC_TM_Acordo STRING,
  JC_TM_Acordo STRING,
  Procon_TM_Acordo STRING,
  TM_Ganhamos STRING,
  JEC_TM_Ganhamos STRING,
  JC_TM_Ganhamos STRING,
  Procon_TM_Ganhamos STRING,
  TM_Perdemos STRING,
  JEC_TM_Perdemos STRING,
  JC_TM_Perdemos STRING,
  Procon_TM_Perdemos STRING,
  Percent_Acordo STRING,
  JEC_Percent_Acordo STRING,
  JC_Percent_Acordo STRING,
  Procon_Percent_Acordo STRING,
  Percent_Ganhamos STRING,
  JEC_Percent_Ganhamos STRING,
  JC_Percent_Ganhamos STRING,
  Procon_Percent_Ganhamos STRING,
  Percent_Perdemos STRING,
  JEC_Percent_Perdemos STRING,
  JC_Percent_Perdemos STRING,
  Procon_Percent_Perdemos STRING,
  Qty_Acordo STRING,
  JEC_Qty_Acordo STRING,
  JC_Qty_Acordo STRING,
  Procon_Qty_Acordo STRING,
  Qty_Ganhamos STRING,
  JEC_Qty_Ganhamos STRING,
  JC_Qty_Ganhamos STRING,
  Procon_Qty_Ganhamos STRING,
  Qty_Perdemos STRING,
  JC_Qty_Perdemos STRING,
  JEC_Qty_Perdemos STRING,
  Procon_Qty_Perdemos STRING,
  Qty_Desistido STRING,
  JEC_Qty_Desistido STRING,
  JC_Qty_Desistido STRING,
  Procon_Qty_Desistido STRING,
  Qty_Outros STRING,
  JEC_Qty_Outros STRING,
  JC_Qty_Outros STRING,
  Procon_Qty_Outros STRING
) OPTIONS (
  format = 'GOOGLE_SHEETS',
  skip_leading_rows = 1,
  sheet_range = 'Database!A:BH',
  uris = ['https://docs.google.com/spreadsheets/d/1TvUrsmAxIcC1BA-YP8R7ksOUiAUYZhSG3CMa-13Cq0w']
);

-- TABELA DE FATO (MESMA ESTRUTURA, CAMPOS COMO STRING)
CREATE
OR REPLACE TABLE `<ENV>.STG.BUDGET_CORACAO_FATO` (
  Pais STRING,
  Objeto STRING,
  Anomes STRING,
  Ano STRING,
  Entradas STRING,
  Entradas_JEC STRING,
  Entradas_JC STRING,
  Entradas_Procon STRING,
  Encerrados STRING,
  Encerrados_JEC STRING,
  Encerrados_JC STRING,
  Encerrados_Procon STRING,
  TM_Provisao STRING,
  JEC_TM_Provisao STRING,
  JC_TM_Provisao STRING,
  Procon_TM_Provisao STRING,
  TM_Acordo STRING,
  JEC_TM_Acordo STRING,
  JC_TM_Acordo STRING,
  Procon_TM_Acordo STRING,
  TM_Ganhamos STRING,
  JEC_TM_Ganhamos STRING,
  JC_TM_Ganhamos STRING,
  Procon_TM_Ganhamos STRING,
  TM_Perdemos STRING,
  JEC_TM_Perdemos STRING,
  JC_TM_Perdemos STRING,
  Procon_TM_Perdemos STRING,
  Percent_Acordo STRING,
  JEC_Percent_Acordo STRING,
  JC_Percent_Acordo STRING,
  Procon_Percent_Acordo STRING,
  Percent_Ganhamos STRING,
  JEC_Percent_Ganhamos STRING,
  JC_Percent_Ganhamos STRING,
  Procon_Percent_Ganhamos STRING,
  Percent_Perdemos STRING,
  JEC_Percent_Perdemos STRING,
  JC_Percent_Perdemos STRING,
  Procon_Percent_Perdemos STRING,
  Qty_Acordo STRING,
  JEC_Qty_Acordo STRING,
  JC_Qty_Acordo STRING,
  Procon_Qty_Acordo STRING,
  Qty_Ganhamos STRING,
  JEC_Qty_Ganhamos STRING,
  JC_Qty_Ganhamos STRING,
  Procon_Qty_Ganhamos STRING,
  Qty_Perdemos STRING,
  JC_Qty_Perdemos STRING,
  JEC_Qty_Perdemos STRING,
  Procon_Qty_Perdemos STRING,
  Qty_Desistido STRING,
  JEC_Qty_Desistido STRING,
  JC_Qty_Desistido STRING,
  Procon_Qty_Desistido STRING,
  Qty_Outros STRING,
  JEC_Qty_Outros STRING,
  JC_Qty_Outros STRING,
  Procon_Qty_Outros STRING
);

-- TRUNCATE DA TABELA DE FATO
DELETE FROM
  `<ENV>.STG.BUDGET_CORACAO_FATO`
WHERE
  TRUE;

INSERT INTO
  `<ENV>.STG.BUDGET_CORACAO_FATO`
SELECT
  *
FROM
  `<ENV>.STG.BUDGET_CORACAO`;