-- ============================================================================
-- BLOCO 00: PREPARAÇÃO INICIAL
-- ============================================================================
-- Descrição: Criação e limpeza de todas as tabelas temporárias (_FINCH)
-- Objetivo: Preparar ambiente para processamento isolado
-- Performance: Execução rápida, apenas DDL
-- ============================================================================

-- Tabelas de entrada e preparação
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_PLANILHA_PRESENTA_CAD_VF_FINCH AS
SELECT * FROM SBOX_LEGALES.STG_QS_PLANILHA_PRESENTA_CAD_VF;
TRUNCATE TABLE SBOX_LEGALES.STG_QS_PLANILHA_PRESENTA_CAD_VF_FINCH;

-- Tabelas de informações de titulares
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_INFO_TIT_CAD_VF_FINCH AS
SELECT * FROM SBOX_LEGALES.STG_QS_INFO_TIT_CAD_VF;
TRUNCATE TABLE SBOX_LEGALES.STG_QS_INFO_TIT_CAD_VF_FINCH;

CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_INFO_TIT_KYC_CAD_VF_FINCH AS
SELECT * FROM SBOX_LEGALES.STG_QS_INFO_TIT_KYC_CAD_VF;
TRUNCATE TABLE SBOX_LEGALES.STG_QS_INFO_TIT_KYC_CAD_VF_FINCH;

-- Tabela nova 2026: Base regulada (melhoria de performance)
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_NQS2_INFO_TIT_CAD_VF_FINCH AS
SELECT * FROM SBOX_LEGALES.STG_QS_INFO_TIT_CAD_VF LIMIT 0;
TRUNCATE TABLE SBOX_LEGALES.STG_NQS2_INFO_TIT_CAD_VF_FINCH;

-- Tabelas de correspondentes e não correspondentes
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_CORRESPONDENTE_CAD_VF_FINCH AS
SELECT * FROM SBOX_LEGALES.STG_QS_CORRESPONDENTE_CAD_VF;
TRUNCATE TABLE SBOX_LEGALES.STG_QS_CORRESPONDENTE_CAD_VF_FINCH;

CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_NAO_CORRESPONDENTE_CAD_VF_FINCH AS
SELECT * FROM SBOX_LEGALES.STG_QS_NAO_CORRESPONDENTE_CAD_VF;
TRUNCATE TABLE SBOX_LEGALES.STG_QS_NAO_CORRESPONDENTE_CAD_VF_FINCH;

-- Tabelas de contas SPB e KYC
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_SPB_CAD_VF_FINCH AS
SELECT * FROM SBOX_LEGALES.STG_QS_SPB_CAD_VF;
TRUNCATE TABLE SBOX_LEGALES.STG_QS_SPB_CAD_VF_FINCH;

CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_MAX_KYC_CAD_VF_FINCH AS
SELECT * FROM SBOX_LEGALES.STG_QS_MAX_KYC_CAD_VF;
TRUNCATE TABLE SBOX_LEGALES.STG_QS_MAX_KYC_CAD_VF_FINCH;

CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_QTD_CUST_MAX_KYC_CAD_VF_FINCH AS
SELECT * FROM SBOX_LEGALES.STG_QS_QTD_CUST_MAX_KYC_CAD_VF;
TRUNCATE TABLE SBOX_LEGALES.STG_QS_QTD_CUST_MAX_KYC_CAD_VF_FINCH;

CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_MAX_CUST_CAD_VF_FINCH AS
SELECT * FROM SBOX_LEGALES.STG_QS_MAX_CUST_CAD_VF;
TRUNCATE TABLE SBOX_LEGALES.STG_QS_MAX_CUST_CAD_VF_FINCH;

CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_NOME_UNI_INV_CAD_VF_FINCH AS
SELECT * FROM SBOX_LEGALES.STG_QS_NOME_UNI_INV_CAD_VF;
TRUNCATE TABLE SBOX_LEGALES.STG_QS_NOME_UNI_INV_CAD_VF_FINCH;

-- Tabela consolidada de titulares
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_TITULAR_CAD_VF_FINCH AS
SELECT * FROM SBOX_LEGALES.STG_QS_TITULAR_CAD_VF;
TRUNCATE TABLE SBOX_LEGALES.STG_QS_TITULAR_CAD_VF_FINCH;

-- Tabelas de movimentações
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_AUX_MOVIMENTACAO_CAD_VF_FINCH AS
SELECT * FROM SBOX_LEGALES.STG_QS_AUX_MOVIMENTACAO_CAD_VF;
TRUNCATE TABLE SBOX_LEGALES.STG_QS_AUX_MOVIMENTACAO_CAD_VF_FINCH;

CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_AUX_MOVIMENTACAO2_CAD_VF_FINCH AS
SELECT * FROM SBOX_LEGALES.STG_QS_AUX_MOVIMENTACAO2_CAD_VF;
TRUNCATE TABLE SBOX_LEGALES.STG_QS_AUX_MOVIMENTACAO2_CAD_VF_FINCH;

-- Tabelas de relacionados (Payout, Payin, Payments, Withdrawal)
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_AUX_PAYOUT_CAD_VF_FINCH AS
SELECT * FROM SBOX_LEGALES.STG_QS_AUX_PAYOUT_CAD_VF;
TRUNCATE TABLE SBOX_LEGALES.STG_QS_AUX_PAYOUT_CAD_VF_FINCH;

CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_AUX_PAYOUT_REL_CAD_VF_FINCH AS
SELECT * FROM SBOX_LEGALES.STG_QS_AUX_PAYOUT_REL_CAD_VF;
TRUNCATE TABLE SBOX_LEGALES.STG_QS_AUX_PAYOUT_REL_CAD_VF_FINCH;

CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_AUX_PAYIN_CAD_VF_FINCH AS
SELECT * FROM SBOX_LEGALES.STG_QS_AUX_PAYIN_CAD_VF;
TRUNCATE TABLE SBOX_LEGALES.STG_QS_AUX_PAYIN_CAD_VF_FINCH;

CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_AUX_PAYIN_REL_CAD_VF_FINCH AS
SELECT * FROM SBOX_LEGALES.STG_QS_AUX_PAYIN_REL_CAD_VF;
TRUNCATE TABLE SBOX_LEGALES.STG_QS_AUX_PAYIN_REL_CAD_VF_FINCH;

-- Tabela nova 2026: Payin base particionada (melhoria de performance)
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_NQS2_AUX_PAYIN_REL_CAD_VF_FINCH_BASE
PARTITION BY PAY_MOVE_DATE     
CLUSTER BY ID_PAGAMENTO AS
SELECT * FROM SBOX_LEGALES.STG_QS_AUX_PAYIN_REL_CAD_VF LIMIT 0;
TRUNCATE TABLE SBOX_LEGALES.STG_NQS2_AUX_PAYIN_REL_CAD_VF_FINCH_BASE;

CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_AUX_PAYMENTS_COMID_CAD_VF_FINCH AS
SELECT * FROM SBOX_LEGALES.STG_QS_AUX_PAYMENTS_COMID_CAD_VF;
TRUNCATE TABLE SBOX_LEGALES.STG_QS_AUX_PAYMENTS_COMID_CAD_VF_FINCH;

CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_AUX_PAYMENTS_SEMID_CAD_VF_FINCH AS
SELECT * FROM SBOX_LEGALES.STG_QS_AUX_PAYMENTS_SEMID_CAD_VF;
TRUNCATE TABLE SBOX_LEGALES.STG_QS_AUX_PAYMENTS_SEMID_CAD_VF_FINCH;

CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_PAGAMENTO_CAD_VF_FINCH AS
SELECT * FROM SBOX_LEGALES.STG_QS_PAGAMENTO_CAD_VF;
TRUNCATE TABLE SBOX_LEGALES.STG_QS_PAGAMENTO_CAD_VF_FINCH;

CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_PAGAMENTO_REL_CAD_VF_FINCH AS
SELECT * FROM SBOX_LEGALES.STG_QS_PAGAMENTO_REL_CAD_VF;
TRUNCATE TABLE SBOX_LEGALES.STG_QS_PAGAMENTO_REL_CAD_VF_FINCH;

CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_AUX_WITHDRAWAL_CAD_VF_FINCH AS
SELECT * FROM SBOX_LEGALES.STG_QS_AUX_WITHDRAWAL_CAD_VF;
TRUNCATE TABLE SBOX_LEGALES.STG_QS_AUX_WITHDRAWAL_CAD_VF_FINCH;

CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_WITHDRAWAL_REL_CAD_VF_FINCH AS
SELECT * FROM SBOX_LEGALES.STG_QS_WITHDRAWAL_REL_CAD_VF;
TRUNCATE TABLE SBOX_LEGALES.STG_QS_WITHDRAWAL_REL_CAD_VF_FINCH;

-- Tabela consolidada de relacionados
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_RELACIONADO_CAD_VF_FINCH AS
SELECT * FROM SBOX_LEGALES.STG_QS_RELACIONADO_CAD_VF;
TRUNCATE TABLE SBOX_LEGALES.STG_QS_RELACIONADO_CAD_VF_FINCH;

-- Tabela de flags de movimentação
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_FLAG_MOV_CAD_VF_FINCH AS
SELECT * FROM SBOX_LEGALES.STG_QS_FLAG_MOV_CAD_VF;
TRUNCATE TABLE SBOX_LEGALES.STG_QS_FLAG_MOV_CAD_VF_FINCH;

-- Tabelas auxiliares
CREATE OR REPLACE TABLE SBOX_LEGALES.Dim_Instituicoes_FINCH AS
SELECT * FROM SBOX_LEGALES.Dim_Instituicoes;
TRUNCATE TABLE SBOX_LEGALES.Dim_Instituicoes_FINCH;

-- Tabelas finais de saída
CREATE OR REPLACE TABLE SBOX_LEGALES.TBL_QS_NAO_CORRESPONDENTE_FINCH AS
SELECT * FROM SBOX_LEGALES.TBL_QS_NAO_CORRESPONDENTE;
TRUNCATE TABLE SBOX_LEGALES.TBL_QS_NAO_CORRESPONDENTE_FINCH;

CREATE OR REPLACE TABLE SBOX_LEGALES.TBL_QS_AGENCIAS_FINCH AS
SELECT * FROM SBOX_LEGALES.TBL_QS_AGENCIAS;
TRUNCATE TABLE SBOX_LEGALES.TBL_QS_AGENCIAS_FINCH;

CREATE OR REPLACE TABLE SBOX_LEGALES.TBL_QS_CONTAS_FINCH AS
SELECT * FROM SBOX_LEGALES.TBL_QS_CONTAS;
TRUNCATE TABLE SBOX_LEGALES.TBL_QS_CONTAS_FINCH;

CREATE OR REPLACE TABLE SBOX_LEGALES.Dim_DATE_FINCH AS
SELECT * FROM SBOX_LEGALES.Dim_DATE;
TRUNCATE TABLE SBOX_LEGALES.Dim_DATE_FINCH;

CREATE OR REPLACE TABLE SBOX_LEGALES.TBL_QS_EXTRATO_FINCH AS
SELECT * FROM SBOX_LEGALES.TBL_QS_EXTRATO;
TRUNCATE TABLE SBOX_LEGALES.TBL_QS_EXTRATO_FINCH;

CREATE OR REPLACE TABLE SBOX_LEGALES.TBL_QS_TITULARES_FINCH AS
SELECT * FROM SBOX_LEGALES.TBL_QS_TITULARES;
TRUNCATE TABLE SBOX_LEGALES.TBL_QS_TITULARES_FINCH;

CREATE OR REPLACE TABLE SBOX_LEGALES.TBL_QS_ORIGEM_DESTINO_FINCH AS
SELECT * FROM SBOX_LEGALES.TBL_QS_ORIGEM_DESTINO;
TRUNCATE TABLE SBOX_LEGALES.TBL_QS_ORIGEM_DESTINO_FINCH;

CREATE OR REPLACE TABLE SBOX_LEGALES.CAD_TBL_QS_EXTRATO_NAO_CORRESPONDENTE_FINCH AS
SELECT * FROM SBOX_LEGALES.CAD_TBL_QS_EXTRATO_NAO_CORRESPONDENTE;
TRUNCATE TABLE SBOX_LEGALES.CAD_TBL_QS_EXTRATO_NAO_CORRESPONDENTE_FINCH;

CREATE OR REPLACE TABLE SBOX_LEGALES.CAD_TBL_QS_EXTRATO_MOVIMENTACAO_FINCH AS
SELECT * FROM SBOX_LEGALES.CAD_TBL_QS_EXTRATO_MOVIMENTACAO;
TRUNCATE TABLE SBOX_LEGALES.CAD_TBL_QS_EXTRATO_MOVIMENTACAO_FINCH;
