-- ============================================================================
-- BLOCO 05: PROCESSAMENTO DE RELACIONADOS
-- ============================================================================
-- Descrição: Processa informações de relacionados em transações financeiras
--             Payout, Payin (PIX), Payments e Withdrawals
-- Objetivo: Identificar origem/destino das transações
-- Performance: JOINs otimizados com filtros específicos
-- MELHORIA 2026: Tabela PIX particionada e melhor tratamento de dados
-- ============================================================================

-- ============================================================================
-- PAYOUT - Transferências enviadas
-- ============================================================================
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_AUX_PAYOUT_CAD_VF_FINCH AS (
SELECT 
  ID_PAGAMENTO,
  CODIGO_CHAVE_EXTRATO
FROM SBOX_LEGALES.STG_QS_AUX_MOVIMENTACAO2_CAD_VF_FINCH MOV
WHERE TBL_RELACIONADO = 'Payout'
);

-- Relacionados de Payout
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_AUX_PAYOUT_REL_CAD_VF_FINCH AS (
SELECT
  DISTINCT
  MOV.ID_PAGAMENTO,
  CODIGO_CHAVE_EXTRATO,
  UPPER(TRIM(WIT.PYT_PRVDR_DATA_DEST_BANK_NAME)) AS NOME_BANCO_REL,
  INSTITUT.NUMERO_CODIGO AS NUMERO_BANCO_REL,
  REGEXP_REPLACE(WIT.PYT_PRVDR_DATA_DEST_BRANCH, '[^a-zA-Z0-9]','') AS NUMERO_AGENCIA_REL,
  REGEXP_REPLACE(WIT.PYT_PRVDR_DATA_DEST_NUMBER, '[^a-zA-Z0-9]','') AS NUMERO_CONTA_REL,
  '4' AS TIPO_CONTA_REL,
  CASE 
    WHEN WIT.PYT_PRVDR_DATA_DEST_IDENT_TYPE = 'CPF' THEN '1' 
    WHEN WIT.PYT_PRVDR_DATA_DEST_IDENT_TYPE = 'CNPJ' THEN '2' 
    ELSE NULL
  END AS TIPO_PESSOA_REL,
  CAST(WIT.PYT_PRVDR_DATA_DEST_IDENT_NUMBER AS STRING) AS CPF_CNPJ_REL,
  UPPER(WIT.PYT_PRVDR_DATA_DEST_HOLDER) AS NOME_PESSOA_REL
FROM SBOX_LEGALES.STG_QS_AUX_PAYOUT_CAD_VF_FINCH MOV
LEFT JOIN WHOWNER.BT_MP_PAYOUTS WIT 
  ON CAST(MOV.ID_PAGAMENTO AS STRING) = CAST(WIT.PAYOUT_ID AS STRING)
LEFT JOIN SBOX_LEGALES.Dim_Instituicoes INSTITUT 
  ON WIT.PYT_PRVDR_DATA_DEST_BANK_ID = CAST(INSTITUT.ISPB AS STRING)
);

-- ============================================================================
-- PAYIN (PIX) - Recebimentos via PIX
-- ============================================================================
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_AUX_PAYIN_CAD_VF_FINCH AS (
SELECT 
  ID_PAGAMENTO,
  CODIGO_CHAVE_EXTRATO
FROM SBOX_LEGALES.STG_QS_AUX_MOVIMENTACAO2_CAD_VF_FINCH MOV
WHERE TBL_RELACIONADO = 'Pix'
);

-- MELHORIA 2026: Tabela PIX particionada por data (melhoria de performance)
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_NQS2_AUX_PAYIN_REL_CAD_VF_FINCH_BASE
PARTITION BY PAY_MOVE_DATE     
CLUSTER BY ID_PAGAMENTO AS (
WITH
  BASE AS (
    SELECT
      a.TRANSACTION_PAYMENT_ID AS ID_PAGAMENTO,
      a.PAY_MOVE_DATE,
      a.PAYER_BANK_NAME,
      a.PAYER_BANK_ID,
      a.PAYER_BRANCH_ID,
      a.PAYER_ACCOUNT_ID,
      a.PAYER_DICT_KEY_TYPE,
      a.PAYER_ENTITY_TYPE,
      a.PAYER_DOC_NUMBER,
      a.PAYER_DOC_NAME,
      a.RECEIVER_BANK_NAME,
      a.RECEIVER_BANK_ID,
      a.RECEIVER_BRANCH_ID,
      a.RECEIVER_ACCOUNT_ID,
      a.RECEIVER_DICT_KEY_TYPE,
      a.RECEIVER_ENTITY_TYPE,
      a.RECEIVER_DOC_NUMBER,
      a.RECEIVER_DOC_NAME,
      p.MP_PROD_PRODUCT,
      p.MP_PROD_USER_TYPE
    FROM `meli-bi-data.WHOWNER.BT_MP_PIX_ALL` a
    LEFT JOIN `meli-bi-data.WHOWNER.BT_MP_PRODUCTS` p
      ON a.PRODUCT_ID = p.MP_PROD_ID
    WHERE SIT_SITE_ID = 'MLB'
  ),
  PIX AS (
    SELECT
      ID_PAGAMENTO,
      PAY_MOVE_DATE,
      PAYER_BANK_NAME AS NOME_BANCO_REL,
      PAYER_BANK_ID AS NUMERO_BANCO_REL,
      PAYER_BRANCH_ID AS NUMERO_AGENCIA_REL,
      PAYER_ACCOUNT_ID AS NUMERO_CONTA_REL,
      PAYER_DICT_KEY_TYPE AS TIPO_CONTA_REL,
      PAYER_ENTITY_TYPE AS TIPO_PESSOA_REL,
      PAYER_DOC_NUMBER AS CPF_CNPJ_REL,
      PAYER_DOC_NAME AS NOME_PESSOA_REL,
      'PAYER' AS ORIGEM_REGISTRO
    FROM BASE
    UNION ALL
    SELECT
      ID_PAGAMENTO,
      PAY_MOVE_DATE,
      RECEIVER_BANK_NAME,
      RECEIVER_BANK_ID,
      RECEIVER_BRANCH_ID,
      RECEIVER_ACCOUNT_ID,
      RECEIVER_DICT_KEY_TYPE,
      RECEIVER_ENTITY_TYPE,
      RECEIVER_DOC_NUMBER,
      RECEIVER_DOC_NAME,
      'RECEIVER'
    FROM BASE
  )
SELECT
  PIX.*,
  QS.CODIGO_CHAVE_EXTRATO
FROM PIX
LEFT JOIN SBOX_LEGALES.STG_QS_AUX_MOVIMENTACAO2_CAD_VF_FINCH QS
  USING (ID_PAGAMENTO)
);

-- MELHORIA 2026: Correção de dados PIX usando base regulada
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_NQS2_AUX_PAYIN_REL_CAD_VF_FINCH AS (
WITH
  BASE AS (
    SELECT * FROM SBOX_LEGALES.STG_NQS2_AUX_PAYIN_REL_CAD_VF_FINCH_BASE
  ),
  REGULATORIO AS (
    SELECT * FROM SBOX_LEGALES.STG_NQS2_INFO_TIT_CAD_VF_FINCH_STEP2
  ),
  BASE_JOINED AS (
    SELECT
      b.ID_PAGAMENTO,
      b.CODIGO_CHAVE_EXTRATO,
      b.NOME_BANCO_REL,
      b.NUMERO_BANCO_REL,
      b.NUMERO_AGENCIA_REL,
      -- Conta corrigida
      COALESCE(NULLIF(b.NUMERO_CONTA_REL, ''), r.AVK_ACCOUNT_ID) AS NUMERO_CONTA_REL,
      b.TIPO_CONTA_REL,
      b.TIPO_PESSOA_REL,
      b.CPF_CNPJ_REL,
      -- Nome corrigido
      COALESCE(NULLIF(b.NOME_PESSOA_REL, ''), r.LEGAL_NAME) AS NOME_PESSOA_REL
    FROM BASE b
    LEFT JOIN REGULATORIO r
      ON b.CPF_CNPJ_REL = r.DOCUMENT_NUMBER
  )
SELECT * FROM BASE_JOINED
);

-- Relacionados de Payin (versão antiga para compatibilidade)
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_AUX_PAYIN_REL_CAD_VF_FINCH AS (
SELECT
  DISTINCT
  MOV.ID_PAGAMENTO,
  CODIGO_CHAVE_EXTRATO,
  UPPER(TRIM(WIT.PYN_COLLECTOR_BANK_NAME)) AS NOME_BANCO_REL,
  INSTITUT.NUMERO_CODIGO AS NUMERO_BANCO_REL,
  '' AS NUMERO_AGENCIA_REL,
  REGEXP_REPLACE(CAST(WIT.PYN_BUY_ACCOUNT_ID AS STRING), '[^a-zA-Z0-9]','') AS NUMERO_CONTA_REL,
  '4' AS TIPO_CONTA_REL,
  CASE 
    WHEN WIT.PYN_PAYER_IDENTIFICATION_TYPE = 'CPF' THEN '1' 
    WHEN WIT.PYN_PAYER_IDENTIFICATION_TYPE = 'CNPJ' THEN '2' 
    ELSE NULL
  END AS TIPO_PESSOA_REL,
  CAST(WIT.PYN_PAYER_IDENTIFICATION_NUMBER AS STRING) AS CPF_CNPJ_REL,
  UPPER(WIT.PYN_PAYER_NAME) AS NOME_PESSOA_REL
FROM SBOX_LEGALES.STG_QS_AUX_PAYIN_CAD_VF_FINCH MOV
LEFT JOIN WHOWNER.BT_MP_PAY_PAYIN WIT 
  ON CAST(MOV.ID_PAGAMENTO AS STRING) = CAST(WIT.PYN_ID AS STRING)
LEFT JOIN SBOX_LEGALES.Dim_Instituicoes INSTITUT 
  ON WIT.PYN_BUY_BANK_ID = CAST(INSTITUT.ISPB AS STRING)
);

-- ============================================================================
-- PAYMENTS - Pagamentos entre contas
-- ============================================================================
-- Payments com ID relacionado
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_AUX_PAYMENTS_COMID_CAD_VF_FINCH AS (
SELECT 
  ID_PAGAMENTO,
  ID_RELACIONADO,
  CUS_CUST_ID,
  CODIGO_CHAVE_EXTRATO
FROM SBOX_LEGALES.STG_QS_AUX_MOVIMENTACAO2_CAD_VF_FINCH MOV
WHERE TBL_RELACIONADO = 'Payments'
  AND ID_RELACIONADO IS NOT NULL
);

-- Payments sem ID relacionado
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_AUX_PAYMENTS_SEMID_CAD_VF_FINCH AS (
SELECT 
  ID_PAGAMENTO,
  ID_RELACIONADO,
  CUS_CUST_ID,
  CODIGO_CHAVE_EXTRATO
FROM SBOX_LEGALES.STG_QS_AUX_MOVIMENTACAO2_CAD_VF_FINCH MOV
WHERE TBL_RELACIONADO = 'Payments'
  AND ID_RELACIONADO IS NULL
);

-- Tabela consolidada de Payments
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_PAGAMENTO_CAD_VF_FINCH AS (
  SELECT
    MOV.ID_PAGAMENTO,
    CAST(MOV.ID_RELACIONADO AS STRING) AS ID_RELACIONADO,
    CAST(CODIGO_CHAVE_EXTRATO AS STRING) AS CODIGO_CHAVE_EXTRATO,
    CAST(NULL AS STRING) AS PAY_REASON_ID
  FROM SBOX_LEGALES.STG_QS_AUX_PAYMENTS_COMID_CAD_VF_FINCH MOV
  WHERE MOV.ID_RELACIONADO IS NOT NULL
  UNION ALL
  SELECT
    MOV.ID_PAGAMENTO,
    CASE
      WHEN MOV.ID_RELACIONADO IS NOT NULL THEN CAST(MOV.ID_RELACIONADO AS STRING)
      WHEN MOV.CUS_CUST_ID = PAY.CUS_CUST_ID_SEL THEN CAST(PAY.CUS_CUST_ID_BUY AS STRING)
      WHEN MOV.CUS_CUST_ID = PAY.CUS_CUST_ID_BUY THEN CAST(PAY.CUS_CUST_ID_SEL AS STRING)
      ELSE NULL
    END AS ID_RELACIONADO,
    CAST(CODIGO_CHAVE_EXTRATO AS STRING) AS CODIGO_CHAVE_EXTRATO,
    REGEXP_REPLACE(CAST(PAY.PAY_REASON_ID AS STRING),'[^0-9a-zA-Z]',' ') AS PAY_REASON_ID
  FROM SBOX_LEGALES.STG_QS_AUX_PAYMENTS_SEMID_CAD_VF_FINCH MOV
  LEFT JOIN WHOWNER.BT_MP_PAY_PAYMENTS_ALL PAY
    ON CAST(MOV.ID_PAGAMENTO AS STRING) = CAST(PAY.PAY_PAYMENT_ID AS STRING)
    AND PAY.SIT_SITE_ID = 'MLB'
  WHERE MOV.ID_RELACIONADO IS NULL
);

-- Informações dos relacionados com ID de pagamento
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_PAGAMENTO_REL_CAD_VF_FINCH AS (
SELECT
  DISTINCT
  PAG.ID_PAGAMENTO,
  PAG.CODIGO_CHAVE_EXTRATO,
  '323' AS NUMERO_BANCO_REL,
  '0001' AS NUMERO_AGENCIA_REL,
  CAST(REL.CUS_CUST_ID AS STRING) AS NUMERO_CONTA_REL,
  '4' AS TIPO_CONTA_REL,
  CASE 
    WHEN LENGTH(REL.CUS_CUST_DOC_NUMBER) = 11 THEN '1'
    WHEN LENGTH(REL.CUS_CUST_DOC_NUMBER) = 14 THEN '2'
    ELSE NULL
  END AS TIPO_PESSOA_REL,
  REL.CUS_CUST_DOC_NUMBER AS CPF_CNPJ_REL,
  UPPER(REL.CUS_FIRST_NAME || ' ' || REL.CUS_LAST_NAME) AS NOME_REL
FROM SBOX_LEGALES.STG_QS_PAGAMENTO_CAD_VF_FINCH PAG
LEFT JOIN WHOWNER.LK_CUS_CUSTOMERS_DATA REL
  ON CAST(PAG.ID_RELACIONADO AS STRING) = CAST(REL.CUS_CUST_ID AS STRING)
  AND REL.SIT_SITE_ID_CUS = 'MLB'
WHERE PAG.ID_RELACIONADO IS NOT NULL
);

-- ============================================================================
-- WITHDRAWAL - Retiradas bancárias
-- ============================================================================
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_AUX_WITHDRAWAL_CAD_VF_FINCH AS (
SELECT 
  ID_PAGAMENTO,
  CODIGO_CHAVE_EXTRATO
FROM SBOX_LEGALES.STG_QS_AUX_MOVIMENTACAO2_CAD_VF_FINCH MOV
WHERE TBL_RELACIONADO = 'Withdrawal'
);

-- Informações dos relacionados com retiros
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_WITHDRAWAL_REL_CAD_VF_FINCH AS (
SELECT
  MOV.ID_PAGAMENTO,
  CODIGO_CHAVE_EXTRATO,
  WIT.WIT_BANK_ACC_BANK_ID AS NUMERO_BANCO_REL,
  REGEXP_REPLACE(WIT.WIT_BANK_ACC_BRANCH_ID, '[^a-zA-Z0-9]','') AS NUMERO_AGENCIA_REL,
  REGEXP_REPLACE(WIT.WIT_BANK_ACC_NUMBER, '[^a-zA-Z0-9]','') AS NUMERO_CONTA_REL,
  '4' AS TIPO_CONTA_REL,
  CASE 
    WHEN WIT.WIT_BANK_ACC_ID_TYPE_ID IS NULL AND LENGTH(WIT.WIT_BANK_ACC_ID_NUMBER) = 11 THEN '1'
    WHEN WIT.WIT_BANK_ACC_ID_TYPE_ID IS NULL AND LENGTH(WIT.WIT_BANK_ACC_ID_NUMBER) = 14 THEN '2'
    WHEN WIT.WIT_BANK_ACC_ID_TYPE_ID = 'CPF' THEN '1' 
    WHEN WIT.WIT_BANK_ACC_ID_TYPE_ID = 'CNPJ' THEN '2' 
    ELSE NULL
  END AS TIPO_PESSOA_REL,
  WIT.WIT_BANK_ACC_ID_NUMBER AS CPF_CNPJ_REL,
  UPPER(COALESCE(WIT.WIT_BANK_ACC_ALIAS, WIT.WIT_BANK_ACC_HOLDER_ID)) AS NOME_PESSOA_REL
FROM SBOX_LEGALES.STG_QS_AUX_WITHDRAWAL_CAD_VF_FINCH MOV
LEFT JOIN WHOWNER.BT_MP_WITHDRAWALS WIT
  ON CAST(MOV.ID_PAGAMENTO AS STRING) = CAST(WIT.WIT_WITHDRAWAL_ID AS STRING)
  AND WIT.SIT_SITE_ID = 'MLB'
);
