-- ============================================================================
-- BLOCO 06: CONSOLIDAÇÃO DE RELACIONADOS
-- ============================================================================
-- Descrição: Consolida todos os relacionados (Payout, Payin, Payments, Withdrawal)
--             em uma única tabela e cria flag de movimentação
-- Objetivo: Unificar origem/destino de todas as transações
-- Performance: UNION DISTINCT otimizado
-- ============================================================================

-- UNIR TODOS OS RELACIONADOS
-- Consolida informações de Payout, Payin (PIX), Payments e Withdrawal
-- Filtra relacionados com nomes "SPLITTER" ou "PAYINS" (anula dados bancários)
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_RELACIONADO_CAD_VF_FINCH AS (
  -- Relacionados de Payout
  SELECT 
    DISTINCT
    ID_PAGAMENTO,
    CODIGO_CHAVE_EXTRATO,
    CASE 
      WHEN UPPER(NOME_PESSOA_REL) LIKE '%SPLITTER%' 
        OR UPPER(NOME_PESSOA_REL) LIKE '%PAYINS%' THEN NULL
      ELSE NUMERO_BANCO_REL
    END AS NUMERO_BANCO_REL,
    CASE 
      WHEN UPPER(NOME_PESSOA_REL) LIKE '%SPLITTER%' 
        OR UPPER(NOME_PESSOA_REL) LIKE '%PAYINS%' THEN NULL
      ELSE NUMERO_AGENCIA_REL
    END AS NUMERO_AGENCIA_REL,
    CASE 
      WHEN UPPER(NOME_PESSOA_REL) LIKE '%SPLITTER%' 
        OR UPPER(NOME_PESSOA_REL) LIKE '%PAYINS%' THEN NULL
      ELSE NUMERO_CONTA_REL
    END AS NUMERO_CONTA_REL,
    TIPO_CONTA_REL,
    CASE 
      WHEN UPPER(NOME_PESSOA_REL) LIKE '%SPLITTER%' 
        OR UPPER(NOME_PESSOA_REL) LIKE '%PAYINS%' THEN NULL
      ELSE TIPO_PESSOA_REL
    END AS TIPO_PESSOA_REL,
    CASE 
      WHEN UPPER(NOME_PESSOA_REL) LIKE '%SPLITTER%' 
        OR UPPER(NOME_PESSOA_REL) LIKE '%PAYINS%' THEN NULL
      ELSE CPF_CNPJ_REL
    END AS CPF_CNPJ_REL,
    CASE 
      WHEN UPPER(NOME_PESSOA_REL) LIKE '%SPLITTER%' 
        OR UPPER(NOME_PESSOA_REL) LIKE '%PAYINS%' THEN NULL
      ELSE NOME_PESSOA_REL
    END AS NOME_PESSOA_REL
  FROM SBOX_LEGALES.STG_QS_AUX_PAYOUT_REL_CAD_VF_FINCH

  UNION DISTINCT

  -- Relacionados de Payments
  SELECT 
    DISTINCT
    ID_PAGAMENTO,
    CODIGO_CHAVE_EXTRATO,
    CASE 
      WHEN UPPER(NOME_REL) LIKE '%SPLITTER%' 
        OR UPPER(NOME_REL) LIKE '%PAYINS%' THEN NULL
      ELSE '323'
    END AS NUMERO_BANCO_REL,
    CASE 
      WHEN UPPER(NOME_REL) LIKE '%SPLITTER%' 
        OR UPPER(NOME_REL) LIKE '%PAYINS%' THEN NULL
      ELSE '0001'
    END AS NUMERO_AGENCIA_REL,
    CASE 
      WHEN UPPER(NOME_REL) LIKE '%SPLITTER%' 
        OR UPPER(NOME_REL) LIKE '%PAYINS%' THEN NULL
      ELSE NUMERO_CONTA_REL
    END AS NUMERO_CONTA_REL,
    '4' AS TIPO_CONTA_REL,
    CASE 
      WHEN UPPER(NOME_REL) LIKE '%SPLITTER%' 
        OR UPPER(NOME_REL) LIKE '%PAYINS%' THEN NULL
      ELSE TIPO_PESSOA_REL
    END AS TIPO_PESSOA_REL,
    CASE 
      WHEN UPPER(NOME_REL) LIKE '%SPLITTER%' 
        OR UPPER(NOME_REL) LIKE '%PAYINS%' THEN NULL
      ELSE CPF_CNPJ_REL
    END AS CPF_CNPJ_REL,
    CASE 
      WHEN UPPER(NOME_REL) LIKE '%SPLITTER%' 
        OR UPPER(NOME_REL) LIKE '%PAYINS%' THEN NULL
      ELSE NOME_REL
    END AS NOME_REL
  FROM SBOX_LEGALES.STG_QS_PAGAMENTO_REL_CAD_VF_FINCH

  UNION DISTINCT

  -- Relacionados de Withdrawal
  SELECT
    DISTINCT
    ID_PAGAMENTO,
    CODIGO_CHAVE_EXTRATO,
    CASE 
      WHEN UPPER(NOME_PESSOA_REL) LIKE '%SPLITTER%' 
        OR UPPER(NOME_PESSOA_REL) LIKE '%PAYINS%' THEN NULL
      ELSE NUMERO_BANCO_REL
    END AS NUMERO_BANCO_REL,
    CASE 
      WHEN UPPER(NOME_PESSOA_REL) LIKE '%SPLITTER%' 
        OR UPPER(NOME_PESSOA_REL) LIKE '%PAYINS%' THEN NULL
      ELSE NUMERO_AGENCIA_REL
    END AS NUMERO_AGENCIA_REL,
    CASE 
      WHEN UPPER(NOME_PESSOA_REL) LIKE '%SPLITTER%' 
        OR UPPER(NOME_PESSOA_REL) LIKE '%PAYINS%' THEN NULL
      ELSE NUMERO_CONTA_REL
    END AS NUMERO_CONTA_REL,
    TIPO_CONTA_REL,
    CASE 
      WHEN UPPER(NOME_PESSOA_REL) LIKE '%SPLITTER%' 
        OR UPPER(NOME_PESSOA_REL) LIKE '%PAYINS%' THEN NULL
      ELSE TIPO_PESSOA_REL
    END AS TIPO_PESSOA_REL,
    CASE 
      WHEN UPPER(NOME_PESSOA_REL) LIKE '%SPLITTER%' 
        OR UPPER(NOME_PESSOA_REL) LIKE '%PAYINS%' THEN NULL
      ELSE CPF_CNPJ_REL
    END AS CPF_CNPJ_REL,
    CASE 
      WHEN UPPER(NOME_PESSOA_REL) LIKE '%SPLITTER%' 
        OR UPPER(NOME_PESSOA_REL) LIKE '%PAYINS%' THEN NULL
      ELSE NOME_PESSOA_REL
    END AS NOME_PESSOA_REL
  FROM SBOX_LEGALES.STG_QS_WITHDRAWAL_REL_CAD_VF_FINCH

  UNION DISTINCT

  -- Relacionados de Payin (PIX) - versão nova 2026
  SELECT 
    DISTINCT
    ID_PAGAMENTO,
    CODIGO_CHAVE_EXTRATO,
    CASE 
      WHEN UPPER(NOME_PESSOA_REL) LIKE '%SPLITTER%' 
        OR UPPER(NOME_PESSOA_REL) LIKE '%PAYINS%' THEN NULL
      ELSE NUMERO_BANCO_REL
    END AS NUMERO_BANCO_REL,
    CASE 
      WHEN UPPER(NOME_PESSOA_REL) LIKE '%SPLITTER%' 
        OR UPPER(NOME_PESSOA_REL) LIKE '%PAYINS%' THEN NULL
      ELSE NUMERO_AGENCIA_REL
    END AS NUMERO_AGENCIA_REL,
    CASE 
      WHEN UPPER(NOME_PESSOA_REL) LIKE '%SPLITTER%' 
        OR UPPER(NOME_PESSOA_REL) LIKE '%PAYINS%' THEN NULL
      ELSE NUMERO_CONTA_REL
    END AS NUMERO_CONTA_REL,
    TIPO_CONTA_REL,
    CASE 
      WHEN UPPER(NOME_PESSOA_REL) LIKE '%SPLITTER%' 
        OR UPPER(NOME_PESSOA_REL) LIKE '%PAYINS%' THEN NULL
      ELSE TIPO_PESSOA_REL
    END AS TIPO_PESSOA_REL,
    CASE 
      WHEN UPPER(NOME_PESSOA_REL) LIKE '%SPLITTER%' 
        OR UPPER(NOME_PESSOA_REL) LIKE '%PAYINS%' THEN NULL
      ELSE CPF_CNPJ_REL
    END AS CPF_CNPJ_REL,
    CASE 
      WHEN UPPER(NOME_PESSOA_REL) LIKE '%SPLITTER%' 
        OR UPPER(NOME_PESSOA_REL) LIKE '%PAYINS%' THEN NULL
      ELSE NOME_PESSOA_REL
    END AS NOME_PESSOA_REL
  FROM SBOX_LEGALES.STG_NQS2_AUX_PAYIN_REL_CAD_VF_FINCH
);

-- CRIAR TABELA DE FLAG DE MOVIMENTAÇÃO
-- Identifica se a conta possui movimentações no período
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_FLAG_MOV_CAD_VF_FINCH AS (
  SELECT
    TIT.CUS_CUST_ID,
    CASE 
      WHEN MOV.CUS_CUST_ID IS NULL THEN '2'  -- Sem movimentação
      ELSE '1'                                -- Com movimentação
    END AS MOVIMENTACAO_CONTA
  FROM SBOX_LEGALES.STG_QS_TITULAR_CAD_VF_FINCH TIT
  LEFT JOIN SBOX_LEGALES.STG_QS_AUX_MOVIMENTACAO2_CAD_VF_FINCH MOV
    ON CAST(TIT.CUS_CUST_ID AS STRING) = CAST(MOV.CUS_CUST_ID AS STRING)
);
