-- ============================================================================
-- BLOCO 02: COLETA DE INFORMAÇÕES REGULADAS (MELHORIA 2026)
-- ============================================================================
-- Descrição: Coleta informações da base regulada LK_REG_REGULATED_BASE_MLB
--             Substitui múltiplas consultas por uma única fonte consolidada
-- Objetivo: Melhorar performance e consistência dos dados
-- Performance: JOIN otimizado com particionamento por SIT_SITE_ID
-- Melhoria 2026: Uso de LK_REG ao invés de LK_KYC_VAULT_USER + LK_CUS_CUSTOMERS_DATA
-- ============================================================================

-- COLETAR INFORMAÇÕES DA BASE REGULADA
-- MELHORIA 2026: Uso de LK_REG_REGULATED_BASE_MLB como fonte única
-- Esta tabela consolida dados de KYC, clientes e contas em uma única fonte
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_NQS2_INFO_TIT_CAD_VF_FINCH AS (
WITH REG AS (
  SELECT
    r.DOCUMENT_NUMBER,
    r.CUS_CUST_ID,
    r.AVK_CREATED_DATETIME,
    r.FIRST_NAME,
    r.LAST_NAME,
    r.LEGAL_NAME,
    r.PREFERRED_FULL_NAME,
    r.ADDRESS_ZIP_CODE,
    r.FIS_ADRESS_LINE,
    r.INCOME,
    r.SIT_SITE_ID,
    -- Campo novo adicionado (sem renomear na origem)
    r.avk_account_id,
    -- Telefone vindo do PHONES_LIST (mais recente)
    t.PHONE_COUNTRY_CODE,
    t.PHONE_AREA_CODE,
    r.DOCUMENT_TYPE,
    t.PHONE_NUMBER
  FROM `WHOWNER.LK_REG_REGULATED_BASE_MLB` r
  LEFT JOIN UNNEST(r.PHONES_LIST) t
  WHERE r.SIT_SITE_ID = 'MLB'
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY r.DOCUMENT_NUMBER
    ORDER BY t.PHONE_LAST_UPDATED DESC
  ) = 1
)

SELECT DISTINCT
  INV.CIRCULAR_3454,
  INV.EXTRATO,
  INV.RANGE_MIN,
  INV.RANGE_MAX,
  INV.DOC_NUMBER,
  INV.IDENTIFICACAO,
  INV.FLAG_INVESTIGADO,
  INV.SISTEMA,
  -- Converte para INT64 para compatibilidade
  CAST(REG.CUS_CUST_ID AS INT64) AS CUS_CUST_ID,
  CAST(REG.AVK_CREATED_DATETIME AS DATE) AS DATA_ABERTURA,
  UPPER(
    CASE
      WHEN REG.LEGAL_NAME IS NOT NULL AND TRIM(REG.LEGAL_NAME) <> '' 
        THEN REG.LEGAL_NAME
      WHEN REG.PREFERRED_FULL_NAME IS NOT NULL AND TRIM(REG.PREFERRED_FULL_NAME) <> '' 
        THEN REG.PREFERRED_FULL_NAME
      ELSE CONCAT(REG.FIRST_NAME, ' ', REG.LAST_NAME)
    END
  ) AS NOME_INVESTIGADO,
  CASE
    WHEN LENGTH(TRIM(REG.FIS_ADRESS_LINE)) = 8 THEN REG.FIS_ADRESS_LINE
    WHEN LENGTH(TRIM(REG.ADDRESS_ZIP_CODE)) = 8 THEN REG.ADDRESS_ZIP_CODE
    ELSE NULL
  END AS CEP,
  CASE
    WHEN REG.PHONE_NUMBER IS NULL OR TRIM(REG.PHONE_NUMBER) = '' THEN NULL
    ELSE CONCAT(
      COALESCE(REG.PHONE_COUNTRY_CODE,''), 
      COALESCE(REG.PHONE_AREA_CODE,''), 
      REG.PHONE_NUMBER
    )
  END AS TELEFONE_PESSOA,
  CAST(
    CASE 
      WHEN DOCUMENT_TYPE = 'CPF' THEN 1
      WHEN DOCUMENT_TYPE = 'CNPJ' THEN 2
      WHEN LENGTH(INV.DOC_NUMBER) = 11 THEN 1
      WHEN LENGTH(INV.DOC_NUMBER) = 14 THEN 2 
      ELSE NULL 
    END 
    AS STRING
  ) AS TIPO_PESSOA,
  COALESCE(CAST(REG.INCOME AS STRING), '') AS VALOR_RENDA,
  -- Lógica de KYC integrada (Convertendo para STRING para bater com Tabela 2)
  CAST(RIGHT(KYC.kyc_completed_level, 1) AS STRING) AS KYC_LEVEL,
  INV.DATAHORA_IMPORTACAO,
  -- AVK_ID mapeado para CONTA_SPB
  CAST(REG.avk_account_id AS STRING) AS CONTA_SPB
FROM SBOX_LEGALES.STG_QS_PLANILHA_PRESENTA_CAD_VF_FINCH INV
-- Join com dados cadastrais (CTE)
LEFT JOIN REG
  ON CAST(INV.DOC_NUMBER AS STRING) = REG.DOCUMENT_NUMBER
-- Join com KYC (Novo)
LEFT JOIN `WHOWNER.BT_MP_KYC_LEVEL` KYC
  ON KYC.cus_cust_id = REG.CUS_CUST_ID
  AND KYC.kyc_expiration_date IS NULL 
  AND KYC.SIT_SITE_ID = 'MLB'
WHERE 
  (INV.CIRCULAR_3454 = 'Sim' OR INV.EXTRATO = 'Sim')
);

-- COLETAR INFORMAÇÕES POR RANGE (MELHORIA 2026)
-- Busca contas criadas no período de investigação
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_NQS2_INFO_TIT_CAD_VF_FINCH_STEP2 AS (
WITH PARAMS AS (
  SELECT DISTINCT
    DOC_NUMBER,
    RANGE_MIN,
    RANGE_MAX
  FROM SBOX_LEGALES.STG_NQS2_INFO_TIT_CAD_VF_FINCH
)
SELECT
  REG.DOCUMENT_NUMBER,
  REG.LEGAL_NAME AS LEGAL_NAME,
  REG.AVK_ACCOUNT_ID,
  REG.AVK_CREATED_DATETIME,
  PAR.RANGE_MIN,
  PAR.RANGE_MAX
FROM PARAMS PAR
JOIN `WHOWNER.LK_REG_REGULATED_BASE_MLB` REG
  ON REG.SIT_SITE_ID = 'MLB'
  AND REG.AVK_CREATED_DATETIME BETWEEN PAR.RANGE_MIN AND PAR.RANGE_MAX
  AND PAR.DOC_NUMBER = REG.DOCUMENT_NUMBER
);
