-- ============================================================================
-- BLOCO 03: PROCESSAMENTO DE TITULARES E KYC
-- ============================================================================
-- Descrição: Processa informações de titulares, identifica correspondentes
--             e não correspondentes, determina maior nível KYC
-- Objetivo: Preparar dados de titulares para processamento
-- Performance: Operações de agregação e JOIN otimizadas
-- ============================================================================

-- TRAZER APENAS INVESTIGADO COM CUS_CUST_ID (CORRESPONDENTES)
-- Investigados que possuem conta no sistema Mercado Pago
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_CORRESPONDENTE_CAD_VF_FINCH AS (
SELECT * 
FROM SBOX_LEGALES.STG_NQS2_INFO_TIT_CAD_VF_FINCH
WHERE CUS_CUST_ID IS NOT NULL
);

-- TRAZER NÃO CORRESPONDENTES
-- Investigados que não possuem conta no sistema (para Carta 3454)
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_NAO_CORRESPONDENTE_CAD_VF_FINCH AS (
SELECT * 
FROM SBOX_LEGALES.STG_NQS2_INFO_TIT_CAD_VF_FINCH
WHERE CUS_CUST_ID IS NULL
);

-- TRAZER MAIOR KYC POR DOCUMENTO
-- Determina o maior nível KYC completado para cada investigado
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_MAX_KYC_CAD_VF_FINCH AS (
SELECT 
  DOC_NUMBER,
  MAX(KYC_LEVEL) AS MAX_KYC_LEVEL
FROM SBOX_LEGALES.STG_NQS2_INFO_TIT_CAD_VF_FINCH
WHERE NOME_INVESTIGADO IS NOT NULL 
  AND TRIM(NOME_INVESTIGADO) <> '' 
  AND CEP <> '000'
GROUP BY 1
);

-- VERIFICAR QUANTOS CUS_CUST_ID TEM COM O MAIOR KYC
-- Identifica quantos clientes diferentes têm o maior nível KYC
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_QTD_CUST_MAX_KYC_CAD_VF_FINCH AS (
SELECT 
  SPB.DOC_NUMBER,
  COUNT(SPB.CUS_CUST_ID) AS QTD_CUST
FROM SBOX_LEGALES.STG_NQS2_INFO_TIT_CAD_VF_FINCH SPB
LEFT JOIN SBOX_LEGALES.STG_QS_MAX_KYC_CAD_VF_FINCH MA
  ON SPB.DOC_NUMBER = MA.DOC_NUMBER
  AND SPB.KYC_LEVEL = MA.MAX_KYC_LEVEL
WHERE MA.DOC_NUMBER IS NOT NULL
GROUP BY 1
);

-- TRAZER MAIOR CUS_CUST_ID
-- Em caso de empate, seleciona o maior CUS_CUST_ID
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_MAX_CUST_CAD_VF_FINCH AS (
SELECT
  INV.DOC_NUMBER,
  MAX(CUS_CUST_ID) AS CUS_CUST_ID
FROM SBOX_LEGALES.STG_NQS2_INFO_TIT_CAD_VF_FINCH INV
LEFT JOIN SBOX_LEGALES.STG_QS_MAX_KYC_CAD_VF_FINCH MA
  ON INV.DOC_NUMBER = MA.DOC_NUMBER
  AND INV.KYC_LEVEL = MA.MAX_KYC_LEVEL
WHERE MA.DOC_NUMBER IS NOT NULL
GROUP BY 1
);

-- TRAZER NOME E CEP ÚNICO
-- Seleciona nome e CEP únicos para cada investigado
-- Prioriza: maior KYC > maior CUS_CUST_ID > único registro
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_NOME_UNI_INV_CAD_VF_FINCH AS (
SELECT 
  DISTINCT
  SPB.DOC_NUMBER AS DOC_INVESTIGADO,
  CAST(
    UPPER(
      CASE 
        WHEN MC.DOC_NUMBER IS NOT NULL THEN SPB.NOME_INVESTIGADO
        WHEN MC.DOC_NUMBER IS NULL AND QK.QTD_CUST = 1 THEN SPB.NOME_INVESTIGADO
      END
    ) 
    AS STRING
  ) AS NOME_INVESTIGADO,
  CASE 
    WHEN MC.DOC_NUMBER IS NOT NULL THEN SPB.CEP
    WHEN MC.DOC_NUMBER IS NULL AND QK.QTD_CUST = 1 THEN SPB.CEP
  END AS CEP
FROM SBOX_LEGALES.STG_NQS2_INFO_TIT_CAD_VF_FINCH SPB
LEFT JOIN SBOX_LEGALES.STG_QS_MAX_KYC_CAD_VF_FINCH MK
  ON SPB.DOC_NUMBER = MK.DOC_NUMBER
  AND SPB.KYC_LEVEL = MK.MAX_KYC_LEVEL
LEFT JOIN SBOX_LEGALES.STG_QS_QTD_CUST_MAX_KYC_CAD_VF_FINCH QK
  ON SPB.DOC_NUMBER = QK.DOC_NUMBER
  AND SPB.KYC_LEVEL = MK.MAX_KYC_LEVEL
LEFT JOIN SBOX_LEGALES.STG_QS_MAX_CUST_CAD_VF_FINCH MC
  ON SPB.DOC_NUMBER = MC.DOC_NUMBER
  AND SPB.CUS_CUST_ID = MC.CUS_CUST_ID
WHERE
  (CASE 
    WHEN MC.DOC_NUMBER IS NOT NULL THEN SPB.CUS_CUST_ID
    WHEN MC.DOC_NUMBER IS NULL AND QK.QTD_CUST = 1 THEN SPB.CUS_CUST_ID
  END) IS NOT NULL
);

-- CRIAR TABELA COM INFORMAÇÕES DO TITULAR PARA A CARTA
-- Consolida informações finais do titular
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_TITULAR_CAD_VF_FINCH AS (
SELECT 
  DISTINCT
  INV.CIRCULAR_3454,
  INV.EXTRATO,
  INV.RANGE_MIN,
  INV.RANGE_MAX,
  INV.DOC_NUMBER,
  INV.IDENTIFICACAO,
  INV.FLAG_INVESTIGADO,
  INV.SISTEMA,
  INV.CUS_CUST_ID,
  INV.CONTA_SPB,
  INV.DATA_ABERTURA,
  COALESCE(UN.NOME_INVESTIGADO, INV.NOME_INVESTIGADO) AS NOME_INVESTIGADO,
  CASE 
    WHEN INV.CEP = '000' THEN UN.CEP
    ELSE INV.CEP
  END AS CEP,
  INV.TELEFONE_PESSOA,
  INV.VALOR_RENDA,
  -- MELHORIA 2026: Usa DATA_ABERTURA como data inicial para movimentações
  -- Evita buscar movimentações antes da criação da conta
  CASE 
    WHEN INV.DATA_ABERTURA > INV.RANGE_MIN THEN INV.DATA_ABERTURA
    ELSE INV.RANGE_MIN
  END AS MOVIMENTACAO_MIN,
  INV.DATAHORA_IMPORTACAO
FROM SBOX_LEGALES.STG_NQS2_INFO_TIT_CAD_VF_FINCH INV
LEFT JOIN SBOX_LEGALES.STG_QS_NOME_UNI_INV_CAD_VF_FINCH UN
  ON INV.DOC_NUMBER = UN.DOC_INVESTIGADO
);
