-- ============================================================================
-- RESUMO DAS TABELAS FINAIS - QUEBRA DE SIGILO POC
-- ============================================================================
-- Descrição: Query para visualizar resumo de qualidade e placeholders
--            nas tabelas finais do processo de Quebra de Sigilo (Carta Circular 3454)
-- Data: 2026-01-27
-- Foco: Qualidade dos dados e identificação de placeholders (9999, valores padrão)
-- ============================================================================

WITH RESUMO_TABELAS AS (
  -- 1. NÃO CORRESPONDENTE
  SELECT 
    'TBL_QS_NAO_CORRESPONDENTE_FINCH' AS NOME_TABELA,
    'Investigados sem conta no Mercado Pago' AS DESCRICAO,
    COUNT(*) AS TOTAL_REGISTROS,
    COUNT(DISTINCT IDENTIFICACAO) AS TOTAL_IDENTIFICACOES,
    COUNT(DISTINCT DOC_NUMBER) AS TOTAL_DOCUMENTOS,
    COUNT(DISTINCT SISTEMA) AS TOTAL_SISTEMAS,
    -- Qualidade: campos vazios
    COUNT(CASE WHEN DOC_NUMBER IS NULL OR DOC_NUMBER = '' THEN 1 END) AS QTD_DOC_NUMBER_VAZIO,
    COUNT(CASE WHEN IDENTIFICACAO IS NULL OR IDENTIFICACAO = '' THEN 1 END) AS QTD_IDENTIFICACAO_VAZIO,
    0 AS QTD_PLACEHOLDERS_9999,
    0 AS QTD_PLACEHOLDERS_OUTROS
  FROM SBOX_LEGALES.TBL_QS_NAO_CORRESPONDENTE_FINCH

  UNION ALL

  -- 2. AGÊNCIAS
  SELECT 
    'TBL_QS_AGENCIAS_FINCH' AS NOME_TABELA,
    'Informações fixas da agência Mercado Pago' AS DESCRICAO,
    COUNT(*) AS TOTAL_REGISTROS,
    COUNT(DISTINCT IDENTIFICACAO) AS TOTAL_IDENTIFICACOES,
    NULL AS TOTAL_DOCUMENTOS,
    COUNT(DISTINCT SISTEMA) AS TOTAL_SISTEMAS,
    COUNT(CASE WHEN IDENTIFICACAO IS NULL OR IDENTIFICACAO = '' THEN 1 END) AS QTD_DOC_NUMBER_VAZIO,
    COUNT(CASE WHEN NUMERO_AGENCIA IS NULL OR NUMERO_AGENCIA = '' THEN 1 END) AS QTD_IDENTIFICACAO_VAZIO,
    0 AS QTD_PLACEHOLDERS_9999,
    0 AS QTD_PLACEHOLDERS_OUTROS
  FROM SBOX_LEGALES.TBL_QS_AGENCIAS_FINCH

  UNION ALL

  -- 3. CONTAS
  SELECT 
    'TBL_QS_CONTAS_FINCH' AS NOME_TABELA,
    'Informações das contas dos investigados' AS DESCRICAO,
    COUNT(*) AS TOTAL_REGISTROS,
    COUNT(DISTINCT IDENTIFICACAO) AS TOTAL_IDENTIFICACOES,
    COUNT(DISTINCT NUMERO_CONTA) AS TOTAL_DOCUMENTOS,
    COUNT(DISTINCT SISTEMA) AS TOTAL_SISTEMAS,
    COUNT(CASE WHEN NUMERO_CONTA IS NULL OR NUMERO_CONTA = '' THEN 1 END) AS QTD_DOC_NUMBER_VAZIO,
    COUNT(CASE WHEN IDENTIFICACAO IS NULL OR IDENTIFICACAO = '' THEN 1 END) AS QTD_IDENTIFICACAO_VAZIO,
    0 AS QTD_PLACEHOLDERS_9999,
    0 AS QTD_PLACEHOLDERS_OUTROS
  FROM SBOX_LEGALES.TBL_QS_CONTAS_FINCH

  UNION ALL

  -- 4. EXTRATO
  SELECT 
    'TBL_QS_EXTRATO_FINCH' AS NOME_TABELA,
    'Movimentações financeiras detalhadas' AS DESCRICAO,
    COUNT(*) AS TOTAL_REGISTROS,
    COUNT(DISTINCT IDENTIFICACAO) AS TOTAL_IDENTIFICACOES,
    COUNT(DISTINCT CODIGO_CHAVE_EXTRATO) AS TOTAL_DOCUMENTOS,
    COUNT(DISTINCT SISTEMA) AS TOTAL_SISTEMAS,
    -- Qualidade: campos vazios e valores padrão
    COUNT(CASE WHEN CODIGO_CHAVE_EXTRATO IS NULL OR CODIGO_CHAVE_EXTRATO = '' THEN 1 END) AS QTD_DOC_NUMBER_VAZIO,
    COUNT(CASE WHEN VALOR_LANCAMENTO IS NULL OR VALOR_LANCAMENTO = '' THEN 1 END) AS QTD_IDENTIFICACAO_VAZIO,
    0 AS QTD_PLACEHOLDERS_9999,
    -- Placeholders: '0' em NUMERO_DOCUMENTO, VALOR_SALDO
    COUNT(CASE WHEN NUMERO_DOCUMENTO = '0' THEN 1 END) + 
    COUNT(CASE WHEN VALOR_SALDO = '0' THEN 1 END) AS QTD_PLACEHOLDERS_OUTROS
  FROM SBOX_LEGALES.TBL_QS_EXTRATO_FINCH

  UNION ALL

  -- 5. TITULARES
  SELECT 
    'TBL_QS_TITULARES_FINCH' AS NOME_TABELA,
    'Informações dos titulares das contas' AS DESCRICAO,
    COUNT(*) AS TOTAL_REGISTROS,
    COUNT(DISTINCT IDENTIFICACAO) AS TOTAL_IDENTIFICACOES,
    NULL AS TOTAL_DOCUMENTOS, -- Removido: CPF_CNPJ_TITULAR (dados sensíveis)
    COUNT(DISTINCT SISTEMA) AS TOTAL_SISTEMAS,
    -- Qualidade: campos vazios (sem acessar dados sensíveis)
    COUNT(CASE WHEN IDENTIFICACAO IS NULL OR IDENTIFICACAO = '' THEN 1 END) AS QTD_DOC_NUMBER_VAZIO,
    COUNT(CASE WHEN NOME_TITULAR IS NULL OR NOME_TITULAR = '' THEN 1 END) AS QTD_IDENTIFICACAO_VAZIO,
    0 AS QTD_PLACEHOLDERS_9999,
    -- Placeholders: campos vazios em datas (removido TELEFONE_PESSOA - dados sensíveis)
    COUNT(CASE WHEN DATA_ATUALIZACAO_RENDA = '' THEN 1 END) +
    COUNT(CASE WHEN DATA_FIM_RELACIONAMENTO_CONTA = '' THEN 1 END) AS QTD_PLACEHOLDERS_OUTROS
  FROM SBOX_LEGALES.TBL_QS_TITULARES_FINCH

  UNION ALL

  -- 6. ORIGEM E DESTINO (PRINCIPAL PARA PLACEHOLDERS)
  SELECT 
    'TBL_QS_ORIGEM_DESTINO_FINCH' AS NOME_TABELA,
    'Informações de origem/destino das transações' AS DESCRICAO,
    COUNT(*) AS TOTAL_REGISTROS,
    COUNT(DISTINCT IDENTIFICACAO) AS TOTAL_IDENTIFICACOES,
    COUNT(DISTINCT CODIGO_CHAVE_EXTRATO) AS TOTAL_DOCUMENTOS,
    COUNT(DISTINCT SISTEMA) AS TOTAL_SISTEMAS,
    -- Qualidade: campos vazios (removido CPF_CNPJ_OD - dados sensíveis)
    COUNT(CASE WHEN CODIGO_CHAVE_EXTRATO IS NULL OR CODIGO_CHAVE_EXTRATO = '' THEN 1 END) AS QTD_DOC_NUMBER_VAZIO,
    COUNT(CASE WHEN NOME_PESSOA_OD IS NULL OR NOME_PESSOA_OD = '' THEN 1 END) AS QTD_IDENTIFICACAO_VAZIO,
    -- Placeholders: '9999' em agência, '99999999999999999999' em conta
    COUNT(CASE WHEN NUMERO_AGENCIA_OD = '9999' THEN 1 END) +
    COUNT(CASE WHEN NUMERO_CONTA_OD = '99999999999999999999' THEN 1 END) AS QTD_PLACEHOLDERS_9999,
    -- Outros placeholders: '0', 'NAO-CORRENTISTA', campos vazios
    COUNT(CASE WHEN SITUACAO_IDENTIFICACAO = '0' THEN 1 END) +
    COUNT(CASE WHEN OBSERVACAO = 'NAO-CORRENTISTA' THEN 1 END) +
    COUNT(CASE WHEN CODIGO_DE_BARRAS = '' THEN 1 END) +
    COUNT(CASE WHEN NOME_ENDOSSANTE_CHEQUE = '' THEN 1 END) +
    COUNT(CASE WHEN DOC_ENDOSSANTE_CHEQUE = '' THEN 1 END) AS QTD_PLACEHOLDERS_OUTROS
  FROM SBOX_LEGALES.TBL_QS_ORIGEM_DESTINO_FINCH

  UNION ALL

  -- 7. CADASTRO EXTRATO NÃO CORRESPONDENTE
  SELECT 
    'CAD_TBL_QS_EXTRATO_NAO_CORRESPONDENTE_FINCH' AS NOME_TABELA,
    'Cadastro de extrato para não correspondentes' AS DESCRICAO,
    COUNT(*) AS TOTAL_REGISTROS,
    COUNT(DISTINCT IDENTIFICACAO) AS TOTAL_IDENTIFICACOES,
    NULL AS TOTAL_DOCUMENTOS,
    COUNT(DISTINCT SISTEMA) AS TOTAL_SISTEMAS,
    COUNT(CASE WHEN IDENTIFICACAO IS NULL OR IDENTIFICACAO = '' THEN 1 END) AS QTD_DOC_NUMBER_VAZIO,
    COUNT(CASE WHEN IDENTIFICACAO IS NULL OR IDENTIFICACAO = '' THEN 1 END) AS QTD_IDENTIFICACAO_VAZIO,
    0 AS QTD_PLACEHOLDERS_9999,
    0 AS QTD_PLACEHOLDERS_OUTROS
  FROM SBOX_LEGALES.CAD_TBL_QS_EXTRATO_NAO_CORRESPONDENTE_FINCH

  UNION ALL

  -- 8. CADASTRO EXTRATO MOVIMENTAÇÃO
  SELECT 
    'CAD_TBL_QS_EXTRATO_MOVIMENTACAO_FINCH' AS NOME_TABELA,
    'Cadastro de extrato de movimentação' AS DESCRICAO,
    COUNT(*) AS TOTAL_REGISTROS,
    COUNT(DISTINCT IDENTIFICACAO) AS TOTAL_IDENTIFICACOES,
    NULL AS TOTAL_DOCUMENTOS,
    COUNT(DISTINCT SISTEMA) AS TOTAL_SISTEMAS,
    COUNT(CASE WHEN IDENTIFICACAO IS NULL OR IDENTIFICACAO = '' THEN 1 END) AS QTD_DOC_NUMBER_VAZIO,
    COUNT(CASE WHEN IDENTIFICACAO IS NULL OR IDENTIFICACAO = '' THEN 1 END) AS QTD_IDENTIFICACAO_VAZIO,
    0 AS QTD_PLACEHOLDERS_9999,
    0 AS QTD_PLACEHOLDERS_OUTROS
  FROM SBOX_LEGALES.CAD_TBL_QS_EXTRATO_MOVIMENTACAO_FINCH
)

SELECT 
  NOME_TABELA,
  DESCRICAO,
  TOTAL_REGISTROS,
  TOTAL_IDENTIFICACOES,
  TOTAL_DOCUMENTOS,
  TOTAL_SISTEMAS,
  -- Métricas de qualidade
  QTD_DOC_NUMBER_VAZIO AS QTD_CAMPOS_OBRIGATORIOS_VAZIOS,
  QTD_IDENTIFICACAO_VAZIO AS QTD_CAMPOS_SECUNDARIOS_VAZIOS,
  QTD_PLACEHOLDERS_9999 AS QTD_PLACEHOLDERS_9999,
  QTD_PLACEHOLDERS_OUTROS AS QTD_PLACEHOLDERS_OUTROS,
  (QTD_PLACEHOLDERS_9999 + QTD_PLACEHOLDERS_OUTROS) AS TOTAL_PLACEHOLDERS,
  -- Percentuais de qualidade
  CASE 
    WHEN TOTAL_REGISTROS > 0 
    THEN ROUND((QTD_DOC_NUMBER_VAZIO * 100.0 / TOTAL_REGISTROS), 2)
    ELSE 0 
  END AS PCT_CAMPOS_OBRIGATORIOS_VAZIOS,
  CASE 
    WHEN TOTAL_REGISTROS > 0 
    THEN ROUND(((QTD_PLACEHOLDERS_9999 + QTD_PLACEHOLDERS_OUTROS) * 100.0 / TOTAL_REGISTROS), 2)
    ELSE 0 
  END AS PCT_PLACEHOLDERS,
  -- Média de registros por identificação
  CASE 
    WHEN TOTAL_IDENTIFICACOES > 0 
    THEN ROUND(TOTAL_REGISTROS * 1.0 / TOTAL_IDENTIFICACOES, 2)
    ELSE NULL 
  END AS MEDIA_REGISTROS_POR_IDENTIFICACAO
FROM RESUMO_TABELAS
ORDER BY TOTAL_PLACEHOLDERS DESC, TOTAL_REGISTROS DESC, NOME_TABELA;

-- ============================================================================
-- RESUMO CONSOLIDADO - QUALIDADE DOS DADOS
-- ============================================================================
WITH RESUMO_TABELAS AS (
  -- 1. NÃO CORRESPONDENTE
  SELECT 
    'TBL_QS_NAO_CORRESPONDENTE_FINCH' AS NOME_TABELA,
    'Investigados sem conta no Mercado Pago' AS DESCRICAO,
    COUNT(*) AS TOTAL_REGISTROS,
    COUNT(DISTINCT IDENTIFICACAO) AS TOTAL_IDENTIFICACOES,
    COUNT(DISTINCT DOC_NUMBER) AS TOTAL_DOCUMENTOS,
    COUNT(DISTINCT SISTEMA) AS TOTAL_SISTEMAS,
    COUNT(CASE WHEN DOC_NUMBER IS NULL OR DOC_NUMBER = '' THEN 1 END) AS QTD_DOC_NUMBER_VAZIO,
    COUNT(CASE WHEN IDENTIFICACAO IS NULL OR IDENTIFICACAO = '' THEN 1 END) AS QTD_IDENTIFICACAO_VAZIO,
    0 AS QTD_PLACEHOLDERS_9999,
    0 AS QTD_PLACEHOLDERS_OUTROS
  FROM SBOX_LEGALES.TBL_QS_NAO_CORRESPONDENTE_FINCH

  UNION ALL

  -- 2. AGÊNCIAS
  SELECT 
    'TBL_QS_AGENCIAS_FINCH' AS NOME_TABELA,
    'Informações fixas da agência Mercado Pago' AS DESCRICAO,
    COUNT(*) AS TOTAL_REGISTROS,
    COUNT(DISTINCT IDENTIFICACAO) AS TOTAL_IDENTIFICACOES,
    NULL AS TOTAL_DOCUMENTOS,
    COUNT(DISTINCT SISTEMA) AS TOTAL_SISTEMAS,
    COUNT(CASE WHEN IDENTIFICACAO IS NULL OR IDENTIFICACAO = '' THEN 1 END) AS QTD_DOC_NUMBER_VAZIO,
    COUNT(CASE WHEN NUMERO_AGENCIA IS NULL OR NUMERO_AGENCIA = '' THEN 1 END) AS QTD_IDENTIFICACAO_VAZIO,
    0 AS QTD_PLACEHOLDERS_9999,
    0 AS QTD_PLACEHOLDERS_OUTROS
  FROM SBOX_LEGALES.TBL_QS_AGENCIAS_FINCH

  UNION ALL

  -- 3. CONTAS
  SELECT 
    'TBL_QS_CONTAS_FINCH' AS NOME_TABELA,
    'Informações das contas dos investigados' AS DESCRICAO,
    COUNT(*) AS TOTAL_REGISTROS,
    COUNT(DISTINCT IDENTIFICACAO) AS TOTAL_IDENTIFICACOES,
    COUNT(DISTINCT NUMERO_CONTA) AS TOTAL_DOCUMENTOS,
    COUNT(DISTINCT SISTEMA) AS TOTAL_SISTEMAS,
    COUNT(CASE WHEN NUMERO_CONTA IS NULL OR NUMERO_CONTA = '' THEN 1 END) AS QTD_DOC_NUMBER_VAZIO,
    COUNT(CASE WHEN IDENTIFICACAO IS NULL OR IDENTIFICACAO = '' THEN 1 END) AS QTD_IDENTIFICACAO_VAZIO,
    0 AS QTD_PLACEHOLDERS_9999,
    0 AS QTD_PLACEHOLDERS_OUTROS
  FROM SBOX_LEGALES.TBL_QS_CONTAS_FINCH

  UNION ALL

  -- 4. EXTRATO
  SELECT 
    'TBL_QS_EXTRATO_FINCH' AS NOME_TABELA,
    'Movimentações financeiras detalhadas' AS DESCRICAO,
    COUNT(*) AS TOTAL_REGISTROS,
    COUNT(DISTINCT IDENTIFICACAO) AS TOTAL_IDENTIFICACOES,
    COUNT(DISTINCT CODIGO_CHAVE_EXTRATO) AS TOTAL_DOCUMENTOS,
    COUNT(DISTINCT SISTEMA) AS TOTAL_SISTEMAS,
    COUNT(CASE WHEN CODIGO_CHAVE_EXTRATO IS NULL OR CODIGO_CHAVE_EXTRATO = '' THEN 1 END) AS QTD_DOC_NUMBER_VAZIO,
    COUNT(CASE WHEN VALOR_LANCAMENTO IS NULL OR VALOR_LANCAMENTO = '' THEN 1 END) AS QTD_IDENTIFICACAO_VAZIO,
    0 AS QTD_PLACEHOLDERS_9999,
    COUNT(CASE WHEN NUMERO_DOCUMENTO = '0' THEN 1 END) + 
    COUNT(CASE WHEN VALOR_SALDO = '0' THEN 1 END) AS QTD_PLACEHOLDERS_OUTROS
  FROM SBOX_LEGALES.TBL_QS_EXTRATO_FINCH

  UNION ALL

  -- 5. TITULARES
  SELECT 
    'TBL_QS_TITULARES_FINCH' AS NOME_TABELA,
    'Informações dos titulares das contas' AS DESCRICAO,
    COUNT(*) AS TOTAL_REGISTROS,
    COUNT(DISTINCT IDENTIFICACAO) AS TOTAL_IDENTIFICACOES,
    NULL AS TOTAL_DOCUMENTOS,
    COUNT(DISTINCT SISTEMA) AS TOTAL_SISTEMAS,
    COUNT(CASE WHEN IDENTIFICACAO IS NULL OR IDENTIFICACAO = '' THEN 1 END) AS QTD_DOC_NUMBER_VAZIO,
    COUNT(CASE WHEN NOME_TITULAR IS NULL OR NOME_TITULAR = '' THEN 1 END) AS QTD_IDENTIFICACAO_VAZIO,
    0 AS QTD_PLACEHOLDERS_9999,
    COUNT(CASE WHEN DATA_ATUALIZACAO_RENDA = '' THEN 1 END) +
    COUNT(CASE WHEN DATA_FIM_RELACIONAMENTO_CONTA = '' THEN 1 END) AS QTD_PLACEHOLDERS_OUTROS
  FROM SBOX_LEGALES.TBL_QS_TITULARES_FINCH

  UNION ALL

  -- 6. ORIGEM E DESTINO
  SELECT 
    'TBL_QS_ORIGEM_DESTINO_FINCH' AS NOME_TABELA,
    'Informações de origem/destino das transações' AS DESCRICAO,
    COUNT(*) AS TOTAL_REGISTROS,
    COUNT(DISTINCT IDENTIFICACAO) AS TOTAL_IDENTIFICACOES,
    COUNT(DISTINCT CODIGO_CHAVE_EXTRATO) AS TOTAL_DOCUMENTOS,
    COUNT(DISTINCT SISTEMA) AS TOTAL_SISTEMAS,
    COUNT(CASE WHEN CODIGO_CHAVE_EXTRATO IS NULL OR CODIGO_CHAVE_EXTRATO = '' THEN 1 END) AS QTD_DOC_NUMBER_VAZIO,
    COUNT(CASE WHEN NOME_PESSOA_OD IS NULL OR NOME_PESSOA_OD = '' THEN 1 END) AS QTD_IDENTIFICACAO_VAZIO,
    COUNT(CASE WHEN NUMERO_AGENCIA_OD = '9999' THEN 1 END) +
    COUNT(CASE WHEN NUMERO_CONTA_OD = '99999999999999999999' THEN 1 END) AS QTD_PLACEHOLDERS_9999,
    COUNT(CASE WHEN SITUACAO_IDENTIFICACAO = '0' THEN 1 END) +
    COUNT(CASE WHEN OBSERVACAO = 'NAO-CORRENTISTA' THEN 1 END) +
    COUNT(CASE WHEN CODIGO_DE_BARRAS = '' THEN 1 END) +
    COUNT(CASE WHEN NOME_ENDOSSANTE_CHEQUE = '' THEN 1 END) +
    COUNT(CASE WHEN DOC_ENDOSSANTE_CHEQUE = '' THEN 1 END) AS QTD_PLACEHOLDERS_OUTROS
  FROM SBOX_LEGALES.TBL_QS_ORIGEM_DESTINO_FINCH

  UNION ALL

  -- 7. CADASTRO EXTRATO NÃO CORRESPONDENTE
  SELECT 
    'CAD_TBL_QS_EXTRATO_NAO_CORRESPONDENTE_FINCH' AS NOME_TABELA,
    'Cadastro de extrato para não correspondentes' AS DESCRICAO,
    COUNT(*) AS TOTAL_REGISTROS,
    COUNT(DISTINCT IDENTIFICACAO) AS TOTAL_IDENTIFICACOES,
    NULL AS TOTAL_DOCUMENTOS,
    COUNT(DISTINCT SISTEMA) AS TOTAL_SISTEMAS,
    COUNT(CASE WHEN IDENTIFICACAO IS NULL OR IDENTIFICACAO = '' THEN 1 END) AS QTD_DOC_NUMBER_VAZIO,
    COUNT(CASE WHEN IDENTIFICACAO IS NULL OR IDENTIFICACAO = '' THEN 1 END) AS QTD_IDENTIFICACAO_VAZIO,
    0 AS QTD_PLACEHOLDERS_9999,
    0 AS QTD_PLACEHOLDERS_OUTROS
  FROM SBOX_LEGALES.CAD_TBL_QS_EXTRATO_NAO_CORRESPONDENTE_FINCH

  UNION ALL

  -- 8. CADASTRO EXTRATO MOVIMENTAÇÃO
  SELECT 
    'CAD_TBL_QS_EXTRATO_MOVIMENTACAO_FINCH' AS NOME_TABELA,
    'Cadastro de extrato de movimentação' AS DESCRICAO,
    COUNT(*) AS TOTAL_REGISTROS,
    COUNT(DISTINCT IDENTIFICACAO) AS TOTAL_IDENTIFICACOES,
    NULL AS TOTAL_DOCUMENTOS,
    COUNT(DISTINCT SISTEMA) AS TOTAL_SISTEMAS,
    COUNT(CASE WHEN IDENTIFICACAO IS NULL OR IDENTIFICACAO = '' THEN 1 END) AS QTD_DOC_NUMBER_VAZIO,
    COUNT(CASE WHEN IDENTIFICACAO IS NULL OR IDENTIFICACAO = '' THEN 1 END) AS QTD_IDENTIFICACAO_VAZIO,
    0 AS QTD_PLACEHOLDERS_9999,
    0 AS QTD_PLACEHOLDERS_OUTROS
  FROM SBOX_LEGALES.CAD_TBL_QS_EXTRATO_MOVIMENTACAO_FINCH
)
SELECT 
  'RESUMO CONSOLIDADO - QUALIDADE' AS TIPO,
  COUNT(DISTINCT NOME_TABELA) AS TOTAL_TABELAS,
  SUM(TOTAL_REGISTROS) AS TOTAL_REGISTROS_GERAL,
  SUM(TOTAL_IDENTIFICACOES) AS TOTAL_IDENTIFICACOES_GERAL,
  SUM(COALESCE(TOTAL_DOCUMENTOS, 0)) AS TOTAL_DOCUMENTOS_GERAL,
  -- Totais de placeholders
  SUM(QTD_PLACEHOLDERS_9999) AS TOTAL_PLACEHOLDERS_9999,
  SUM(QTD_PLACEHOLDERS_OUTROS) AS TOTAL_PLACEHOLDERS_OUTROS,
  SUM(QTD_PLACEHOLDERS_9999 + QTD_PLACEHOLDERS_OUTROS) AS TOTAL_PLACEHOLDERS_GERAL,
  -- Totais de campos vazios
  SUM(QTD_DOC_NUMBER_VAZIO) AS TOTAL_CAMPOS_OBRIGATORIOS_VAZIOS,
  SUM(QTD_IDENTIFICACAO_VAZIO) AS TOTAL_CAMPOS_SECUNDARIOS_VAZIOS,
  -- Percentuais gerais
  CASE 
    WHEN SUM(TOTAL_REGISTROS) > 0 
    THEN ROUND((SUM(QTD_PLACEHOLDERS_9999 + QTD_PLACEHOLDERS_OUTROS) * 100.0 / SUM(TOTAL_REGISTROS)), 2)
    ELSE 0 
  END AS PCT_PLACEHOLDERS_GERAL,
  CASE 
    WHEN SUM(TOTAL_REGISTROS) > 0 
    THEN ROUND((SUM(QTD_DOC_NUMBER_VAZIO) * 100.0 / SUM(TOTAL_REGISTROS)), 2)
    ELSE 0 
  END AS PCT_CAMPOS_VAZIOS_GERAL
FROM RESUMO_TABELAS;

-- ============================================================================
-- DETALHAMENTO DE PLACEHOLDERS - ORIGEM E DESTINO
-- ============================================================================
-- Análise detalhada dos placeholders na tabela mais crítica
SELECT 
  'DETALHAMENTO PLACEHOLDERS - ORIGEM/DESTINO' AS TIPO,
  COUNT(*) AS TOTAL_REGISTROS,
  -- Placeholders 9999
  COUNT(CASE WHEN NUMERO_AGENCIA_OD = '9999' THEN 1 END) AS QTD_AGENCIA_9999,
  COUNT(CASE WHEN NUMERO_CONTA_OD = '99999999999999999999' THEN 1 END) AS QTD_CONTA_99999999999999999999,
  -- Outros placeholders
  COUNT(CASE WHEN SITUACAO_IDENTIFICACAO = '0' THEN 1 END) AS QTD_SITUACAO_0,
  COUNT(CASE WHEN OBSERVACAO = 'NAO-CORRENTISTA' THEN 1 END) AS QTD_NAO_CORRENTISTA,
  COUNT(CASE WHEN OBSERVACAO = 'CORRENTISTA' THEN 1 END) AS QTD_CORRENTISTA,
  -- Campos vazios críticos (removido CPF_CNPJ_OD - dados sensíveis)
  COUNT(CASE WHEN NOME_PESSOA_OD IS NULL OR NOME_PESSOA_OD = '' THEN 1 END) AS QTD_NOME_VAZIO,
  COUNT(CASE WHEN NUMERO_BANCO_OD IS NULL OR NUMERO_BANCO_OD = '' THEN 1 END) AS QTD_BANCO_VAZIO,
  -- Percentuais
  ROUND(COUNT(CASE WHEN NUMERO_AGENCIA_OD = '9999' THEN 1 END) * 100.0 / COUNT(*), 2) AS PCT_AGENCIA_9999,
  ROUND(COUNT(CASE WHEN NUMERO_CONTA_OD = '99999999999999999999' THEN 1 END) * 100.0 / COUNT(*), 2) AS PCT_CONTA_99999999999999999999,
  ROUND(COUNT(CASE WHEN OBSERVACAO = 'NAO-CORRENTISTA' THEN 1 END) * 100.0 / COUNT(*), 2) AS PCT_NAO_CORRENTISTA
FROM SBOX_LEGALES.TBL_QS_ORIGEM_DESTINO_FINCH;

-- ============================================================================
-- DETALHAMENTO DE PLACEHOLDERS - EXTRATO
-- ============================================================================
SELECT 
  'DETALHAMENTO PLACEHOLDERS - EXTRATO' AS TIPO,
  COUNT(*) AS TOTAL_REGISTROS,
  -- Placeholders '0'
  COUNT(CASE WHEN NUMERO_DOCUMENTO = '0' THEN 1 END) AS QTD_NUMERO_DOC_0,
  COUNT(CASE WHEN VALOR_SALDO = '0' THEN 1 END) AS QTD_VALOR_SALDO_0,
  -- Campos vazios
  COUNT(CASE WHEN CODIGO_CHAVE_EXTRATO IS NULL OR CODIGO_CHAVE_EXTRATO = '' THEN 1 END) AS QTD_CODIGO_CHAVE_VAZIO,
  COUNT(CASE WHEN VALOR_LANCAMENTO IS NULL OR VALOR_LANCAMENTO = '' THEN 1 END) AS QTD_VALOR_LANCAMENTO_VAZIO,
  COUNT(CASE WHEN DESCRICAO_LANCAMENTO IS NULL OR DESCRICAO_LANCAMENTO = '' THEN 1 END) AS QTD_DESCRICAO_VAZIO,
  -- Percentuais
  ROUND(COUNT(CASE WHEN NUMERO_DOCUMENTO = '0' THEN 1 END) * 100.0 / COUNT(*), 2) AS PCT_NUMERO_DOC_0,
  ROUND(COUNT(CASE WHEN VALOR_SALDO = '0' THEN 1 END) * 100.0 / COUNT(*), 2) AS PCT_VALOR_SALDO_0
FROM SBOX_LEGALES.TBL_QS_EXTRATO_FINCH;

-- ============================================================================
-- OBSERVAÇÕES:
-- ============================================================================
-- 1. Placeholders identificados:
--    - '9999' em NUMERO_AGENCIA_OD (quando agência não informada)
--    - '99999999999999999999' em NUMERO_CONTA_OD (quando conta não informada)
--    - '0' em vários campos (NUMERO_DOCUMENTO, VALOR_SALDO, SITUACAO_IDENTIFICACAO)
--    - '' (vazio) em campos opcionais ou não preenchidos
--    - 'NAO-CORRENTISTA' quando relacionado não identificado
--
-- 2. Métricas de qualidade focam em:
--    - Campos obrigatórios vazios
--    - Quantidade de placeholders por tipo
--    - Percentuais de dados com placeholders
--
-- 3. As tabelas CAD podem estar vazias se não forem populadas no processo.
--
-- 4. Para executar apenas o resumo detalhado, use apenas a primeira query.
--    Para executar apenas o resumo consolidado, use apenas a segunda query.
--
-- 5. DADOS SENSÍVEIS REMOVIDOS:
--    - CPF_CNPJ_TITULAR (TBL_QS_TITULARES_FINCH) - protegido por policy tag
--    - CPF_CNPJ_OD (TBL_QS_ORIGEM_DESTINO_FINCH) - protegido por policy tag
--    - TELEFONE_PESSOA (TBL_QS_TITULARES_FINCH) - protegido por policy tag
--    Estas colunas foram removidas para evitar erros de acesso negado.
-- ============================================================================
