WITH TAREFAS_REITERACAO_DE_OFICIO AS (
  SELECT *
  FROM `pdme000426-c1s7scatwm0-furyid.STG.LK_PBD_LA_VW_TAREFAS_AGENDAMENTOS_CLEAN`
  WHERE UPPER(TRIM(FASE_DE_WORKFLOW)) IN (
    'ELABORAR RESPOSTA DE REITERAÇÃO DE OFÍCIO',
    'ELABORAR SUBSÍDIO DE REITERAÇÃO DE OFÍCIO',
    'REITERAÇÃO DE OFÍCIO'
  )
),

REITERACAO_DE_OFICIO AS (
  SELECT
    PROCESSO_ID,
    MAX(PARSE_DATE('%d/%m/%Y', DATA_DE_CONFIRMACAO)) AS DT_REITERACAO_DE_OFICIO
  FROM TAREFAS_REITERACAO_DE_OFICIO
  WHERE UPPER(TRIM(FASE_DE_WORKFLOW)) = 'REITERAÇÃO DE OFÍCIO'
  GROUP BY PROCESSO_ID
),

ELABORAR_SUBSIDIO_REITERACAO AS (
  SELECT
    PROCESSO_ID,
    MAX(PARSE_DATE('%d/%m/%Y', DATA_DE_CONFIRMACAO)) AS DT_ELABORAR_SUBSIDIO
  FROM TAREFAS_REITERACAO_DE_OFICIO
  WHERE UPPER(TRIM(FASE_DE_WORKFLOW)) = 'ELABORAR SUBSÍDIO DE REITERAÇÃO DE OFÍCIO'
  GROUP BY PROCESSO_ID
),

ELABORAR_RESPOSTA_REITERACAO AS (
  SELECT
    PROCESSO_ID,
    MAX(PARSE_DATE('%d/%m/%Y', DATA_DE_CONFIRMACAO)) AS DT_ELABORAR_RESPOSTA
  FROM TAREFAS_REITERACAO_DE_OFICIO
  WHERE UPPER(TRIM(FASE_DE_WORKFLOW)) = 'ELABORAR RESPOSTA DE REITERAÇÃO DE OFÍCIO'
  GROUP BY PROCESSO_ID
),

BASE_TEMP AS (
  SELECT
    COALESCE(r.PROCESSO_ID, s.PROCESSO_ID, e.PROCESSO_ID) AS PROCESSO_ID,
    r.DT_REITERACAO_DE_OFICIO,
    s.DT_ELABORAR_SUBSIDIO,
    e.DT_ELABORAR_RESPOSTA,
    DATE_DIFF(s.DT_ELABORAR_SUBSIDIO, r.DT_REITERACAO_DE_OFICIO, DAY) AS Tempo_de_Subs,
    DATE_DIFF(e.DT_ELABORAR_RESPOSTA, s.DT_ELABORAR_SUBSIDIO, DAY) AS Tempo_de_resposta,
    DATE_DIFF(e.DT_ELABORAR_RESPOSTA, r.DT_REITERACAO_DE_OFICIO, DAY) AS Tempo_de_reiteracao
  FROM REITERACAO_DE_OFICIO r
  FULL OUTER JOIN ELABORAR_SUBSIDIO_REITERACAO s ON r.PROCESSO_ID = s.PROCESSO_ID
  FULL OUTER JOIN ELABORAR_RESPOSTA_REITERACAO e ON COALESCE(r.PROCESSO_ID, s.PROCESSO_ID) = e.PROCESSO_ID
)

SELECT 
  PROCESSO_ID,
  DT_REITERACAO_DE_OFICIO,
  atributo AS FASE,
  valor AS DIAS
FROM BASE_TEMP,
UNNEST([
  STRUCT('Tempo_de_Subs' AS atributo, CAST(Tempo_de_Subs AS INT64) AS valor),
  STRUCT('Tempo_de_resposta', CAST(Tempo_de_resposta AS INT64)),
  STRUCT('Tempo_de_reiteracao', CAST(Tempo_de_reiteracao AS INT64))
]) AS unpivoted
