-- TABELA 1
SELECT
    *
FROM
    `pdme000426-c1s7scatwm0-furyid.STG.LK_PBD_LA_VW_TAREFAS_AGENDAMENTOS_CLEAN`
WHERE
    UPPER(TRIM(FASE_DE_WORKFLOW)) IN (
        'ELABORAR RESPOSTA DE REITERAÇÃO DE OFÍCIO',
        'ELABORAR SUBSÍDIO DE REITERAÇÃO DE OFÍCIO',
        'REITERAÇÃO DE OFÍCIO'
    ) 
    
    
    
-- TABELA 2
SELECT
    PROCESSO_ID,
    pais,
    data_registrado AS DATA_REGISTRADO
FROM
    `pdme000426-c1s7scatwm0-furyid.STG.TBL_FINAL_CONSOLIDADA_OFICIOS_EMBARGOS`