-- Cálculo de TMA para Brasil
WITH AJUSTE_DE_CADASTRO_AGRUPADO AS (
    SELECT
        PAIS,
        PROCESSO_ID,
        MAX(SAFE.PARSE_DATE('%d/%m/%Y', DATA_DE_CONFIRMACAO)) AS MAX_TAREFA_1
    FROM `pdme000426-c1s7scatwm0-furyid.STG.LK_PBD_LA_VW_TAREFAS_AGENDAMENTOS_CLEAN`
    WHERE 
        UPPER(TRIM(FASE_DE_WORKFLOW)) IN ('AJUSTE DE CADASTRO')
        OR UPPER(TRIM(WORKFLOW)) IN ('AJUSTE DE CADASTRO')
        AND status <> "Cancelado"
    GROUP BY PAIS, PROCESSO_ID
),

VALIDACAO_CADASTRO_AGRUPADO AS (
    SELECT
        PROCESSO_ID,
        MAX(SAFE.PARSE_DATE('%d/%m/%Y', DATA_DE_CONFIRMACAO)) AS MAX_TAREFA_2
    FROM `pdme000426-c1s7scatwm0-furyid.STG.LK_PBD_LA_VW_TAREFAS_AGENDAMENTOS_CLEAN`
    WHERE 
        UPPER(TRIM(FASE_DE_WORKFLOW)) = 'VALIDAÇÃO - CADASTRO AJUSTADO'
        AND status <> "Cancelado"
    GROUP BY PROCESSO_ID
),

BLOCO_BRASIL AS (
    SELECT 
        a.PAIS,
        a.PROCESSO_ID,
        a.MAX_TAREFA_1,
        v.MAX_TAREFA_2,
        GREATEST(DATE_DIFF(v.MAX_TAREFA_2, a.MAX_TAREFA_1, DAY), 0) AS TMA_TAREFAS,
        'Tarefa' AS TIPO
    FROM AJUSTE_DE_CADASTRO_AGRUPADO a
    LEFT JOIN VALIDACAO_CADASTRO_AGRUPADO v
        ON a.PROCESSO_ID = v.PROCESSO_ID
    -- WHERE v.MAX_TAREFA_2 IS NOT NULL
),

-- Cálculo de TMA para Hispanos
AJUSTE_DE_REGISTRO_HISP AS (
    SELECT
        PAIS,
        PROCESSO_ID,
        FASE_DE_WORKFLOW,
        MAX(SAFE.PARSE_DATE('%d/%m/%Y', DATA_DE_CONFIRMACAO)) AS MAX_TAREFA_1
    FROM `pdme000426-c1s7scatwm0-furyid.STG.LK_PBD_LA_VW_TAREFAS_AGENDAMENTOS_CLEAN`
    WHERE 
        UPPER(TRIM(FASE_DE_WORKFLOW)) = 'AJUSTE DE REGISTRO'
        AND STATUS <> 'Cancelado'
    GROUP BY PAIS, PROCESSO_ID, FASE_DE_WORKFLOW
),

VALIDACAO_CADASTRO_AGRUPADO_HISP AS (
    SELECT
        PROCESSO_ID,
        MAX(SAFE.PARSE_DATE('%d/%m/%Y', DATA_DE_CONFIRMACAO)) AS MAX_TAREFA_2
    FROM `pdme000426-c1s7scatwm0-furyid.STG.LK_PBD_LA_VW_TAREFAS_AGENDAMENTOS_CLEAN`
    WHERE 
        UPPER(TRIM(FASE_DE_WORKFLOW)) = 'VALIDACIÓN - AJUSTE DE REGISTRO'
        AND status <> "Cancelado"
    GROUP BY PROCESSO_ID
),

BLOCO_HISPANOS AS (
    SELECT 
        a.PAIS,
        a.PROCESSO_ID,
        a.MAX_TAREFA_1,
        v.MAX_TAREFA_2,
        GREATEST(DATE_DIFF(v.MAX_TAREFA_2, a.MAX_TAREFA_1, DAY), 0) AS TMA_TAREFAS,
        'Tarefa' AS TIPO
    FROM AJUSTE_DE_REGISTRO_HISP a
    LEFT JOIN VALIDACAO_CADASTRO_AGRUPADO_HISP v
        ON a.PROCESSO_ID = v.PROCESSO_ID
    -- WHERE v.MAX_TAREFA_2 IS NOT NULL
),

resultado AS (
    -- Resultado final unificado
    SELECT * FROM BLOCO_BRASIL
    UNION ALL
    SELECT * FROM BLOCO_HISPANOS
)

SELECT *
FROM resultado
WHERE MAX_TAREFA_1 >= DATE '2024-01-01'
