WITH CASOS_RECEBIDOS AS (
    SELECT
        SAFE.PARSE_DATE('%d/%m/%Y', DATA_ENVIO_SISBACEN) AS DATA_ENVIO_SISBACEN,
        SAFE.PARSE_DATE('%d/%m/%Y', DATA_RECEBIMENTO_INST) AS DATA_RECEBIMENTO_INST,
        ORIGEM,
        TIPO_DE_OFICIO,
        NO_PROTOCOLO,
        NO_PROCESSO,
        INSTITUICAO,
        NOME_DO_SOLICITANTE,
        NOME_DA_VARA_JUIZO,
        TRIBUNAL,
        CPF_CNPJ,
        PESSOA,
        TRIM(CAST(CCS_NUMERO_DO_CASO AS STRING)) AS CCS_NUMERO_DO_CASO,
        CCS_INICIO_DO_PERIODO_SOLICITADO,
        CCS_FIM_DO_PERIODO_SOLICITADO,
        CCS_PRAZO_LIMITE_DE_RESPOSTA,
        CCS_HASHTAGS,
        CCS_SISTEMA_DE_ENTREGA,
        STATUS,
        AUD_INS_DTTM,
        AUD_UPD_DTTM
    FROM
        `pdme000426-c1s7scatwm0-furyid.TBL.LK_PBD_LA_QUEBRA_DE_SIGILO_CONTROLE`
)

SELECT * FROM CASOS_RECEBIDOS;
