-- ============================================================================
-- BLOCO 00 - DDL: Criação das tabelas zeradas (estrutura do modelo original)
-- ============================================================================
-- Objetivo: Criar no ambiente novo (<ENV>.STG) todas as tabelas vazias com
--           a estrutura correta, para o BLOCO_00 e o pipeline funcionarem.
-- Uso: Substitua <ENV> pelo project ID do ambiente (ex.: dme000426).
-- Nota: Dim_DATE não veio no export; se existir na origem, inclua manualmente
--       ou crie após rodar este script.
-- Execução: Script BigQuery (BEGIN/END) para rodar múltiplos CREATE em um job.
-- ============================================================================

BEGIN
  -- CAD_TBL_QS_EXTRATO_MOVIMENTACAO
  CREATE TABLE IF NOT EXISTS `<ENV>.STG.CAD_TBL_QS_EXTRATO_MOVIMENTACAO` (
  VERTICAL STRING,
  IDENTIFICACAO STRING,
  TIPO_MOVIMENTO STRING,
  DOC_INVESTIGADO STRING,
  CUS_CUST_ID STRING,
  MOV_CREATED_DT DATE,
  ID_PAGAMENTO STRING,
  MOV_TYPE_ID STRING,
  MOV_DETAIL STRING,
  MOV_STATUS_ID STRING,
  MOV_AMOUNT STRING,
  MOV_BALANCED_AMOUNT STRING,
  DATAHORA_IMPORTACAO DATETIME
  );

  -- CAD_TBL_QS_EXTRATO_NAO_CORRESPONDENTE
  CREATE TABLE IF NOT EXISTS `<ENV>.STG.CAD_TBL_QS_EXTRATO_NAO_CORRESPONDENTE` (
  VERTICAL STRING,
  IDENTIFICACAO STRING,
  DOC_NUMBER STRING,
  SISTEMA STRING,
  DATA_IMPORTACAO DATE,
  DATAHORA_IMPORTACAO DATETIME
  );

  -- Dim_Instituicoes
  CREATE TABLE IF NOT EXISTS `<ENV>.STG.Dim_Instituicoes` (
  ISPB INT64,
  NOME_REDUZIDO STRING,
  NUMERO_CODIGO STRING,
  PARTICIPA_DA_COMPE STRING,
  ACESSO_PRINCIPAL STRING,
  NOME_EXTENSO STRING,
  INICIO_DA_OPERACAO DATE
  );

  -- STG_QS_AUX_MOVIMENTACAO2_CAD_VF
  CREATE TABLE IF NOT EXISTS `<ENV>.STG.STG_QS_AUX_MOVIMENTACAO2_CAD_VF` (
  EXCLUIR STRING,
  CUS_CUST_ID INT64,
  CODIGO_CHAVE_EXTRATO STRING,
  DATA_LANCAMENTO DATE,
  DESCRICAO_LANCAMENTO STRING,
  TIPO_LANCAMENTO STRING,
  VALOR_LANCAMENTO STRING,
  NATUREZA_LANCAMENTO STRING,
  NATUREZA_SALDO STRING,
  ID_RELACIONADO NUMERIC,
  ID_PAGAMENTO NUMERIC,
  TBL_RELACIONADO STRING,
  MOV_DETAIL STRING,
  MOV_TYPE_ID STRING,
  MOV_LABEL STRING
);

-- STG_QS_AUX_MOVIMENTACAO_CAD_VF
CREATE TABLE IF NOT EXISTS `<ENV>.STG.STG_QS_AUX_MOVIMENTACAO_CAD_VF` (
  CUS_CUST_ID INT64,
  CODIGO_CHAVE_EXTRATO STRING,
  DATA_LANCAMENTO DATE,
  DESCRICAO_LANCAMENTO STRING,
  TIPO_LANCAMENTO STRING,
  VALOR_LANCAMENTO STRING,
  NATUREZA_LANCAMENTO STRING,
  NATUREZA_SALDO STRING,
  ID_RELACIONADO NUMERIC,
  ID_PAGAMENTO NUMERIC,
  TBL_RELACIONADO STRING,
  MOV_DETAIL STRING,
  MOV_TYPE_ID STRING,
  MOV_LABEL STRING
);

-- STG_QS_AUX_PAYIN_CAD_VF
CREATE TABLE IF NOT EXISTS `<ENV>.STG.STG_QS_AUX_PAYIN_CAD_VF` (
  ID_PAGAMENTO NUMERIC,
  CODIGO_CHAVE_EXTRATO STRING
);

-- STG_QS_AUX_PAYIN_REL_CAD_VF
CREATE TABLE IF NOT EXISTS `<ENV>.STG.STG_QS_AUX_PAYIN_REL_CAD_VF` (
  ID_PAGAMENTO NUMERIC,
  CODIGO_CHAVE_EXTRATO STRING,
  NOME_BANCO_REL STRING,
  NUMERO_BANCO_REL STRING,
  NUMERO_AGENCIA_REL STRING,
  NUMERO_CONTA_REL STRING,
  TIPO_CONTA_REL STRING,
  TIPO_PESSOA_REL STRING,
  CPF_CNPJ_REL STRING,
  NOME_PESSOA_REL STRING
);

-- STG_QS_AUX_PAYMENTS_COMID_CAD_VF
CREATE TABLE IF NOT EXISTS `<ENV>.STG.STG_QS_AUX_PAYMENTS_COMID_CAD_VF` (
  ID_PAGAMENTO NUMERIC,
  ID_RELACIONADO NUMERIC,
  CUS_CUST_ID INT64,
  CODIGO_CHAVE_EXTRATO STRING
);

-- STG_QS_AUX_PAYMENTS_SEMID_CAD_VF
CREATE TABLE IF NOT EXISTS `<ENV>.STG.STG_QS_AUX_PAYMENTS_SEMID_CAD_VF` (
  ID_PAGAMENTO NUMERIC,
  ID_RELACIONADO NUMERIC,
  CUS_CUST_ID INT64,
  CODIGO_CHAVE_EXTRATO STRING
);

-- STG_QS_AUX_PAYOUT_CAD_VF
CREATE TABLE IF NOT EXISTS `<ENV>.STG.STG_QS_AUX_PAYOUT_CAD_VF` (
  ID_PAGAMENTO NUMERIC,
  CODIGO_CHAVE_EXTRATO STRING
);

-- STG_QS_AUX_PAYOUT_REL_CAD_VF
CREATE TABLE IF NOT EXISTS `<ENV>.STG.STG_QS_AUX_PAYOUT_REL_CAD_VF` (
  ID_PAGAMENTO NUMERIC,
  CODIGO_CHAVE_EXTRATO STRING,
  NOME_BANCO_REL STRING,
  NUMERO_BANCO_REL STRING,
  NUMERO_AGENCIA_REL STRING,
  NUMERO_CONTA_REL STRING,
  TIPO_CONTA_REL STRING,
  TIPO_PESSOA_REL STRING,
  CPF_CNPJ_REL STRING,
  NOME_PESSOA_REL STRING
);

-- STG_QS_AUX_WITHDRAWAL_CAD_VF
CREATE TABLE IF NOT EXISTS `<ENV>.STG.STG_QS_AUX_WITHDRAWAL_CAD_VF` (
  ID_PAGAMENTO NUMERIC,
  CODIGO_CHAVE_EXTRATO STRING
);

-- STG_QS_CORRESPONDENTE_CAD_VF
CREATE TABLE IF NOT EXISTS `<ENV>.STG.STG_QS_CORRESPONDENTE_CAD_VF` (
  CIRCULAR_3454 STRING,
  EXTRATO STRING,
  RANGE_MIN DATE,
  RANGE_MAX DATE,
  DOC_NUMBER STRING,
  IDENTIFICACAO STRING,
  FLAG_INVESTIGADO STRING,
  SISTEMA STRING,
  CUS_CUST_ID INT64,
  DATA_ABERTURA DATE,
  NOME_INVESTIGADO STRING,
  CEP STRING,
  TELEFONE_PESSOA STRING,
  VALOR_RENDA STRING,
  DATAHORA_IMPORTACAO DATETIME,
  KYC_LEVEL STRING
);

-- STG_QS_FLAG_MOV_CAD_VF
CREATE TABLE IF NOT EXISTS `<ENV>.STG.STG_QS_FLAG_MOV_CAD_VF` (
  CUS_CUST_ID INT64,
  MOVIMENTACAO_CONTA STRING
);

-- STG_QS_INFO_TIT_CAD_VF
CREATE TABLE IF NOT EXISTS `<ENV>.STG.STG_QS_INFO_TIT_CAD_VF` (
  CIRCULAR_3454 STRING,
  EXTRATO STRING,
  RANGE_MIN DATE,
  RANGE_MAX DATE,
  DOC_NUMBER STRING,
  IDENTIFICACAO STRING,
  FLAG_INVESTIGADO STRING,
  SISTEMA STRING,
  CUS_CUST_ID INT64,
  DATA_ABERTURA DATE,
  NOME_INVESTIGADO STRING,
  CEP STRING,
  TELEFONE_PESSOA STRING,
  VALOR_RENDA STRING,
  KYC_LEVEL STRING,
  DATAHORA_IMPORTACAO DATETIME
);

-- STG_QS_INFO_TIT_KYC_CAD_VF
CREATE TABLE IF NOT EXISTS `<ENV>.STG.STG_QS_INFO_TIT_KYC_CAD_VF` (
  CIRCULAR_3454 STRING,
  EXTRATO STRING,
  RANGE_MIN DATE,
  RANGE_MAX DATE,
  DOC_NUMBER STRING,
  IDENTIFICACAO STRING,
  FLAG_INVESTIGADO STRING,
  SISTEMA STRING,
  CUS_CUST_ID INT64,
  DATA_ABERTURA DATE,
  NOME_INVESTIGADO STRING,
  CEP STRING,
  TELEFONE_PESSOA STRING,
  VALOR_RENDA STRING,
  DATAHORA_IMPORTACAO DATETIME,
  KYC_LEVEL STRING
);

-- STG_QS_MAX_CUST_CAD_VF
CREATE TABLE IF NOT EXISTS `<ENV>.STG.STG_QS_MAX_CUST_CAD_VF` (
  DOC_NUMBER STRING,
  CUS_CUST_ID INT64
);

-- STG_QS_MAX_KYC_CAD_VF
CREATE TABLE IF NOT EXISTS `<ENV>.STG.STG_QS_MAX_KYC_CAD_VF` (
  DOC_NUMBER STRING,
  MAX_KYC_LEVEL STRING
);

-- STG_QS_NAO_CORRESPONDENTE_CAD_VF
CREATE TABLE IF NOT EXISTS `<ENV>.STG.STG_QS_NAO_CORRESPONDENTE_CAD_VF` (
  CIRCULAR_3454 STRING,
  EXTRATO STRING,
  RANGE_MIN DATE,
  RANGE_MAX DATE,
  DOC_NUMBER STRING,
  IDENTIFICACAO STRING,
  FLAG_INVESTIGADO STRING,
  SISTEMA STRING,
  CUS_CUST_ID INT64,
  DATA_ABERTURA DATE,
  NOME_INVESTIGADO STRING,
  CEP STRING,
  TELEFONE_PESSOA STRING,
  VALOR_RENDA STRING,
  DATAHORA_IMPORTACAO DATETIME,
  KYC_LEVEL STRING
);

-- STG_QS_NOME_UNI_INV_CAD_VF
CREATE TABLE IF NOT EXISTS `<ENV>.STG.STG_QS_NOME_UNI_INV_CAD_VF` (
  DOC_INVESTIGADO STRING,
  NOME_INVESTIGADO STRING,
  CEP STRING
);

-- STG_QS_PAGAMENTO_CAD_VF
CREATE TABLE IF NOT EXISTS `<ENV>.STG.STG_QS_PAGAMENTO_CAD_VF` (
  ID_PAGAMENTO NUMERIC,
  ID_RELACIONADO NUMERIC,
  CODIGO_CHAVE_EXTRATO STRING,
  PAY_REASON_ID STRING
);

-- STG_QS_PAGAMENTO_REL_CAD_VF
CREATE TABLE IF NOT EXISTS `<ENV>.STG.STG_QS_PAGAMENTO_REL_CAD_VF` (
  ID_PAGAMENTO NUMERIC,
  CODIGO_CHAVE_EXTRATO STRING,
  NUMERO_CONTA_REL STRING,
  TIPO_PESSOA_REL STRING,
  CPF_CNPJ_REL STRING,
  NOME_REL STRING
);

-- STG_QS_PLANILHA_PRESENTA_CAD_VF
CREATE TABLE IF NOT EXISTS `<ENV>.STG.STG_QS_PLANILHA_PRESENTA_CAD_VF` (
  CIRCULAR_3454 STRING,
  EXTRATO STRING,
  RANGE_MIN DATE,
  RANGE_MAX DATE,
  DOC_NUMBER STRING,
  IDENTIFICACAO STRING,
  FLAG_INVESTIGADO STRING,
  SISTEMA STRING,
  DATAHORA_IMPORTACAO DATETIME
);

-- STG_QS_QTD_CUST_MAX_KYC_CAD_VF
CREATE TABLE IF NOT EXISTS `<ENV>.STG.STG_QS_QTD_CUST_MAX_KYC_CAD_VF` (
  DOC_NUMBER STRING,
  QTD_CUST INT64
);

-- STG_QS_RELACIONADO_CAD_VF
CREATE TABLE IF NOT EXISTS `<ENV>.STG.STG_QS_RELACIONADO_CAD_VF` (
  ID_PAGAMENTO NUMERIC,
  CODIGO_CHAVE_EXTRATO STRING,
  NUMERO_BANCO_REL STRING,
  NUMERO_AGENCIA_REL STRING,
  NUMERO_CONTA_REL STRING,
  TIPO_CONTA_REL STRING,
  TIPO_PESSOA_REL STRING,
  CPF_CNPJ_REL STRING,
  NOME_PESSOA_REL STRING
);

-- STG_QS_SPB_CAD_VF
CREATE TABLE IF NOT EXISTS `<ENV>.STG.STG_QS_SPB_CAD_VF` (
  CIRCULAR_3454 STRING,
  EXTRATO STRING,
  RANGE_MIN DATE,
  RANGE_MAX DATE,
  DOC_NUMBER STRING,
  IDENTIFICACAO STRING,
  FLAG_INVESTIGADO STRING,
  SISTEMA STRING,
  CUS_CUST_ID INT64,
  DATA_ABERTURA DATE,
  NOME_INVESTIGADO STRING,
  CEP STRING,
  TELEFONE_PESSOA STRING,
  VALOR_RENDA STRING,
  KYC_LEVEL STRING,
  DATAHORA_IMPORTACAO DATETIME,
  CONTA_SPB STRING
);

-- STG_QS_TITULAR_CAD_VF
CREATE TABLE IF NOT EXISTS `<ENV>.STG.STG_QS_TITULAR_CAD_VF` (
  CIRCULAR_3454 STRING,
  EXTRATO STRING,
  RANGE_MIN DATE,
  RANGE_MAX DATE,
  DOC_NUMBER STRING,
  IDENTIFICACAO STRING,
  FLAG_INVESTIGADO STRING,
  SISTEMA STRING,
  CUS_CUST_ID INT64,
  CONTA_SPB STRING,
  DATA_ABERTURA DATE,
  NOME_INVESTIGADO STRING,
  CEP STRING,
  TELEFONE_PESSOA STRING,
  VALOR_RENDA STRING,
  MOVIMENTACAO_MIN DATE,
  DATAHORA_IMPORTACAO DATETIME
);

-- STG_QS_WITHDRAWAL_REL_CAD_VF
CREATE TABLE IF NOT EXISTS `<ENV>.STG.STG_QS_WITHDRAWAL_REL_CAD_VF` (
  ID_PAGAMENTO NUMERIC,
  CODIGO_CHAVE_EXTRATO STRING,
  NUMERO_BANCO_REL STRING,
  NUMERO_AGENCIA_REL STRING,
  NUMERO_CONTA_REL STRING,
  TIPO_CONTA_REL STRING,
  TIPO_PESSOA_REL STRING,
  CPF_CNPJ_REL STRING,
  NOME_PESSOA_REL STRING
);

-- TBL_QS_AGENCIAS
CREATE TABLE IF NOT EXISTS `<ENV>.STG.TBL_QS_AGENCIAS` (
  VERTICAL STRING,
  IDENTIFICACAO STRING,
  SISTEMA STRING,
  DATA_IMPORTACAO DATE,
  NUMERO_BANCO STRING,
  NUMERO_AGENCIA STRING,
  NOME_AGENCIA STRING,
  ENDERECO_LOGRADOURO STRING,
  ENDERECO_CIDADE STRING,
  ENDERECO_UF STRING,
  ENDERECO_PAIS STRING,
  ENDERECO_CEP STRING,
  TELEFONE_AGENCIA STRING,
  DATA_ABERTURA_AGENCIA STRING,
  DATA_FECHAMENTO_AGENCIA STRING,
  DATAHORA_IMPORTACAO DATETIME
);

-- TBL_QS_AUX_INVESTIGADO_FINCH (entrada do BLOCO_01)
CREATE TABLE IF NOT EXISTS `<ENV>.STG.TBL_QS_AUX_INVESTIGADO_FINCH` (
  SISTEMA STRING,
  RANGE_MIN STRING,
  RANGE_MAX STRING,
  CPFCNPJ_ORIGINAL STRING,
  CCS_Hashtags STRING,
  PROTOCOLO STRING,
  CASO STRING,
  CPF_CNPJ STRING,
  APOIO_CPF_CNPJ STRING,
  APOIO_RANGE_MIN DATE,
  APOIO_RANGE_MAX DATE
);

-- TBL_QS_CONTAS
CREATE TABLE IF NOT EXISTS `<ENV>.STG.TBL_QS_CONTAS` (
  VERTICAL STRING,
  IDENTIFICACAO STRING,
  SISTEMA STRING,
  DATA_IMPORTACAO DATE,
  NUMERO_BANCO STRING,
  NUMERO_AGENCIA STRING,
  NUMERO_CONTA STRING,
  TIPO_CONTA STRING,
  DATA_ABERTURA_CONTA STRING,
  DATA_ENCERRAMENTO_CONTA STRING,
  MOVIMENTACAO_CONTA STRING,
  DATAHORA_IMPORTACAO DATETIME
);

-- TBL_QS_EXTRATO
CREATE TABLE IF NOT EXISTS `<ENV>.STG.TBL_QS_EXTRATO` (
  VERTICAL STRING,
  IDENTIFICACAO STRING,
  SISTEMA STRING,
  DATA_IMPORTACAO DATE,
  CODIGO_CHAVE_EXTRATO STRING,
  NUMERO_BANCO STRING,
  NUMERO_AGENCIA STRING,
  NUMERO_CONTA STRING,
  TIPO_CONTA STRING,
  DATA_LANCAMENTO STRING,
  NUMERO_DOCUMENTO STRING,
  DESCRICAO_LANCAMENTO STRING,
  TIPO_LANCAMENTO STRING,
  VALOR_LANCAMENTO STRING,
  NATUREZA_LANCAMENTO STRING,
  VALOR_SALDO STRING,
  NATUREZA_SALDO STRING,
  LOCAL_TRANSACAO STRING,
  DATAHORA_IMPORTACAO DATETIME
);

-- TBL_QS_NAO_CORRESPONDENTE
CREATE TABLE IF NOT EXISTS `<ENV>.STG.TBL_QS_NAO_CORRESPONDENTE` (
  VERTICAL STRING,
  IDENTIFICACAO STRING,
  DOC_NUMBER STRING,
  SISTEMA STRING,
  DATA_IMPORTACAO DATE,
  DATAHORA_IMPORTACAO DATETIME
);

-- TBL_QS_ORIGEM_DESTINO
CREATE TABLE IF NOT EXISTS `<ENV>.STG.TBL_QS_ORIGEM_DESTINO` (
  VERTICAL STRING,
  IDENTIFICACAO STRING,
  SISTEMA STRING,
  DATA_IMPORTACAO DATE,
  CODIGO_CHAVE_OD STRING,
  CODIGO_CHAVE_EXTRATO STRING,
  VALOR_TRANSACAO STRING,
  NUMERO_DOCUMENTO_TRANSACAO STRING,
  NUMERO_BANCO_OD STRING,
  NUMERO_AGENCIA_OD STRING,
  NUMERO_CONTA_OD STRING,
  TIPO_CONTA_OD STRING,
  TIPO_PESSOA_OD STRING,
  CPF_CNPJ_OD STRING,
  NOME_PESSOA_OD STRING,
  NOME_DOC_IDENTIFICACAO STRING,
  NUMERO_DOC_IDENTIFICACAO STRING,
  CODIGO_DE_BARRAS STRING,
  NOME_ENDOSSANTE_CHEQUE STRING,
  DOC_ENDOSSANTE_CHEQUE STRING,
  SITUACAO_IDENTIFICACAO STRING,
  OBSERVACAO STRING,
  DATAHORA_IMPORTACAO DATETIME
);

-- TBL_QS_TITULARES
CREATE TABLE IF NOT EXISTS `<ENV>.STG.TBL_QS_TITULARES` (
  VERTICAL STRING,
  IDENTIFICACAO STRING,
  SISTEMA STRING,
  RANGE_MIN DATE,
  RANGE_MAX DATE,
  DATA_IMPORTACAO DATE,
  NUMERO_BANCO STRING,
  NUMERO_AGENCIA STRING,
  NUMERO_CONTA STRING,
  TIPO_CONTA STRING,
  TIPO_TITULAR STRING,
  PESSOA_INVESTIGADA STRING,
  TIPO_PESSOA_TITULAR STRING,
  CPF_CNPJ_TITULAR STRING,
  NOME_TITULAR STRING,
  NOME_DOC_IDENTIFICACAO STRING,
  NUMERO_DOC_IDENTIFICACAO STRING,
  ENDERECO_CEP STRING,
  TELEFONE_PESSOA STRING,
  VALOR_RENDA STRING,
  DATA_ATUALIZACAO_RENDA STRING,
  DATA_INICIO_RELACIONAMENTO_CONTA STRING,
  DATA_FIM_RELACIONAMENTO_CONTA STRING,
  DATAHORA_IMPORTACAO DATETIME
  );

END;

-- ============================================================================
-- Dim_DATE: não constava no export. Se existir na origem, adicione aqui ou
-- crie manualmente. Exemplo mínimo:
-- CREATE TABLE IF NOT EXISTS `<ENV>.STG.Dim_DATE` ( DATA_REF DATE, ... );
-- ============================================================================
