INSERT INTO
    `<ENV>.STG.ZTZ_coleta_historico` (
        DADO_INPUT,
        CUS_CUST_DOC_NUMBER,
        AVAILABLE_AMOUNT,
        ASSET_MGMT_STATUS,
        ASSET_MGMT_PRODUCT_ID,
        TIPO_FONDO_INVERTIDO,
        AVAILABLE_AMOUNT_AJUSTADO
    )
SELECT
    CAST(DADO_INPUT AS STRING),
    CAST(CUS_CUST_DOC_NUMBER AS STRING),
    CAST(AVAILABLE_AMOUNT AS FLOAT64),
    CAST(ASSET_MGMT_STATUS AS STRING),
    CAST(ASSET_MGMT_PRODUCT_ID AS STRING),
    CAST(TIPO_FONDO_INVERTIDO AS STRING),
    CAST(AVAILABLE_AMOUNT_AJUSTADO AS STRING)
FROM
    `<ENV>.STG.ZTZ_coleta`