-- 1
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_PLANILHA_PRESENTA_CAD_VF_TUNING AS
  SELECT * FROM SBOX_LEGALES.STG_QS_PLANILHA_PRESENTA_CAD_VF;
TRUNCATE TABLE SBOX_LEGALES.STG_QS_PLANILHA_PRESENTA_CAD_VF_TUNING;

-- 2
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_INFO_TIT_CAD_VF_TUNING AS
  SELECT * FROM SBOX_LEGALES.STG_QS_INFO_TIT_CAD_VF;
TRUNCATE TABLE SBOX_LEGALES.STG_QS_INFO_TIT_CAD_VF_TUNING;

-- 3
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_INFO_TIT_KYC_CAD_VF_TUNING AS
  SELECT * FROM SBOX_LEGALES.STG_QS_INFO_TIT_KYC_CAD_VF;
TRUNCATE TABLE SBOX_LEGALES.STG_QS_INFO_TIT_KYC_CAD_VF_TUNING;

-- 4
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_CORRESPONDENTE_CAD_VF_TUNING AS
  SELECT * FROM SBOX_LEGALES.STG_QS_CORRESPONDENTE_CAD_VF;
TRUNCATE TABLE SBOX_LEGALES.STG_QS_CORRESPONDENTE_CAD_VF_TUNING;

-- 5
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_NAO_CORRESPONDENTE_CAD_VF_TUNING AS
  SELECT * FROM SBOX_LEGALES.STG_QS_NAO_CORRESPONDENTE_CAD_VF;
TRUNCATE TABLE SBOX_LEGALES.STG_QS_NAO_CORRESPONDENTE_CAD_VF_TUNING;

-- 6
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_SPB_CAD_VF_TUNING AS
  SELECT * FROM SBOX_LEGALES.STG_QS_SPB_CAD_VF;
TRUNCATE TABLE SBOX_LEGALES.STG_QS_SPB_CAD_VF_TUNING;

-- 7
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_MAX_KYC_CAD_VF_TUNING AS
  SELECT * FROM SBOX_LEGALES.STG_QS_MAX_KYC_CAD_VF;
TRUNCATE TABLE SBOX_LEGALES.STG_QS_MAX_KYC_CAD_VF_TUNING;

-- 8
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_QTD_CUST_MAX_KYC_CAD_VF_TUNING AS
  SELECT * FROM SBOX_LEGALES.STG_QS_QTD_CUST_MAX_KYC_CAD_VF;
TRUNCATE TABLE SBOX_LEGALES.STG_QS_QTD_CUST_MAX_KYC_CAD_VF_TUNING;

-- 9
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_MAX_CUST_CAD_VF_TUNING AS
  SELECT * FROM SBOX_LEGALES.STG_QS_MAX_CUST_CAD_VF;
TRUNCATE TABLE SBOX_LEGALES.STG_QS_MAX_CUST_CAD_VF_TUNING;

-- 10
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_NOME_UNI_INV_CAD_VF_TUNING AS
  SELECT * FROM SBOX_LEGALES.STG_QS_NOME_UNI_INV_CAD_VF;
TRUNCATE TABLE SBOX_LEGALES.STG_QS_NOME_UNI_INV_CAD_VF_TUNING;

-- 11
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_TITULAR_CAD_VF_TUNING AS
  SELECT * FROM SBOX_LEGALES.STG_QS_TITULAR_CAD_VF;
TRUNCATE TABLE SBOX_LEGALES.STG_QS_TITULAR_CAD_VF_TUNING;

-- 12
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_AUX_MOVIMENTACAO_CAD_VF_TUNING AS
  SELECT * FROM SBOX_LEGALES.STG_QS_AUX_MOVIMENTACAO_CAD_VF;
TRUNCATE TABLE SBOX_LEGALES.STG_QS_AUX_MOVIMENTACAO_CAD_VF_TUNING;

-- 13
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_AUX_MOVIMENTACAO2_CAD_VF_TUNING AS
  SELECT * FROM SBOX_LEGALES.STG_QS_AUX_MOVIMENTACAO2_CAD_VF;
TRUNCATE TABLE SBOX_LEGALES.STG_QS_AUX_MOVIMENTACAO2_CAD_VF_TUNING;

-- 14
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_AUX_PAYOUT_CAD_VF_TUNING AS
  SELECT * FROM SBOX_LEGALES.STG_QS_AUX_PAYOUT_CAD_VF;
TRUNCATE TABLE SBOX_LEGALES.STG_QS_AUX_PAYOUT_CAD_VF_TUNING;

-- 15
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_AUX_PAYOUT_REL_CAD_VF_TUNING AS
  SELECT * FROM SBOX_LEGALES.STG_QS_AUX_PAYOUT_REL_CAD_VF;
TRUNCATE TABLE SBOX_LEGALES.STG_QS_AUX_PAYOUT_REL_CAD_VF_TUNING;

-- 16
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_AUX_PAYIN_CAD_VF_TUNING AS
  SELECT * FROM SBOX_LEGALES.STG_QS_AUX_PAYIN_CAD_VF;
TRUNCATE TABLE SBOX_LEGALES.STG_QS_AUX_PAYIN_CAD_VF_TUNING;

-- 17
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_AUX_PAYIN_REL_CAD_VF_TUNING AS
  SELECT * FROM SBOX_LEGALES.STG_QS_AUX_PAYIN_REL_CAD_VF;
TRUNCATE TABLE SBOX_LEGALES.STG_QS_AUX_PAYIN_REL_CAD_VF_TUNING;

-- 18
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_AUX_PAYMENTS_COMID_CAD_VF_TUNING AS
  SELECT * FROM SBOX_LEGALES.STG_QS_AUX_PAYMENTS_COMID_CAD_VF;
TRUNCATE TABLE SBOX_LEGALES.STG_QS_AUX_PAYMENTS_COMID_CAD_VF_TUNING;

-- 19
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_AUX_PAYMENTS_SEMID_CAD_VF_TUNING AS
  SELECT * FROM SBOX_LEGALES.STG_QS_AUX_PAYMENTS_SEMID_CAD_VF;
TRUNCATE TABLE SBOX_LEGALES.STG_QS_AUX_PAYMENTS_SEMID_CAD_VF_TUNING;

-- 20
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_PAGAMENTO_CAD_VF_TUNING AS
  SELECT * FROM SBOX_LEGALES.STG_QS_PAGAMENTO_CAD_VF;
TRUNCATE TABLE SBOX_LEGALES.STG_QS_PAGAMENTO_CAD_VF_TUNING;

-- 21
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_PAGAMENTO_REL_CAD_VF_TUNING AS
  SELECT * FROM SBOX_LEGALES.STG_QS_PAGAMENTO_REL_CAD_VF;
TRUNCATE TABLE SBOX_LEGALES.STG_QS_PAGAMENTO_REL_CAD_VF_TUNING;

-- 22
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_AUX_WITHDRAWAL_CAD_VF_TUNING AS
  SELECT * FROM SBOX_LEGALES.STG_QS_AUX_WITHDRAWAL_CAD_VF;
TRUNCATE TABLE SBOX_LEGALES.STG_QS_AUX_WITHDRAWAL_CAD_VF_TUNING;

-- 23
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_WITHDRAWAL_REL_CAD_VF_TUNING AS
  SELECT * FROM SBOX_LEGALES.STG_QS_WITHDRAWAL_REL_CAD_VF;
TRUNCATE TABLE SBOX_LEGALES.STG_QS_WITHDRAWAL_REL_CAD_VF_TUNING;

-- 24
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_RELACIONADO_CAD_VF_TUNING AS
  SELECT * FROM SBOX_LEGALES.STG_QS_RELACIONADO_CAD_VF;
TRUNCATE TABLE SBOX_LEGALES.STG_QS_RELACIONADO_CAD_VF_TUNING;

-- 25
CREATE OR REPLACE TABLE SBOX_LEGALES.STG_QS_FLAG_MOV_CAD_VF_TUNING AS
  SELECT * FROM SBOX_LEGALES.STG_QS_FLAG_MOV_CAD_VF;
TRUNCATE TABLE SBOX_LEGALES.STG_QS_FLAG_MOV_CAD_VF_TUNING;


-- 27
CREATE OR REPLACE TABLE SBOX_LEGALES.TBL_QS_NAO_CORRESPONDENTE_TUNING AS
  SELECT * FROM SBOX_LEGALES.TBL_QS_NAO_CORRESPONDENTE;
TRUNCATE TABLE SBOX_LEGALES.TBL_QS_NAO_CORRESPONDENTE_TUNING;

-- 28
CREATE OR REPLACE TABLE SBOX_LEGALES.TBL_QS_AGENCIAS_TUNING AS
  SELECT * FROM SBOX_LEGALES.TBL_QS_AGENCIAS;
TRUNCATE TABLE SBOX_LEGALES.TBL_QS_AGENCIAS_TUNING;

-- 29
CREATE OR REPLACE TABLE SBOX_LEGALES.TBL_QS_CONTAS_TUNING AS
  SELECT * FROM SBOX_LEGALES.TBL_QS_CONTAS;
TRUNCATE TABLE SBOX_LEGALES.TBL_QS_CONTAS_TUNING;

-- 31
CREATE OR REPLACE TABLE SBOX_LEGALES.TBL_QS_EXTRATO_TUNING AS
  SELECT * FROM SBOX_LEGALES.TBL_QS_EXTRATO;
TRUNCATE TABLE SBOX_LEGALES.TBL_QS_EXTRATO_TUNING;

-- 32
CREATE OR REPLACE TABLE SBOX_LEGALES.TBL_QS_TITULARES_TUNING AS
  SELECT * FROM SBOX_LEGALES.TBL_QS_TITULARES;
TRUNCATE TABLE SBOX_LEGALES.TBL_QS_TITULARES_TUNING;

-- 33
CREATE OR REPLACE TABLE SBOX_LEGALES.TBL_QS_ORIGEM_DESTINO_TUNING AS
  SELECT * FROM SBOX_LEGALES.TBL_QS_ORIGEM_DESTINO;
TRUNCATE TABLE SBOX_LEGALES.TBL_QS_ORIGEM_DESTINO_TUNING;

-- 34
CREATE OR REPLACE TABLE SBOX_LEGALES.CAD_TBL_QS_EXTRATO_NAO_CORRESPONDENTE_TUNING AS
  SELECT * FROM SBOX_LEGALES.CAD_TBL_QS_EXTRATO_NAO_CORRESPONDENTE;
TRUNCATE TABLE SBOX_LEGALES.CAD_TBL_QS_EXTRATO_NAO_CORRESPONDENTE_TUNING;

-- 35
CREATE OR REPLACE TABLE SBOX_LEGALES.CAD_TBL_QS_EXTRATO_MOVIMENTACAO_TUNING AS
  SELECT * FROM SBOX_LEGALES.CAD_TBL_QS_EXTRATO_MOVIMENTACAO;
TRUNCATE TABLE SBOX_LEGALES.CAD_TBL_QS_EXTRATO_MOVIMENTACAO_TUNING;
