-- UNIR OS RELACIONADOS
CREATE
OR REPLACE TABLE SBOX_LEGALES.STG_QS_RELACIONADO_CAD_VF_TUNING AS (
    SELECT
        DISTINCT ID_PAGAMENTO,
        CODIGO_CHAVE_EXTRATO,
        CASE
            WHEN UPPER(NOME_PESSOA_REL) LIKE '%SPLITTER%'
            OR UPPER(NOME_PESSOA_REL) LIKE '%PAYINS%' THEN NULL
            ELSE NUMERO_BANCO_REL
        END AS NUMERO_BANCO_REL,
        CASE
            WHEN UPPER(NOME_PESSOA_REL) LIKE '%SPLITTER%'
            OR UPPER(NOME_PESSOA_REL) LIKE '%PAYINS%' THEN NULL
            ELSE NUMERO_AGENCIA_REL
        END AS NUMERO_AGENCIA_REL,
        CASE
            WHEN UPPER(NOME_PESSOA_REL) LIKE '%SPLITTER%'
            OR UPPER(NOME_PESSOA_REL) LIKE '%PAYINS%' THEN NULL
            ELSE NUMERO_CONTA_REL
        END AS NUMERO_CONTA_REL,
        TIPO_CONTA_REL,
        CASE
            WHEN UPPER(NOME_PESSOA_REL) LIKE '%SPLITTER%'
            OR UPPER(NOME_PESSOA_REL) LIKE '%PAYINS%' THEN NULL
            ELSE TIPO_PESSOA_REL
        END AS TIPO_PESSOA_REL,
        CASE
            WHEN UPPER(NOME_PESSOA_REL) LIKE '%SPLITTER%'
            OR UPPER(NOME_PESSOA_REL) LIKE '%PAYINS%' THEN NULL
            ELSE CPF_CNPJ_REL
        END AS CPF_CNPJ_REL,
        CASE
            WHEN UPPER(NOME_PESSOA_REL) LIKE '%SPLITTER%'
            OR UPPER(NOME_PESSOA_REL) LIKE '%PAYINS%' THEN NULL
            ELSE NOME_PESSOA_REL
        END AS NOME_PESSOA_REL
    FROM
        SBOX_LEGALES.STG_QS_AUX_PAYOUT_REL_CAD_VF_TUNING
    UNION
    DISTINCT
    SELECT
        DISTINCT ID_PAGAMENTO,
        CODIGO_CHAVE_EXTRATO,
        CASE
            WHEN UPPER(NOME_REL) LIKE '%SPLITTER%'
            OR UPPER(NOME_REL) LIKE '%PAYINS%' THEN NULL
            ELSE '323'
        END AS NUMERO_BANCO_REL,
        CASE
            WHEN UPPER(NOME_REL) LIKE '%SPLITTER%'
            OR UPPER(NOME_REL) LIKE '%PAYINS%' THEN NULL
            ELSE '0001'
        END AS NUMERO_AGENCIA_REL,
        CASE
            WHEN UPPER(NOME_REL) LIKE '%SPLITTER%'
            OR UPPER(NOME_REL) LIKE '%PAYINS%' THEN NULL
            ELSE NUMERO_CONTA_REL
        END AS NUMERO_CONTA_REL,
        '4' AS TIPO_CONTA_REL,
        CASE
            WHEN UPPER(NOME_REL) LIKE '%SPLITTER%'
            OR UPPER(NOME_REL) LIKE '%PAYINS%' THEN NULL
            ELSE TIPO_PESSOA_REL
        END AS TIPO_PESSOA_REL,
        CASE
            WHEN UPPER(NOME_REL) LIKE '%SPLITTER%'
            OR UPPER(NOME_REL) LIKE '%PAYINS%' THEN NULL
            ELSE CPF_CNPJ_REL
        END AS CPF_CNPJ_REL,
        CASE
            WHEN UPPER(NOME_REL) LIKE '%SPLITTER%'
            OR UPPER(NOME_REL) LIKE '%PAYINS%' THEN NULL
            ELSE NOME_REL
        END AS NOME_REL
    FROM
        SBOX_LEGALES.STG_QS_PAGAMENTO_REL_CAD_VF_TUNING
    UNION
    DISTINCT
    SELECT
        DISTINCT ID_PAGAMENTO,
        CODIGO_CHAVE_EXTRATO,
        CASE
            WHEN UPPER(NOME_PESSOA_REL) LIKE '%SPLITTER%'
            OR UPPER(NOME_PESSOA_REL) LIKE '%PAYINS%' THEN NULL
            ELSE NUMERO_BANCO_REL
        END AS NUMERO_BANCO_REL,
        CASE
            WHEN UPPER(NOME_PESSOA_REL) LIKE '%SPLITTER%'
            OR UPPER(NOME_PESSOA_REL) LIKE '%PAYINS%' THEN NULL
            ELSE NUMERO_AGENCIA_REL
        END AS NUMERO_AGENCIA_REL,
        CASE
            WHEN UPPER(NOME_PESSOA_REL) LIKE '%SPLITTER%'
            OR UPPER(NOME_PESSOA_REL) LIKE '%PAYINS%' THEN NULL
            ELSE NUMERO_CONTA_REL
        END AS NUMERO_CONTA_REL,
        TIPO_CONTA_REL,
        CASE
            WHEN UPPER(NOME_PESSOA_REL) LIKE '%SPLITTER%'
            OR UPPER(NOME_PESSOA_REL) LIKE '%PAYINS%' THEN NULL
            ELSE TIPO_PESSOA_REL
        END AS TIPO_PESSOA_REL,
        CASE
            WHEN UPPER(NOME_PESSOA_REL) LIKE '%SPLITTER%'
            OR UPPER(NOME_PESSOA_REL) LIKE '%PAYINS%' THEN NULL
            ELSE CPF_CNPJ_REL
        END AS CPF_CNPJ_REL,
        CASE
            WHEN UPPER(NOME_PESSOA_REL) LIKE '%SPLITTER%'
            OR UPPER(NOME_PESSOA_REL) LIKE '%PAYINS%' THEN NULL
            ELSE NOME_PESSOA_REL
        END AS NOME_PESSOA_REL
    FROM
        SBOX_LEGALES.STG_QS_WITHDRAWAL_REL_CAD_VF_TUNING
    UNION
    DISTINCT
    SELECT
        DISTINCT ID_PAGAMENTO,
        CODIGO_CHAVE_EXTRATO,
        CASE
            WHEN UPPER(NOME_PESSOA_REL) LIKE '%SPLITTER%'
            OR UPPER(NOME_PESSOA_REL) LIKE '%PAYINS%' THEN NULL
            ELSE NUMERO_BANCO_REL
        END AS NUMERO_BANCO_REL,
        CASE
            WHEN UPPER(NOME_PESSOA_REL) LIKE '%SPLITTER%'
            OR UPPER(NOME_PESSOA_REL) LIKE '%PAYINS%' THEN NULL
            ELSE NUMERO_AGENCIA_REL
        END AS NUMERO_AGENCIA_REL,
        CASE
            WHEN UPPER(NOME_PESSOA_REL) LIKE '%SPLITTER%'
            OR UPPER(NOME_PESSOA_REL) LIKE '%PAYINS%' THEN NULL
            ELSE NUMERO_CONTA_REL
        END AS NUMERO_CONTA_REL,
        TIPO_CONTA_REL,
        CASE
            WHEN UPPER(NOME_PESSOA_REL) LIKE '%SPLITTER%'
            OR UPPER(NOME_PESSOA_REL) LIKE '%PAYINS%' THEN NULL
            ELSE TIPO_PESSOA_REL
        END AS TIPO_PESSOA_REL,
        CASE
            WHEN UPPER(NOME_PESSOA_REL) LIKE '%SPLITTER%'
            OR UPPER(NOME_PESSOA_REL) LIKE '%PAYINS%' THEN NULL
            ELSE CPF_CNPJ_REL
        END AS CPF_CNPJ_REL,
        CASE
            WHEN UPPER(NOME_PESSOA_REL) LIKE '%SPLITTER%'
            OR UPPER(NOME_PESSOA_REL) LIKE '%PAYINS%' THEN NULL
            ELSE NOME_PESSOA_REL
        END AS NOME_PESSOA_REL
    FROM
        SBOX_LEGALES.STG_QS_AUX_PAYIN_REL_CAD_VF_TUNING
);

-- CRIAR TABELA DE FLAG_MOV
CREATE
OR REPLACE TABLE SBOX_LEGALES.STG_QS_FLAG_MOV_CAD_VF_TUNING AS (
    SELECT
        TIT.CUS_CUST_ID,
        CASE
            WHEN MOV.CUS_CUST_ID IS NULL THEN '2'
            ELSE '1'
        END AS MOVIMENTACAO_CONTA
    FROM
        SBOX_LEGALES.STG_QS_TITULAR_CAD_VF_TUNING TIT
        LEFT JOIN SBOX_LEGALES.STG_QS_AUX_MOVIMENTACAO2_CAD_VF_TUNING MOV
            ON TIT.CUS_CUST_ID = MOV.CUS_CUST_ID
);
