-- NÃO CORRESPONDENTE
MERGE SBOX_LEGALES.TBL_QS_NAO_CORRESPONDENTE_TUNING A
USING SBOX_LEGALES.STG_QS_NAO_CORRESPONDENTE_CAD_VF_TUNING B
  ON A.DATAHORA_IMPORTACAO = B.DATAHORA_IMPORTACAO
WHEN MATCHED THEN DELETE;

-- INSERIR PARA CARTA
INSERT INTO SBOX_LEGALES.TBL_QS_NAO_CORRESPONDENTE_TUNING
SELECT
    '<area>' AS VERTICAL,
    IDENTIFICACAO,
    DOC_NUMBER,
    SISTEMA,
    CAST(DATAHORA_IMPORTACAO AS DATE) AS DATA_IMPORTACAO,
    DATAHORA_IMPORTACAO AS DATAHORA_IMPORTACAO
FROM SBOX_LEGALES.STG_QS_NAO_CORRESPONDENTE_CAD_VF_TUNING
WHERE CIRCULAR_3454 = 'Sim';

-- AGÊNCIAS
MERGE SBOX_LEGALES.TBL_QS_AGENCIAS_TUNING A
USING SBOX_LEGALES.STG_QS_CORRESPONDENTE_CAD_VF_TUNING B
  ON A.DATAHORA_IMPORTACAO = B.DATAHORA_IMPORTACAO
WHEN MATCHED THEN DELETE;

INSERT INTO SBOX_LEGALES.TBL_QS_AGENCIAS_TUNING
SELECT
    DISTINCT '<area>' AS VERTICAL,
    IDENTIFICACAO,
    SISTEMA,
    CAST(DATAHORA_IMPORTACAO AS DATE) AS DATA_IMPORTACAO,
    CAST('323' AS STRING) AS NUMERO_BANCO,
    CAST('0001' AS STRING) AS NUMERO_AGENCIA,
    CAST('Mercado Pago' AS STRING) AS NOME_AGENCIA,
    CAST('AVENIDA DAS NACOES UNIDAS, 3003' AS STRING) AS ENDERECO_LOGRADOURO,
    CAST('OSASCO' AS STRING) AS ENDERECO_CIDADE,
    CAST('SP' AS STRING) AS ENDERECO_UF,
    CAST('BRASIL' AS STRING) AS ENDERECO_PAIS,
    CAST('06233903' AS STRING) AS ENDERECO_CEP,
    CAST('1125434155' AS STRING) AS TELEFONE_AGENCIA,
    CAST('22122008' AS STRING) AS DATA_ABERTURA_AGENCIA,
    CAST('' AS STRING) AS DATA_FECHAMENTO_AGENCIA,
    DATAHORA_IMPORTACAO
FROM SBOX_LEGALES.STG_QS_CORRESPONDENTE_CAD_VF_TUNING
WHERE CIRCULAR_3454 = 'Sim';

-- CONTAS
MERGE SBOX_LEGALES.TBL_QS_CONTAS_TUNING A
USING SBOX_LEGALES.STG_QS_TITULAR_CAD_VF_TUNING B
  ON A.DATAHORA_IMPORTACAO = B.DATAHORA_IMPORTACAO
WHEN MATCHED THEN DELETE;

INSERT INTO SBOX_LEGALES.TBL_QS_CONTAS_TUNING
SELECT
    DISTINCT '<area>' AS VERTICAL,
    TIT.IDENTIFICACAO,
    TIT.SISTEMA,
    CAST(TIT.DATAHORA_IMPORTACAO AS DATE) AS DATA_IMPORTACAO,
    CAST('323' AS STRING) AS NUMERO_BANCO,
    CAST('0001' AS STRING) AS NUMERO_AGENCIA,
    COALESCE(TIT.CONTA_SPB, CAST(TIT.CUS_CUST_ID AS STRING)) AS NUMERO_CONTA,
    CAST('4' AS STRING) AS TIPO_CONTA,
    CAST(DT.ID_DATE_BR AS STRING) AS DATA_ABERTURA_CONTA,
    CAST('' AS STRING) AS DATA_ENCERRAMENTO_CONTA,
    FL.MOVIMENTACAO_CONTA,
    TIT.DATAHORA_IMPORTACAO
FROM SBOX_LEGALES.STG_QS_TITULAR_CAD_VF_TUNING TIT
LEFT JOIN SBOX_LEGALES.STG_QS_FLAG_MOV_CAD_VF_TUNING FL
  ON CAST(TIT.CUS_CUST_ID AS STRING) = CAST(FL.CUS_CUST_ID AS STRING)
LEFT JOIN SBOX_LEGALES.DIM_DATE DT
  ON DT.DS_DATE = TIT.DATA_ABERTURA
WHERE TIT.CIRCULAR_3454 = 'Sim';

-- EXTRATO
MERGE SBOX_LEGALES.TBL_QS_EXTRATO_TUNING A
USING SBOX_LEGALES.STG_QS_TITULAR_CAD_VF_TUNING B
  ON A.DATAHORA_IMPORTACAO = B.DATAHORA_IMPORTACAO
WHEN MATCHED THEN DELETE;

INSERT INTO SBOX_LEGALES.TBL_QS_EXTRATO_TUNING
SELECT
    DISTINCT '<area>' AS VERTICAL,
    TIT.IDENTIFICACAO,
    TIT.SISTEMA,
    CAST(TIT.DATAHORA_IMPORTACAO AS DATE) AS DATA_IMPORTACAO,
    COALESCE(MOV.CODIGO_CHAVE_EXTRATO, '') AS CODIGO_CHAVE_EXTRATO,
    CASE
        WHEN MOV.CUS_CUST_ID IS NOT NULL THEN CAST('323' AS STRING)
        ELSE ''
    END AS NUMERO_BANCO,
    CASE
        WHEN MOV.CUS_CUST_ID IS NOT NULL THEN CAST('0001' AS STRING)
        ELSE ''
    END AS NUMERO_AGENCIA,
    CASE
        WHEN MOV.CUS_CUST_ID IS NOT NULL THEN
            COALESCE(COALESCE(TIT.CONTA_SPB, CAST(TIT.CUS_CUST_ID AS STRING)), '')
        ELSE ''
    END AS NUMERO_CONTA,
    CASE
        WHEN MOV.CUS_CUST_ID IS NOT NULL THEN CAST('4' AS STRING)
        ELSE ''
    END AS TIPO_CONTA,
    COALESCE(CAST(MOV.DATA_LANCAMENTO AS STRING), '') AS DATA_LANCAMENTO,
    CASE
        WHEN MOV.CUS_CUST_ID IS NOT NULL
         AND REL.NUMERO_AGENCIA_REL IS NULL
         AND TIPO_LANCAMENTO IN ('120','213','217','117','218')
        THEN 'Pagamento Fornecedores'
        ELSE COALESCE(SUBSTR(DESCRICAO_LANCAMENTO,1,50),'')
    END AS DESCRICAO_LANCAMENTO,
    CASE
        WHEN MOV.CUS_CUST_ID IS NOT NULL
         AND REL.NUMERO_AGENCIA_REL IS NULL
         AND TIPO_LANCAMENTO IN ('120','213','217','117','218')
         AND NATUREZA_LANCAMENTO = 'D' THEN '112'
        WHEN MOV.CUS_CUST_ID IS NOT NULL
         AND REL.NUMERO_AGENCIA_REL IS NULL
         AND TIPO_LANCAMENTO IN ('120','213','217','117','218')
         AND NATUREZA_LANCAMENTO = 'C' THEN '217'
        ELSE COALESCE(TIPO_LANCAMENTO,'')
    END AS TIPO_LANCAMENTO,
    COALESCE(VALOR_LANCAMENTO,'') AS VALOR_LANCAMENTO,
    COALESCE(NATUREZA_LANCAMENTO,'') AS NATUREZA_LANCAMENTO,
    CASE
        WHEN MOV.CUS_CUST_ID IS NOT NULL THEN CAST('0' AS STRING)
        ELSE ''
    END AS VALOR_SALDO,
    COALESCE(NATUREZA_SALDO,'') AS NATUREZA_SALDO,
    CASE
        WHEN MOV.CUS_CUST_ID IS NOT NULL THEN CAST('INTERNET' AS STRING)
        ELSE ''
    END AS LOCAL_TRANSACAO,
    TIT.DATAHORA_IMPORTACAO
FROM SBOX_LEGALES.STG_QS_TITULAR_CAD_VF_TUNING TIT
LEFT JOIN SBOX_LEGALES.STG_QS_AUX_MOVIMENTACAO2_CAD_VF_TUNING MOV
  ON CAST(TIT.CUS_CUST_ID AS STRING) = CAST(MOV.CUS_CUST_ID AS STRING)
LEFT JOIN SBOX_LEGALES.STG_QS_RELACIONADO_CAD_VF_TUNING REL
  ON MOV.ID_PAGAMENTO = REL.ID_PAGAMENTO
 AND CAST(MOV.CODIGO_CHAVE_EXTRATO AS STRING) = REL.CODIGO_CHAVE_EXTRATO
WHERE TIT.CIRCULAR_3454 = 'Sim';

-- INSERIR INFORMAÇÃO DOS TITULARES INVESTIGADOS NO MP
MERGE SBOX_LEGALES.TBL_QS_TITULARES_TUNING A
USING SBOX_LEGALES.STG_QS_TITULAR_CAD_VF_TUNING B
  ON A.DATAHORA_IMPORTACAO = B.DATAHORA_IMPORTACAO
WHEN MATCHED THEN DELETE;

INSERT INTO SBOX_LEGALES.TBL_QS_TITULARES_TUNING
SELECT
    DISTINCT '<area>' AS VERTICAL,
    TIT.IDENTIFICACAO,
    TIT.SISTEMA,
    TIT.RANGE_MIN,
    TIT.RANGE_MAX,
    CAST(TIT.DATAHORA_IMPORTACAO AS DATE) AS DATA_IMPORTACAO,
    CAST('323' AS STRING) AS NUMERO_BANCO,
    CAST('0001' AS STRING) AS NUMERO_AGENCIA,
    COALESCE(TIT.CONTA_SPB, CAST(TIT.CUS_CUST_ID AS STRING)) AS NUMERO_CONTA,
    CAST('4' AS STRING) AS TIPO_CONTA,
    CAST('T' AS STRING) AS TIPO_TITULAR,
    CAST('1' AS STRING) AS PESSOA_INVESTIGADA,
    CASE
        WHEN LENGTH(TIT.DOC_NUMBER)=11 THEN '1'
        WHEN LENGTH(TIT.DOC_NUMBER)=14 THEN '2'
        ELSE ''
    END AS TIPO_PESSOA_TITULAR,
    TIT.DOC_NUMBER AS CPF_CNPJ_TITULAR,
    SUBSTR(TIT.NOME_INVESTIGADO,1,79) AS NOME_TITULAR,
    CASE
        WHEN LENGTH(TIT.DOC_NUMBER)=11 THEN 'CPF'
        WHEN LENGTH(TIT.DOC_NUMBER)=14 THEN 'CNPJ'
        ELSE ''
    END AS NOME_DOC_IDENTIFICACAO,
    TIT.DOC_NUMBER AS NUMERO_DOC_IDENTIFICACAO,
    TIT.CEP AS ENDERECO_CEP,
    COALESCE(TIT.TELEFONE_PESSOA,'0') AS TELEFONE_PESSOA,
    CAST(TIT.VALOR_RENDA AS STRING) AS VALOR_RENDA,
    CAST('' AS STRING) AS DATA_ATUALIZACAO_RENDA,
    CAST(DT.ID_DATE_BR AS STRING) AS DATA_INICIO_RELACIONAMENTO_CONTA,
    CAST('' AS STRING) AS DATA_FIM_RELACIONAMENTO_CONTA,
    TIT.DATAHORA_IMPORTACAO
FROM SBOX_LEGALES.STG_QS_TITULAR_CAD_VF_TUNING TIT
LEFT JOIN SBOX_LEGALES.DIM_DATE DT
  ON DT.DS_DATE = TIT.DATA_ABERTURA
WHERE TIT.CIRCULAR_3454 = 'Sim';

-- ORIGEM E DESTINO
MERGE SBOX_LEGALES.TBL_QS_ORIGEM_DESTINO_TUNING A
USING SBOX_LEGALES.STG_QS_TITULAR_CAD_VF_TUNING B
  ON A.DATAHORA_IMPORTACAO = B.DATAHORA_IMPORTACAO
WHEN MATCHED THEN DELETE;

INSERT INTO SBOX_LEGALES.TBL_QS_ORIGEM_DESTINO_TUNING
SELECT
    DISTINCT '<area>' AS VERTICAL,
    TIT.IDENTIFICACAO,
    TIT.SISTEMA,
    CAST(TIT.DATAHORA_IMPORTACAO AS DATE) AS DATA_IMPORTACAO,
    CASE
        WHEN MOV.CUS_CUST_ID IS NULL THEN ''
        ELSE CAST(SUM(1) OVER(ROWS UNBOUNDED PRECEDING) AS STRING)
    END AS CODIGO_CHAVE_OD,
    COALESCE(MOV.CODIGO_CHAVE_EXTRATO,'') AS CODIGO_CHAVE_EXTRATO,
    COALESCE(MOV.VALOR_LANCAMENTO,'') AS VALOR_TRANSACAO,
    COALESCE(CAST(MOV.ID_PAGAMENTO AS STRING),'') AS NUMERO_DOCUMENTO_TRANSACAO,
    COALESCE(REL.NUMERO_BANCO_REL,'') AS NUMERO_BANCO_OD,
    CASE
        WHEN MOV.CUS_CUST_ID IS NULL THEN ''
        WHEN MOV.CUS_CUST_ID IS NOT NULL
         AND (REL.NUMERO_BANCO_REL IS NULL OR REL.NUMERO_BANCO_REL='')
        THEN '9999'
        ELSE SUBSTR(REL.NUMERO_AGENCIA_REL,1,4)
    END AS NUMERO_AGENCIA_OD,
    CASE
        WHEN MOV.CUS_CUST_ID IS NULL THEN ''
        WHEN MOV.CUS_CUST_ID IS NOT NULL
         AND (REL.NUMERO_BANCO_REL IS NULL OR REL.NUMERO_BANCO_REL='')
        THEN '99999999999999999999'
        ELSE SUBSTR(REL.NUMERO_CONTA_REL,1,20)
    END AS NUMERO_CONTA_OD,
    COALESCE(REL.TIPO_CONTA_REL,'') AS TIPO_CONTA_OD,
    COALESCE(REL.TIPO_PESSOA_REL,'') AS TIPO_PESSOA_OD,
    COALESCE(REL.CPF_CNPJ_REL,'') AS CPF_CNPJ_OD,
    COALESCE(SUBSTR(TRIM(REL.NOME_PESSOA_REL),1,79),'') AS NOME_PESSOA_OD,
    CASE
        WHEN MOV.CUS_CUST_ID IS NULL THEN ''
        WHEN REL.TIPO_PESSOA_REL='1' THEN 'CPF'
        WHEN REL.TIPO_PESSOA_REL='2' THEN 'CNPJ'
        ELSE ''
    END AS NOME_DOC_IDENTIFICACAO,
    COALESCE(REL.CPF_CNPJ_REL,'') AS NUMERO_DOC_IDENTIFICACAO,
    CAST('' AS STRING) AS CODIGO_DE_BARRAS,
    CAST('' AS STRING) AS NOME_ENDOSSANTE_CHEQUE,
    CAST('' AS STRING) AS DOC_ENDOSSANTE_CHEQUE,
    CASE
        WHEN MOV.CODIGO_CHAVE_EXTRATO IS NULL THEN ''
        ELSE '0'
    END AS SITUACAO_IDENTIFICACAO,
    CASE
        WHEN MOV.CODIGO_CHAVE_EXTRATO IS NULL THEN ''
        WHEN MOV.CODIGO_CHAVE_EXTRATO IS NOT NULL
         AND (REL.NUMERO_BANCO_REL IS NULL OR REL.NUMERO_BANCO_REL='')
        THEN 'NAO-CORRENTISTA'
        ELSE 'CORRENTISTA'
    END AS OBSERVACAO,
    TIT.DATAHORA_IMPORTACAO
FROM SBOX_LEGALES.STG_QS_TITULAR_CAD_VF_TUNING TIT
LEFT JOIN SBOX_LEGALES.STG_QS_AUX_MOVIMENTACAO2_CAD_VF_TUNING MOV
  ON CAST(TIT.CUS_CUST_ID AS STRING)=CAST(MOV.CUS_CUST_ID AS STRING)
LEFT JOIN SBOX_LEGALES.STG_QS_RELACIONADO_CAD_VF_TUNING REL
  ON MOV.ID_PAGAMENTO=REL.ID_PAGAMENTO
 AND CAST(MOV.CODIGO_CHAVE_EXTRATO AS STRING)=REL.CODIGO_CHAVE_EXTRATO
WHERE TIT.CIRCULAR_3454 = 'Sim';
