-- NÃO CORRESPONDENTE
MERGE SBOX_LEGALES.CAD_TBL_QS_EXTRATO_NAO_CORRESPONDENTE_TUNING A
USING SBOX_LEGALES.STG_QS_NAO_CORRESPONDENTE_CAD_VF_TUNING B
  ON A.DATAHORA_IMPORTACAO = B.DATAHORA_IMPORTACAO
WHEN MATCHED THEN DELETE;

INSERT INTO SBOX_LEGALES.CAD_TBL_QS_EXTRATO_NAO_CORRESPONDENTE_TUNING
SELECT
    '<area>' AS VERTICAL,
    IDENTIFICACAO,
    DOC_NUMBER,
    SISTEMA,
    CAST(DATAHORA_IMPORTACAO AS DATE) AS DATA_IMPORTACAO,
    DATAHORA_IMPORTACAO AS DATAHORA_IMPORTACAO
FROM
    SBOX_LEGALES.STG_QS_NAO_CORRESPONDENTE_CAD_VF_TUNING
WHERE
    EXTRATO = 'Sim';

-- EXTRAÇÃO DE MOVIMENTAÇÃO
MERGE SBOX_LEGALES.CAD_TBL_QS_EXTRATO_MOVIMENTACAO_TUNING A
USING SBOX_LEGALES.STG_QS_TITULAR_CAD_VF_TUNING B
  ON A.DATAHORA_IMPORTACAO = B.DATAHORA_IMPORTACAO
WHEN MATCHED THEN DELETE;

INSERT INTO SBOX_LEGALES.CAD_TBL_QS_EXTRATO_MOVIMENTACAO_TUNING
SELECT
    DISTINCT '<area>' AS VERTICAL,
    TIT.IDENTIFICACAO,
    CASE
        WHEN MOV.CUS_CUST_ID IS NOT NULL THEN 'EXTRATO'
        ELSE NULL
    END AS TIPO_MOVIMENTO,
    TIT.DOC_NUMBER AS DOC_INVESTIGADO,
    COALESCE(
        CAST(TIT.CONTA_SPB AS STRING),
        CAST(TIT.CUS_CUST_ID AS STRING)
    ) AS ID_INVESTIGADO,
    MOV.DATA_LANCAMENTO,
    CAST(MOV.ID_PAGAMENTO AS STRING) AS ID_PAGAMENTO,
    MOV.MOV_TYPE_ID,
    MOV.MOV_DETAIL,
    CASE
        WHEN MOV.CUS_CUST_ID IS NOT NULL THEN 'available'
        ELSE NULL
    END AS MOV_STATUS_ID,
    CASE
        WHEN NATUREZA_LANCAMENTO = 'D' THEN (
            CASE
                WHEN LENGTH(VALOR_LANCAMENTO) = 1 THEN CONCAT('-0,0', VALOR_LANCAMENTO)
                WHEN LENGTH(VALOR_LANCAMENTO) = 2 THEN CONCAT('-0,', VALOR_LANCAMENTO)
                ELSE CONCAT(
                    '-',
                    LEFT(VALOR_LANCAMENTO, LENGTH(VALOR_LANCAMENTO) - 2),
                    ',',
                    RIGHT(VALOR_LANCAMENTO, 2)
                )
            END
        )
        WHEN NATUREZA_LANCAMENTO = 'C' THEN (
            CASE
                WHEN LENGTH(VALOR_LANCAMENTO) = 1 THEN CONCAT('0,0', VALOR_LANCAMENTO)
                WHEN LENGTH(VALOR_LANCAMENTO) = 2 THEN CONCAT('0,', VALOR_LANCAMENTO)
                ELSE CONCAT(
                    LEFT(VALOR_LANCAMENTO, LENGTH(VALOR_LANCAMENTO) - 2),
                    ',',
                    RIGHT(VALOR_LANCAMENTO, 2)
                )
            END
        )
    END AS VALOR_LANCAMENTO,
    '0' AS MOV_BALANCED_AMOUNT,
    DATAHORA_IMPORTACAO AS DATAHORA_IMPORTACAO
FROM
    SBOX_LEGALES.STG_QS_TITULAR_CAD_VF_TUNING TIT
    LEFT JOIN SBOX_LEGALES.STG_QS_AUX_MOVIMENTACAO2_CAD_VF_TUNING MOV
      ON CAST(TIT.CUS_CUST_ID AS STRING) = CAST(MOV.CUS_CUST_ID AS STRING)
WHERE
    TIT.EXTRATO = 'Sim';
