TRUNCATE TABLE `<ENV>.TBL.LK_PBD_LA_CUST_IDS_LEGALES`;

INSERT INTO `<ENV>.TBL.LK_PBD_LA_CUST_IDS_LEGALES` (
Cust_ID_Autor,
AUD_INS_DTTM,
AUD_UPD_DTTM
)
SELECT
CAST(Cust_ID_Autor AS STRING),
CURRENT_DATETIME(),
CURRENT_DATETIME()
FROM
`<ENV>.STG.Tab_ids_processos_ativos`;
