TRUNCATE TABLE `<ENV>.TBL.LK_PAGAMENTOS_EM_GARANTIA`;

INSERT INTO `<ENV>.TBL.LK_PAGAMENTOS_EM_GARANTIA` (
    EMPRESA_PERTINENTE,
    TIPO_DE_TRANSFERENCIA,
    NRO_LEGALES,
    IMPORTE,
    PRAZO_FATAL,
    NUMERO_DA_CONTA,
    BENEFICIARIO_NOME,
    ESTADO,
    BANCO,
    AGENCIA,
    TIPO_DE_CONTA,
    CPF_CNPJ,
    FECHA_ESTADO,
    PROVEDOR,
    FACTURA,
    ACORDO,
    TIPO_DE_PROCEDIMENTO,
    CONTA_CONTABIL,
    CENTRO_DE_CUSTO,
    FECHA,
    CODIGO_DE_BARRAS,
    PARTE_CONTRARIA_NOME,
    ADVOGADO_RESPONSAVEL,
    PROCESSO_ID,
    SUB_TIPO,
    ESCRITORIO_EXTERNO,
    PROCESSO_CLASSIFICACAO,
    STATUS,
    AREA_DO_DIREITO,
    SUB_AREA_DO_DIREITO,
    VALOR_LEVANTADO_EMPRESA,
    VALOR_LEVANTADO_PARTE_CONTRARIA,
    VALOR_TOTAL_GARANTIAS,
    VALOR,
    TIPO,
    SUB_TIPO_1,
    OBJETO,
    OBJETO_REVISADO,
    FASE,
    --ESTADO_2,
    AUD_INS_DTTM,
    AUD_UPD_DTTM
)
SELECT
    empresa_pertinente,
    tipo_de_transferencia,
    CAST(nro_legales AS STRING) AS nro_legales,
    CAST(importe AS STRING) AS importe,
    CAST(prazo_fatal AS STRING) AS prazo_fatal,
    numero_da_conta,
    beneficiario_nome,
    estado,
    banco,
    CAST(agencia AS STRING) AS agencia,
    tipo_de_conta,
    cpf_cnpj,
    CAST(fecha_estado AS STRING) AS fecha_estado,
    CAST(provedor AS STRING) AS provedor,
    CAST(factura AS STRING) AS factura,
    acordo,
    tipo_de_procedimento,
    conta_contabil,
    centro_de_custo,
    CAST(fecha AS STRING) AS fecha,
    codigo_de_barras,
    parte_contraria_nome,
    advogado_responsavel,
    CAST(processo_id AS STRING) AS processo_id,
    sub_tipo,
    escritorio_externo,
    processo_classificacao,
    status,
    area_do_direito,
    sub_area_do_direito,
    CAST(valor_levantado_empresa AS STRING) AS valor_levantado_empresa,
    CAST(valor_levantado_parte_contraria AS STRING) AS valor_levantado_parte_contraria,
    CAST(valor_total_garantias AS STRING) AS valor_total_garantias,
    CAST(valor AS STRING) AS valor,
    tipo,
    sub_tipo_1,
    objeto,
    objeto_revisado,
    fase,
    --estado_2,
    CAST(CURRENT_TIMESTAMP() AS DATETIME) AS aud_ins_dttm,
    CAST(CURRENT_TIMESTAMP() AS DATETIME) AS aud_upd_dttm
FROM `<ENV>.TBL.LK_PBD_LA_ELAW_REPORT_PAGAMENTOS_E_GARANTIA`;
