CREATE OR REPLACE TABLE `<ENV>.STG.STG_INPUT_NPS` AS (
  WITH Dim_Objetos_Hispanos AS (
    SELECT
      *
    FROM
      `<ENV>.TBL.LK_PBD_LA_DIM_OBJETOS_2`
    WHERE
      PAIS = "HISPANOS"
  ),
  Base_Hispanos_Matriz AS (
    SELECT
      CAST(COALESCE(inc.PROCESSO_ID, outg.PROCESSO_ID, ong.PROCESSO_ID) AS INT64) AS PROCESSO_ID,
      CAST(COALESCE(inc.PAIS, outg.PAIS, ong.PAIS) AS STRING) AS PAIS,
      CAST(COALESCE(inc.AREA_DO_DIREITO, outg.AREA_DO_DIREITO, ong.AREA_DO_DIREITO) AS STRING) AS AREA_DO_DIREITO,
      CAST(COALESCE(inc.SUB_AREA_DO_DIREITO, outg.SUB_AREA_DO_DIREITO, ong.SUB_AREA_DO_DIREITO) AS STRING) AS SUB_AREA_DO_DIREITO,
      CAST(COALESCE(inc.CLIENTE, outg.CLIENTE, ong.CLIENTE) AS STRING) AS CLIENTE,
      CAST(COALESCE(inc.STATUS, outg.STATUS, ong.STATUS) AS STRING) AS STATUS,
      CAST(COALESCE(inc.PARTE_CONTRARIA_NOME, outg.PARTE_CONTRARIA_NOME, ong.PARTE_CONTRARIA_NOME) AS STRING) AS PARTE_CONTRARIA_NOME,
      CAST(COALESCE(inc.CUST_ID_AUTOR, outg.CUST_ID_AUTOR, ong.CUST_ID_AUTOR) AS STRING) AS CUST_ID_AUTOR,
      CAST(COALESCE(inc.PAGE_REPORT_ESCRITORIORESPONSAVEL, outg.PAGE_REPORT_ESCRITORIORESPONSAVEL, ong.PAGE_REPORT_ESCRITORIORESPONSAVEL) AS STRING) AS PAGE_REPORT_ESCRITORIORESPONSAVEL,
      CAST(COALESCE(inc.PROCESSO_ESTADO, outg.PROCESSO_ESTADO, ong.PROCESSO_ESTADO) AS STRING) AS PROCESSO_ESTADO,
      CAST(COALESCE(inc.DATA_REGISTRADO, outg.DATA_REGISTRADO, ong.DATA_REGISTRADO) AS STRING) AS DATA_REGISTRADO,
      CAST(COALESCE(inc.DATA_DE_ENCERRAMENTO, outg.DATA_DE_ENCERRAMENTO, ong.DATA_DE_ENCERRAMENTO) AS STRING) AS DATA_DE_ENCERRAMENTO,
      CAST(COALESCE(inc.FASE_ESTADO, outg.FASE_ESTADO, ong.FASE_ESTADO) AS STRING) AS FASE_ESTADO,
      CAST(COALESCE(inc.FASE_ESTADO_4, outg.FASE_ESTADO_4, ong.FASE_ESTADO_4) AS STRING) AS FASE_ESTADO_4,
      CAST(COALESCE(inc.DATA_AUDIENCIA_INICIAL, outg.DATA_AUDIENCIA_INICIAL, ong.DATA_AUDIENCIA_INICIAL) AS STRING) AS DATA_AUDIENCIA_INICIAL,
      CAST(
        CASE
          WHEN COALESCE(inc.PAIS, outg.PAIS, ong.PAIS) = 'Brasil' THEN COALESCE(inc.OBJETO, outg.OBJETO, ong.OBJETO)
          WHEN IFNULL(TRIM(COALESCE(inc.OBJETO, outg.OBJETO, ong.OBJETO)), '') = ''
          AND IFNULL(TRIM(COALESCE(inc.CAUSAS_RAIZES, outg.CAUSAS_RAIZES, ong.CAUSAS_RAIZES)), '') <> '' THEN COALESCE(inc.CAUSAS_RAIZES, outg.CAUSAS_RAIZES, ong.CAUSAS_RAIZES)
          WHEN IFNULL(TRIM(COALESCE(inc.OBJETO, outg.OBJETO, ong.OBJETO)), '') <> ''
          AND IFNULL(TRIM(COALESCE(inc.CAUSAS_RAIZES, outg.CAUSAS_RAIZES, ong.CAUSAS_RAIZES)), '') = '' THEN COALESCE(inc.OBJETO, outg.OBJETO, ong.OBJETO)
          ELSE COALESCE(inc.CAUSAS_RAIZES, outg.CAUSAS_RAIZES, ong.CAUSAS_RAIZES)
        END AS STRING
      ) AS OBJETO_CROSS
    FROM
      `<ENV>.TBL.LK_PBD_LA_ELAW_CONTENCIOSO_HISPANOS_INCOMING` AS inc
      FULL OUTER JOIN `<ENV>.TBL.LK_PBD_LA_ELAW_CONTENCIOSO_HISPANOS_OUTGOING` AS outg
      ON inc.PROCESSO_ID = outg.PROCESSO_ID
      FULL OUTER JOIN `<ENV>.TBL.LK_PBD_LA_ELAW_CONTENCIOSO_HISPANOS_ONGOING` AS ong
      ON COALESCE(inc.PROCESSO_ID, outg.PROCESSO_ID) = ong.PROCESSO_ID
  ),
  Base_Hispanos_Encerrados AS (
    SELECT
      a.*,
      CAST(b.OBJETO_NOVO AS STRING) AS OBJETO_NOVO,
      'HISPANOS' AS ORIGEM,
      'Encerrado' AS STATUS_PROCESSO
    FROM
      Base_Hispanos_Matriz a
      LEFT JOIN Dim_Objetos_Hispanos b
      ON UPPER(a.OBJETO_CROSS) = UPPER(b.OBJETO)
    WHERE
      a.STATUS = 'Encerrado'
      AND a.SUB_AREA_DO_DIREITO IN ('Administrativo', 'Pre-Administrativo')
      AND a.FASE_ESTADO = 'Conciliatória'
      AND a.AREA_DO_DIREITO = 'CORP - Consumidor'
      AND SAFE.PARSE_DATE('%d/%m/%Y', a.DATA_DE_ENCERRAMENTO) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 7 DAY) AND CURRENT_DATE()
  ),
  Base_Hispanos_Abertos AS (
    SELECT
      a.*,
      CAST(b.OBJETO_NOVO AS STRING) AS OBJETO_NOVO,
      'HISPANOS' AS ORIGEM,
      'Ativo' AS STATUS_PROCESSO
    FROM
      Base_Hispanos_Matriz a
      LEFT JOIN Dim_Objetos_Hispanos b
      ON UPPER(a.OBJETO_CROSS) = UPPER(b.OBJETO)
    WHERE
      a.STATUS = 'Ativo'
      AND a.FASE_ESTADO_4 = 'Encerrada sem acordo'
      AND SAFE.PARSE_DATE('%d/%m/%Y', a.DATA_AUDIENCIA_INICIAL) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 7 DAY) AND CURRENT_DATE()
  ),
  Dim_Objetos_Brasil AS (
    SELECT
      *
    FROM
      `<ENV>.TBL.LK_PBD_LA_DIM_OBJETOS_2`
    WHERE
      PAIS = "BRASIL"
  ),
  Base_Brasil_Matriz AS (
    SELECT
      CAST(PROCESSO_ID AS INT64) AS PROCESSO_ID,
      CAST(PAIS AS STRING) AS PAIS,
      CAST(AREA_DO_DIREITO AS STRING) AS AREA_DO_DIREITO,
      CAST(SUB_AREA_DO_DIREITO AS STRING) AS SUB_AREA_DO_DIREITO,
      CAST(CLIENTE AS STRING) AS CLIENTE,
      CAST(STATUS AS STRING) AS STATUS,
      CAST(PARTE_CONTRARIA_NOME AS STRING) AS PARTE_CONTRARIA_NOME,
      CAST(CUST_ID_AUTOR AS STRING) AS CUST_ID_AUTOR,
      CAST(PAGE_REPORT_ESCRITORIORESPONSAVEL AS STRING) AS PAGE_REPORT_ESCRITORIORESPONSAVEL,
      CAST(PROCESSO_ESTADO AS STRING) AS PROCESSO_ESTADO,
      CAST(DATA_REGISTRADO AS STRING) AS DATA_REGISTRADO,
      CAST(DATA_DE_ENCERRAMENTO AS STRING) AS DATA_DE_ENCERRAMENTO,
      CAST(NULL AS STRING) AS FASE_ESTADO,
      CAST(FASE_ESTADO_4 AS STRING) AS FASE_ESTADO_4,
      CAST(DATA_AUDIENCIA_INICIAL AS STRING) AS DATA_AUDIENCIA_INICIAL,
      CAST(
        CASE
          WHEN PAIS = 'Brasil' THEN OBJETO
          WHEN IFNULL(TRIM(OBJETO), '') = ''
          AND IFNULL(TRIM(CAUSAS_RAIZES), '') <> '' THEN CAUSAS_RAIZES
          WHEN IFNULL(TRIM(OBJETO), '') <> ''
          AND IFNULL(TRIM(CAUSAS_RAIZES), '') = '' THEN OBJETO
          ELSE CAUSAS_RAIZES
        END AS STRING
      ) AS OBJETO_CROSS
    FROM
      `<ENV>.TBL.LK_PBD_LA_ELAW_CONTENCIOSO_BRASIL_INCOMING`
  ),
  Base_Brasil_Encerrados AS (
    SELECT
      a.*,
      CAST(b.OBJETO_NOVO AS STRING) AS OBJETO_NOVO,
      'BRASIL' AS ORIGEM,
      'Encerrado' AS STATUS_PROCESSO
    FROM
      Base_Brasil_Matriz a
      LEFT JOIN Dim_Objetos_Brasil b
      ON UPPER(a.OBJETO_CROSS) = UPPER(b.OBJETO)
    WHERE
      a.STATUS = 'Encerrado'
      AND a.AREA_DO_DIREITO IN ('Consumidor', 'Cível')
      AND SAFE.PARSE_DATE('%d/%m/%Y', a.DATA_AUDIENCIA_INICIAL) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 7 DAY) AND CURRENT_DATE()
      AND a.CUST_ID_AUTOR IS NOT NULL
      AND a.AREA_DO_DIREITO <> 'Requerimentos'
  ),
  Base_Brasil_Abertos AS (
    SELECT
      a.*,
      CAST(b.OBJETO_NOVO AS STRING) AS OBJETO_NOVO,
      'BRASIL' AS ORIGEM,
      'Ativo' AS STATUS_PROCESSO
    FROM
      Base_Brasil_Matriz a
      LEFT JOIN Dim_Objetos_Brasil b
      ON UPPER(a.OBJETO_CROSS) = UPPER(b.OBJETO)
    WHERE
      a.STATUS = 'Ativo'
      AND a.AREA_DO_DIREITO IN ('Consumidor', 'Cível')
      AND SAFE.PARSE_DATE('%d/%m/%Y', a.DATA_AUDIENCIA_INICIAL) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 7 DAY) AND CURRENT_DATE()
      AND a.CUST_ID_AUTOR IS NOT NULL
      AND a.AREA_DO_DIREITO <> 'Requerimentos'
  ),
  Base_Unificada AS (
    SELECT
      *,
      CASE
        WHEN UPPER(PAIS) = 'BRASIL' THEN 'PT-BR'
        ELSE 'ES'
      END AS Language,
      SPLIT(PARTE_CONTRARIA_NOME, ' ')[OFFSET(0)] AS Firstname,
      REGEXP_REPLACE(PARTE_CONTRARIA_NOME, r'^(\S+)\s*', '') AS Lastname,
      DATE_DIFF(SAFE.PARSE_DATE('%d/%m/%Y', DATA_DE_ENCERRAMENTO), SAFE.PARSE_DATE('%d/%m/%Y', DATA_REGISTRADO), DAY) AS Intervalo
    FROM
      Base_Hispanos_Encerrados
    UNION ALL
    SELECT
      *,
      CASE
        WHEN UPPER(PAIS) = 'BRASIL' THEN 'PT-BR'
        ELSE 'ES'
      END AS Language,
      SPLIT(PARTE_CONTRARIA_NOME, ' ')[OFFSET(0)] AS Firstname,
      REGEXP_REPLACE(PARTE_CONTRARIA_NOME, r'^(\S+)\s*', '') AS Lastname,
      DATE_DIFF(SAFE.PARSE_DATE('%d/%m/%Y', DATA_DE_ENCERRAMENTO), SAFE.PARSE_DATE('%d/%m/%Y', DATA_REGISTRADO), DAY) AS Intervalo
    FROM
      Base_Hispanos_Abertos
    UNION ALL
    SELECT
      *,
      CASE
        WHEN UPPER(PAIS) = 'BRASIL' THEN 'PT-BR'
        ELSE 'ES'
      END AS Language,
      SPLIT(PARTE_CONTRARIA_NOME, ' ')[OFFSET(0)] AS Firstname,
      REGEXP_REPLACE(PARTE_CONTRARIA_NOME, r'^(\S+)\s*', '') AS Lastname,
      DATE_DIFF(SAFE.PARSE_DATE('%d/%m/%Y', DATA_DE_ENCERRAMENTO), SAFE.PARSE_DATE('%d/%m/%Y', DATA_REGISTRADO), DAY) AS Intervalo
    FROM
      Base_Brasil_Encerrados
    UNION ALL
    SELECT
      *,
      CASE
        WHEN UPPER(PAIS) = 'BRASIL' THEN 'PT-BR'
        ELSE 'ES'
      END AS Language,
      SPLIT(PARTE_CONTRARIA_NOME, ' ')[OFFSET(0)] AS Firstname,
      REGEXP_REPLACE(PARTE_CONTRARIA_NOME, r'^(\S+)\s*', '') AS Lastname,
      DATE_DIFF(SAFE.PARSE_DATE('%d/%m/%Y', DATA_DE_ENCERRAMENTO), SAFE.PARSE_DATE('%d/%m/%Y', DATA_REGISTRADO), DAY) AS Intervalo
    FROM
      Base_Brasil_Abertos
  )
  SELECT
    Firstname,
    Lastname,
    Language,
    PAIS AS Pais,
    PROCESSO_ID AS Processo_ID,
    AREA_DO_DIREITO AS Area_do_direito,
    SUB_AREA_DO_DIREITO AS SubArea_do_direito,
    PAGE_REPORT_ESCRITORIORESPONSAVEL AS Escritorio_responsavel,
    PROCESSO_ESTADO AS Processo_uf,
    DATA_REGISTRADO AS Data_Registrado,
    DATA_DE_ENCERRAMENTO AS Data_de_encerramento,
    FASE_ESTADO_4 AS Fase_estado,
    OBJETO_CROSS AS Objeto,
    CAST(Intervalo AS STRING) AS Intervalo,
    CLIENTE AS Cliente,
    SAFE_CAST(CUST_ID_AUTOR AS INT64) AS Cust_ID_Autor,
    CASE
      WHEN REGEXP_CONTAINS(UPPER(FASE_ESTADO_4), r'GANHAMOS|GANAMOS') THEN 'Ganhamos'
      WHEN REGEXP_CONTAINS(UPPER(FASE_ESTADO_4), r'ACORDO|ACORDADO') THEN 'Acordo'
      WHEN REGEXP_CONTAINS(UPPER(FASE_ESTADO_4), r'PERDEMOS') THEN 'Perdemos'
      ELSE 'Outros'
    END AS Tipo_fase
  FROM
    Base_Unificada
);