CREATE
OR REPLACE TABLE `ddme000426-gopr4nla6zo-furyid.STG.LK_PBD_LA_BUDGET_REAL_Atualizada` AS WITH DadosCombinados AS (
    SELECT
        T1.*
    EXCEPT
        (AREA, SUBAREA, EQUIPO),
        COALESCE(T2.AREA, T1.AREA) AS AREA,
        COALESCE(T2.SUBAREA, T1.SUBAREA) AS SUBAREA,
        COALESCE(T2.EQUIPO, T1.EQUIPO) AS EQUIPO
    FROM
        `ddme000426-gopr4nla6zo-furyid.STG.LK_PBD_LA_BUDGET_REAL` AS T1
        LEFT JOIN `ddme000426-gopr4nla6zo-furyid.STG.LK_PBD_LA_BUDGET_REAL_Ajustes_final` AS T2 ON UPPER(CAST(T1.COUNTRY AS STRING)) = UPPER(CAST(T2.COUNTRY AS STRING))
        AND UPPER(CAST(T1.Vendor_Desc AS STRING)) = UPPER(CAST(T2.Vendor_Desc AS STRING))
        AND UPPER(CAST(T1.Area AS STRING)) = UPPER(CAST(T2.Area AS STRING))
        AND UPPER(CAST(T1.Subarea AS STRING)) = UPPER(CAST(T2.Subarea AS STRING))
)
SELECT
    DISTINCT *
FROM
    DadosCombinados;