CREATE
OR REPLACE EXTERNAL TABLE `ddme000426-gopr4nla6zo-furyid.STG.LK_PBD_LA_BUDGET_REAL_Ajustes_temp` (
  COMPANY_ID STRING,
  FISCAL_PERIOD STRING,
  COUNTRY STRING,
  AGRUPADOR_1 STRING,
  AGRUPADOR_2 STRING,
  PL_L0_ID STRING,
  PL_L8_ID STRING,
  VENDOR_ID STRING,
  VENDOR_DESC STRING,
  ITREM_TEXT STRING,
  AREA STRING,
  SUBAREA STRING,
  BU STRING,
  SUBBU STRING,
  BU_AREA STRING,
  ALLOCATION STRING,
  DOCUMENT_TYPE STRING,
  DOCUMENT_TYPE_DESC STRING,
  DOCUMENT_ID STRING,
  ACCOUNT_ID STRING,
  ACCOUNT_DESC STRING,
  COST_CENTER STRING,
  AMOUNT_LC FLOAT64,
  AMOUNT_LC2_GLOB FLOAT64,
  CONCATENADO STRING,
  VERTICAL STRING,
  EQUIPO STRING
) OPTIONS (
  format = 'GOOGLE_SHEETS',
  skip_leading_rows = 1,
  sheet_range = 'Extracto_SUPPLIER_Ajustes!A:AA',
  uris = ['https://docs.google.com/spreadsheets/d/1-r2-qYifcntHzLeQaXVXYMnj0IBHJLrHkCdHpqA39yg/edit?gid=1730157001#gid=1730157001']
);

----


CREATE
OR REPLACE TABLE `ddme000426-gopr4nla6zo-furyid.STG.LK_PBD_LA_BUDGET_REAL_FINAL_ajustes` AS
select
  'Real' AS Versao,
  2025 AS Ano,
  FORMAT_DATE(
    '%B',
    PARSE_DATE('%Y%m', CAST(FISCAL_PERIOD AS STRING))
  ) AS Mes,
  COUNTRY,
  AGRUPADOR_1,
  AGRUPADOR_2,
  PL_L8_ID AS Account_name,
  VENDOR_DESC AS Vendor_Desc,
  ITREM_TEXT AS Item_Text,
  AREA,
  SUBAREA,
  BU,
  SUBBU AS SubBU,
  ALLOCATION AS Allocation,
  DOCUMENT_TYPE_DESC AS Document_Type_Desc,
  DOCUMENT_ID AS Document_ID,
  '' AS Supplier_Unificado,
  EQUIPO,
  FORMAT('%0.2f', SAFE_CAST(AMOUNT_LC AS FLOAT64)) AS Valor_Local,
  FORMAT('%0.2f', SAFE_CAST(AMOUNT_LC2_GLOB AS FLOAT64)) AS Valor_USD
from
  `ddme000426-gopr4nla6zo-furyid.STG.LK_PBD_LA_BUDGET_REAL_Ajustes_temp`