CREATE OR REPLACE EXTERNAL TABLE `<ENV>.STG.INPUT_DE_IDS` (
  Cust_ID_Autor STRING
)
OPTIONS (
  format = 'GOOGLE_SHEETS',
  skip_leading_rows = 1,
  sheet_range = 'Input_Manual!A:A',
  uris = ['https://docs.google.com/spreadsheets/d/1jODz75dZM_-o3b-IKLzrdiXJy0M57KWIkh09v_Ddxso']
);

CREATE OR REPLACE TABLE `<ENV>.STG.DADOS_MLM_MLM` AS
WITH
CTE_INPUT_MANUAL AS (
  SELECT DISTINCT
    Cust_ID_Autor
  FROM `<ENV>.STG.INPUT_DE_IDS`
  WHERE Cust_ID_Autor IS NOT NULL
    AND Cust_ID_Autor != ''
),

CTE_HISPANOS AS (
  SELECT DISTINCT
    LEFT(CUST_ID_AUTOR, 10) AS Cust_ID_Autor
  FROM `<ENV>.TBL.LK_PBD_LA_ELAW_CONTENCIOSO_HISPANOS_ONGOING`
  WHERE pais IN ('Argentina', 'Mexico')
    AND status = 'Ativo'
    AND CUST_ID_AUTOR IS NOT NULL
),

CTE_BRASIL AS (
  SELECT DISTINCT
    LEFT(CUST_ID_AUTOR, 10) AS Cust_ID_Autor
  FROM `<ENV>.TBL.LK_PBD_LA_ELAW_CONTENCIOSO_BRASIL_ONGOING`
  WHERE status = 'Ativo'
    AND CUST_ID_AUTOR IS NOT NULL
),

CTE_BASE_CONSOLIDADA AS (
  SELECT Cust_ID_Autor FROM CTE_HISPANOS
  UNION ALL
  SELECT Cust_ID_Autor FROM CTE_BRASIL
),

CTE_UNIAO_FINAL AS (
  SELECT Cust_ID_Autor FROM CTE_INPUT_MANUAL
  UNION ALL
  SELECT Cust_ID_Autor FROM CTE_BASE_CONSOLIDADA
)

SELECT DISTINCT
  Cust_ID_Autor
FROM CTE_UNIAO_FINAL
WHERE Cust_ID_Autor IS NOT NULL
  AND Cust_ID_Autor != '';
