-----
--Captura de dados Brasil
-----
WITH TABELA_FILTRADA_BRASIL AS (
    SELECT
        *,
        CASE
            WHEN FASE_DESFECHO = "Ganhamos" THEN 0
            ELSE SAFE_CAST(VALOR_DO_RISCO AS FLOAT64)
        END AS VALOR_DO_RISCO_AJUSTADO,
        CASE
            WHEN FASE_DESFECHO = "Ganhamos" THEN 0
            WHEN SAFE_CAST(VALOR_DO_RISCO AS FLOAT64) > 0
            AND SAFE_CAST(VALOR_DO_RISCO AS FLOAT64) <= 20000 THEN 1
            WHEN SAFE_CAST(VALOR_DO_RISCO AS FLOAT64) > 20000
            AND SAFE_CAST(VALOR_DO_RISCO AS FLOAT64) <= 100000 THEN 2
            WHEN SAFE_CAST(VALOR_DO_RISCO AS FLOAT64) > 100000
            AND SAFE_CAST(VALOR_DO_RISCO AS FLOAT64) <= 500000 THEN 3
            WHEN SAFE_CAST(VALOR_DO_RISCO AS FLOAT64) > 500000
            AND SAFE_CAST(VALOR_DO_RISCO AS FLOAT64) <= 1000000 THEN 4
            WHEN SAFE_CAST(VALOR_DO_RISCO AS FLOAT64) > 1000000 THEN 5
            ELSE 0
        END AS FAIXA_RISCO
    FROM
        `pdme000426-c1s7scatwm0-furyid.STG.LK_PBD_LA_ENTRADAS_E_DESFECHOS`
    WHERE
        AREA_DO_DIREITO IN ("Consumidor", "Cível")
        AND PROCESSO_CLASSIFICACAO = "Normal"
        AND PAIS = "Brasil"
        AND STATUS = "Encerrado"
),
ENRIQUECIMENTO_NORMAL_BRASIL AS (
    SELECT
        A.*,
        IFNULL(SAFE_CAST(B.Valor_Honorario AS FLOAT64), 0) AS Valor_Honorario
    FROM
        TABELA_FILTRADA_BRASIL AS A
        LEFT JOIN `pdme000426-c1s7scatwm0-furyid.STG.LK_PBD_LA_HONORARIOS_NORMAL_FATO` AS B ON A.AREA_DO_DIREITO = B.Area
        AND A.SUB_AREA_DO_DIREITO = B.SubArea
        AND A.PAIS = B.PAIS
        AND A.PROCEDIMENTO_JUDICIAL = B.Procedimento
        AND A.PROCESSO_CLASSIFICACAO = B.Classificacao
        AND A.FASE_DESFECHO = B.Tipo_desfecho
),
ENRIQUECIMENTO_ESTRATEGICO_BRASIL AS (
    SELECT
        A.*,
        IFNULL(SAFE_CAST(B.Valor_Honorario AS FLOAT64), 0) AS Valor_Honorario_Estrategico
    FROM
        ENRIQUECIMENTO_NORMAL_BRASIL AS A
        LEFT JOIN `pdme000426-c1s7scatwm0-furyid.STG.LK_PBD_LA_HONORARIOS_ESTRATEGICO_FATO` AS B ON A.AREA_DO_DIREITO = B.Area
        AND A.SUB_AREA_DO_DIREITO = B.SubArea
        AND A.PAIS = B.PAIS
        AND A.PROCEDIMENTO_JUDICIAL = B.Procedimento -- AND A.PROCESSO_CLASSIFICACAO = B.Classificacao
        AND A.FASE_DESFECHO = B.Tipo_desfecho
        AND A.FAIXA_RISCO = SAFE_CAST(B.Faixa AS INT64)
),
FINAL_BRASIL AS(
    SELECT
        DATA_DE_CITACAO,
        PROCESSO_ID,
        PASTA,
        PAIS,
        NUMERO_DO_PROCESSO,
        OUTROS_NUMEROS,
        STATUS,
        AREA_DO_DIREITO,
        SUB_AREA_DO_DIREITO,
        CLIENTE,
        PARTE_CONTRARIA_NOME,
        CUST_ID_AUTOR,
        OUTRAS_PARTES_NAO_CLIENTES,
        PAGE_REPORT_ESCRITORIORESPONSAVEL,
        DATA_AUDIENCIA_INICIAL,
        ADVOGADO_RESPONSAVEL,
        PROCESSO_ESTADO,
        PROCESSO_COMARCA,
        PROCESSO_FORO_TRIBUNAL_ORGAO,
        PROCESSO_VARA_ORGAO,
        ACAO,
        OBJETO,
        OBJETO_1,
        DETALHAMENTO_DO_OBJETO,
        DISTRIBUICAO,
        TIPO_DE_CONTINGENCIA,
        RISCO,
        OBSERVACAO,
        TIPO_DA_AUDIENCIA_INICIAL,
        VALOR_DA_CAUSA,
        OUTROS_CLIENTES_REU,
        MODALIDADE,
        SAFE.PARSE_DATE('%d/%m/%Y', DATA_REGISTRADO) AS DATA_REGISTRADO,
        CPF_CNPJ,
        -- PARTE_CONTRARIA_CPF,
        SAFE.PARSE_DATE('%d/%m/%Y', DATA_DE_ENCERRAMENTO) AS DATA_DE_ENCERRAMENTO,
        DATA_DE_REGISTRO_DO_ENCERRAMENTO,
        DATA_DO_ENVIO_AO_ESCRITORIO,
        PROCEDIMENTO_JUDICIAL,
        -- RESUMO_DO_SUBSIDIO,
        ADVOGADO_DA_PARTE_CONTRARIA_NOME,
        ADVOGADOS_PARTICIPANTES,
        ADVOGADO_DA_PARTE_CONTRARIA_CPF,
        CUST_ID_CONTRAPARTE,
        ID_MEDIACAO,
        CENTRO_CUSTO_NOME,
        CENTRO_DE_CUSTO_CODIGO,
        VALOR_DO_RISCO,
        COMPORTAMENTO_DO_USUARIO_CX,
        ID_DO_PAGAMENTO,
        FASE_ESTADO,
        FASE_ESTADO_4,
        PARTE_CONTRARIA_CONTUMAZ,
        ADVOGADO_PARTE_CONTRARIA_CONTUMAZ,
        USUARIO,
        AUDIENCIA_PENDENTE_DATA,
        MOTIVO_DE_ENCERRAMENTO,
        CARATULA,
        INDICA_MENORIDADE,
        PROCESSO_CLASSIFICACAO,
        INVOCA_HIPERVULNERABILIDAD,
        CAUSAS_RAIZES,
        CAUSAS_RAIZES_1,
        CAUSAS_RAIZES_2,
        ID_DE_SALESFORCE,
        MODELO_DE_CONTRATACAO,
        NUMERO_DE_ENVIO,
        USUARIO_RECLAMOU_A_CX,
        PROCESO_CRITICO,
        CBT,
        UNIDADE_DE_NEGOCIO_IMPACTADA,
        CAMPOS_DE_ALTERACAO_DE_VALOR_IDENTIFICACAO_DO_PAGAMENTO,
        PROCESSO_CUST_ID_CONTRAPARTE,
        PROCESSO_IDENTIFICACAO_DO_PAGAMENTO,
        VALOR_1_INSTANCIA,
        INFORMACOES_COMPLEMENTARES_CUST_ID_CONTRAPARTE,
        PROCESSO_CUST_ID_CONTRAPARTE_1,
        PROCESSO_APELIDO_CONTRAPARTE,
        EMPRESA_RESPONSAVEL,
        PROCESSO_IDENTIFICACAO_DO_PAGAMENTO_1,
        PROCESSO_EMPRESA_DEMANDADA,
        HISP_SUBSIDIOS_ID_DA_OPERACAO_MP,
        HISP_SUBSIDIOS_STATUS_DO_PAGAMENTO,
        HISP_SUBSIDIOS_CUST_ID_AUTOR,
        HISP_SUBSIDIOS_NUMERO_DE_ENVIO,
        PROCESSO_CUSTID_MELI,
        PROCESSO_REVISADO_POR_DRE,
        PROCESSO_ESCRITORIO_DO_ADVOGADO_DA_PARTE_CONTRARIA,
        PROCESSO_MATERIA,
        JUSTICA,
        PROCESSO_OBJETO_REVISADO,
        PROCESSO_REVISADO_POR_DRE_1,
        FORMA_DE_PARTICIPACAO,
        -- ESCRITORIO_EXTERNO,
        PEDIDO,
        PROCESSO_APRESENTADA_RESPOSTA_NEGATIVA,
        DATA_DE_REATIVACAO,
        MOTIVO_DE_REATIVACAO,
        ACAO_1,
        VALOR_OBJETO,
        PROCESSO_CONDENACAO_EM_MA_FE,
        PROCESSO_VALOR_ASSOCIADO_A_MA_FE,
        PROCESSO_DATA_DENUNCIA,
        PROCESSO_DATA_DO_PROTOCOLO,
        PROCESSO_DATA_INSTAURACAO,
        PROCESSO_ESTADO_DA_DENUNCIA,
        PROCESSO_TIPO_DE_OPERACAO,
        PROCESSO_DATA_DA_OPERACAO,
        PROCESSO_CRIME,
        PROCESSO_CRIME_2,
        PROCESSO_PRAZO,
        ADVOGADO_ESCRITORIO,
        PROCESSO_ESTADO_DE_LA_DENUNCIA,
        DECISAO_ANALISE_DE_RESPONSABILIDADE,
        PROCESSO_SUPERENDIVIDAMENTO,
        DATA_REGISTRADO_TRATADA,
        MULTA_DATA,
        MULTA_TIPO_AJUSTADO,
        REGIAO,
        FASE_DESFECHO,
        OBJETO_TRATADO,
        UNIDADE_TRATADA,
        EMPRESA_TRATADA,
        OBJETO_CROSS,
        MUNDO,
        IFNULL(VALOR_DO_RISCO_AJUSTADO, 0) AS VALOR_DO_RISCO_AJUSTADO,
        IFNULL(FAIXA_RISCO, 0) AS FAIXA_RISCO,
        IFNULL(Valor_Honorario, 0) AS Valor_Honorario,
        IFNULL(Valor_Honorario_Estrategico, 0) AS Valor_Honorario_Estrategico,
        IFNULL(Valor_Honorario_Estrategico, 0) + IFNULL(Valor_Honorario, 0) + IFNULL(VALOR_DO_RISCO_AJUSTADO, 0) AS valor_total
    FROM
        ENRIQUECIMENTO_ESTRATEGICO_BRASIL
),
-----
--Captura de dados Hispanos
-----
TABELA_FILTRADA_HISPANOS AS (
    SELECT
        *
    FROM
        `pdme000426-c1s7scatwm0-furyid.STG.LK_PBD_LA_ENTRADAS_E_DESFECHOS`
    WHERE
        AREA_DO_DIREITO NOT IN ("Consumidor", "Cível") -- AND PROCESSO_CLASSIFICACAO = "Normal"
        AND PAIS <> "Brasil"
        AND STATUS = "Encerrado"
),
FINAL_HISPANOS AS (
    SELECT
        DATA_DE_CITACAO,
        PROCESSO_ID,
        PASTA,
        PAIS,
        NUMERO_DO_PROCESSO,
        OUTROS_NUMEROS,
        STATUS,
        AREA_DO_DIREITO,
        SUB_AREA_DO_DIREITO,
        CLIENTE,
        PARTE_CONTRARIA_NOME,
        CUST_ID_AUTOR,
        OUTRAS_PARTES_NAO_CLIENTES,
        PAGE_REPORT_ESCRITORIORESPONSAVEL,
        DATA_AUDIENCIA_INICIAL,
        ADVOGADO_RESPONSAVEL,
        PROCESSO_ESTADO,
        PROCESSO_COMARCA,
        PROCESSO_FORO_TRIBUNAL_ORGAO,
        PROCESSO_VARA_ORGAO,
        ACAO,
        OBJETO,
        OBJETO_1,
        DETALHAMENTO_DO_OBJETO,
        DISTRIBUICAO,
        TIPO_DE_CONTINGENCIA,
        RISCO,
        OBSERVACAO,
        TIPO_DA_AUDIENCIA_INICIAL,
        VALOR_DA_CAUSA,
        OUTROS_CLIENTES_REU,
        MODALIDADE,
        SAFE.PARSE_DATE('%d/%m/%Y', DATA_REGISTRADO) AS DATA_REGISTRADO,
        CPF_CNPJ,
        -- PARTE_CONTRARIA_CPF,
        SAFE.PARSE_DATE('%d/%m/%Y', DATA_DE_ENCERRAMENTO) AS DATA_DE_ENCERRAMENTO,
        DATA_DE_REGISTRO_DO_ENCERRAMENTO,
        DATA_DO_ENVIO_AO_ESCRITORIO,
        PROCEDIMENTO_JUDICIAL,
        -- RESUMO_DO_SUBSIDIO,
        ADVOGADO_DA_PARTE_CONTRARIA_NOME,
        ADVOGADOS_PARTICIPANTES,
        ADVOGADO_DA_PARTE_CONTRARIA_CPF,
        CUST_ID_CONTRAPARTE,
        ID_MEDIACAO,
        CENTRO_CUSTO_NOME,
        CENTRO_DE_CUSTO_CODIGO,
        VALOR_DO_RISCO,
        COMPORTAMENTO_DO_USUARIO_CX,
        ID_DO_PAGAMENTO,
        FASE_ESTADO,
        FASE_ESTADO_4,
        PARTE_CONTRARIA_CONTUMAZ,
        ADVOGADO_PARTE_CONTRARIA_CONTUMAZ,
        USUARIO,
        AUDIENCIA_PENDENTE_DATA,
        MOTIVO_DE_ENCERRAMENTO,
        CARATULA,
        INDICA_MENORIDADE,
        PROCESSO_CLASSIFICACAO,
        INVOCA_HIPERVULNERABILIDAD,
        CAUSAS_RAIZES,
        CAUSAS_RAIZES_1,
        CAUSAS_RAIZES_2,
        ID_DE_SALESFORCE,
        MODELO_DE_CONTRATACAO,
        NUMERO_DE_ENVIO,
        USUARIO_RECLAMOU_A_CX,
        PROCESO_CRITICO,
        CBT,
        UNIDADE_DE_NEGOCIO_IMPACTADA,
        CAMPOS_DE_ALTERACAO_DE_VALOR_IDENTIFICACAO_DO_PAGAMENTO,
        PROCESSO_CUST_ID_CONTRAPARTE,
        PROCESSO_IDENTIFICACAO_DO_PAGAMENTO,
        VALOR_1_INSTANCIA,
        INFORMACOES_COMPLEMENTARES_CUST_ID_CONTRAPARTE,
        PROCESSO_CUST_ID_CONTRAPARTE_1,
        PROCESSO_APELIDO_CONTRAPARTE,
        EMPRESA_RESPONSAVEL,
        PROCESSO_IDENTIFICACAO_DO_PAGAMENTO_1,
        PROCESSO_EMPRESA_DEMANDADA,
        HISP_SUBSIDIOS_ID_DA_OPERACAO_MP,
        HISP_SUBSIDIOS_STATUS_DO_PAGAMENTO,
        HISP_SUBSIDIOS_CUST_ID_AUTOR,
        HISP_SUBSIDIOS_NUMERO_DE_ENVIO,
        PROCESSO_CUSTID_MELI,
        PROCESSO_REVISADO_POR_DRE,
        PROCESSO_ESCRITORIO_DO_ADVOGADO_DA_PARTE_CONTRARIA,
        PROCESSO_MATERIA,
        JUSTICA,
        PROCESSO_OBJETO_REVISADO,
        PROCESSO_REVISADO_POR_DRE_1,
        FORMA_DE_PARTICIPACAO,
        -- ESCRITORIO_EXTERNO,
        PEDIDO,
        PROCESSO_APRESENTADA_RESPOSTA_NEGATIVA,
        DATA_DE_REATIVACAO,
        MOTIVO_DE_REATIVACAO,
        ACAO_1,
        VALOR_OBJETO,
        PROCESSO_CONDENACAO_EM_MA_FE,
        PROCESSO_VALOR_ASSOCIADO_A_MA_FE,
        PROCESSO_DATA_DENUNCIA,
        PROCESSO_DATA_DO_PROTOCOLO,
        PROCESSO_DATA_INSTAURACAO,
        PROCESSO_ESTADO_DA_DENUNCIA,
        PROCESSO_TIPO_DE_OPERACAO,
        PROCESSO_DATA_DA_OPERACAO,
        PROCESSO_CRIME,
        PROCESSO_CRIME_2,
        PROCESSO_PRAZO,
        ADVOGADO_ESCRITORIO,
        PROCESSO_ESTADO_DE_LA_DENUNCIA,
        DECISAO_ANALISE_DE_RESPONSABILIDADE,
        PROCESSO_SUPERENDIVIDAMENTO,
        DATA_REGISTRADO_TRATADA,
        MULTA_DATA,
        MULTA_TIPO_AJUSTADO,
        REGIAO,
        FASE_DESFECHO,
        OBJETO_TRATADO,
        UNIDADE_TRATADA,
        EMPRESA_TRATADA,
        OBJETO_CROSS,
        MUNDO,
        0 AS VALOR_DO_RISCO_AJUSTADO,
        0 AS FAIXA_RISCO,
        0 AS Valor_Honorario,
        0 AS Valor_Honorario_Estrategico,
        0 AS valor_total
    FROM
        TABELA_FILTRADA_HISPANOS
),
TABELA_FINAL_CONSOLIDADA AS(
    SELECT
        *
    FROM
        FINAL_BRASIL
    UNION
    ALL
    SELECT
        *
    FROM
        FINAL_HISPANOS
)
SELECT
    *
FROM
    TABELA_FINAL_CONSOLIDADA