-- DEV
-- ddme000426-gopr4nla6zo-furyid
-- PROD
-- pdme000426-c1s7scatwm0-furyid
TRUNCATE TABLE `<ENV>.TBL.LK_LEGAL_DATABASE`;

INSERT INTO
    `<ENV>.TBL.LK_LEGAL_DATABASE` (
        LEGAL_ID,
        SIT_SITE_ID,
        LEGAL_STATUS,
        LEGAL_AREA,
        LEGAL_SUBAREA,
        LEGAL_PROCESS_NUMBER,
        LEGAL_PLAINTIFF_LAWYER,
        LEGAL_PLAINTIFF_CUST_ID,
        LEGAL_SELLER_CUST_ID,
        LEGAL_FIRST_HEARING_DATE,
        LEGAL_CLOSING_DATE,
        LEGAL_REACTIVATE_DATE,
        LEGAL_ENTRY_DATE,
        LEGAL_VERTICAL_INVOLVED,
        LEGAL_LAW_OFFICE,
        LEGAL_RISK,
        LEGAL_AMOUNT_CLAIMED,
        PERSONAL_ID,
        VALOR_ACTUALIZADO,
        LEGAL_PHASE,
        LEGAL_PHASE_DETAIL,
        LEGAL_REASON,
        PAY_PAYMENT_ID,
        LEGAL_AMOUNT_UPDATED,
        LEGAL_PROCESS_NAME,
        LEGAL_PLAINTIFF_NAME,
        LEGAL_BU_INVOLVED,
        LEGAL_PHASE_SIMPLIFIED,
        LEGAL_JURISDICTION_STATE,
       
        LEGAL_COMPANY_INVOLVED,
        LEGAL_COURT_TYPE_MLB,
        LEGAL_COURT_AGENCY,
        
        DATA_UPDATE,
        AUD_INS_DTTM,
        AUD_UPD_DTTM
    )
SELECT
    CAST(processo_id AS STRING) AS LEGAL_ID,
    CASE
        WHEN pais = 'Argentina' THEN 'MLA'
        WHEN pais = 'Chile' THEN 'MLC'
        WHEN pais = 'Colombia' THEN 'MCO'
        WHEN pais = 'México' THEN 'MLM'
        WHEN pais = 'Perú' THEN 'MPE'
        WHEN pais = 'Uruguay' THEN 'MLU'
        WHEN pais = 'Brasil' THEN 'MLB'
        WHEN pais = 'Ecuador' THEN 'MEC'
        ELSE pais
    END AS SIT_SITE_ID,
    STATUS AS LEGAL_STATUS,
    CASE
        WHEN AREA_DO_DIREITO IN ('Cível', 'CORP - Civil') THEN 'Civil'
        WHEN AREA_DO_DIREITO IN ('Trabalhista', 'CORP - Laboral') THEN 'Laboral'
        WHEN AREA_DO_DIREITO IN ('Tributário', 'CORP - Tributário') THEN 'Tributario'
        WHEN AREA_DO_DIREITO IN ( 'Requerimentos', 'CORP - Requerimientos') THEN 'Requerimientos'
        WHEN AREA_DO_DIREITO IN ('Criminal', 'CORP - Criminal') THEN 'Criminal'
        WHEN AREA_DO_DIREITO IN ('Consumidor', 'CORP - Consumidor') THEN 'Consumidor'
        ELSE AREA_DO_DIREITO
    END AS LEGAL_AREA,
    CASE 
        WHEN SUB_AREA_DO_DIREITO IN ('Pré Administrativo', 'Pre-Administrativo') THEN 'Pre-Administrativo'
        WHEN SUB_AREA_DO_DIREITO IN ('Notificações') THEN 'Notificaciones'
        WHEN SUB_AREA_DO_DIREITO IN ('Oficios', 'Ofícios') THEN 'Oficios'
        ELSE SUB_AREA_DO_DIREITO
    END AS LEGAL_SUBAREA,
    NUMERO_DO_PROCESSO AS LEGAL_NUMERO_PROCESO,
    ADVOGADO_DA_PARTE_CONTRARIA_NOME AS ABOGADO_PARTE_CONTRARIA_NOMBRE,
    IFNULL(SAFE_CAST(CUST_ID_AUTOR AS BIGINT), 0) AS CUS_CUST_ID,
    CAST(CUST_ID_CONTRAPARTE AS STRING) AS CUST_ID_CONTRAPARTE,

    -- Datas ajustadas para YYYY-MM-DD
    FORMAT_DATE('%Y-%m-%d', SAFE.PARSE_DATE('%d/%m/%Y', DATA_AUDIENCIA_INICIAL)) AS LEGAL_FIRST_HEARING_DATE,
    FORMAT_DATE('%Y-%m-%d', SAFE.PARSE_DATE('%d/%m/%Y', DATA_DE_ENCERRAMENTO)) AS LEGAL_CLOSING_DATE,
    FORMAT_DATE('%Y-%m-%d', SAFE.PARSE_DATE('%d/%m/%Y', DATA_DE_REATIVACAO)) AS LEGAL_REACTIVATE_DATE,
    FORMAT_DATE('%Y-%m-%d', SAFE.PARSE_DATE('%d/%m/%Y', DATA_REGISTRADO)) AS LEGAL_ENTRY_DATE,

    EMPRESA_TRATADA AS VERTICAL_RESPONSABLE,
    PAGE_REPORT_ESCRITORIORESPONSAVEL AS OFICINA_EXTERNA,
    RISCO AS RIESGO,
    CAST(VALOR_DA_CAUSA AS STRING) AS VALOR_SOLICITADO,
    PARTE_CONTRARIA_CPF AS N_DOCUMENTO_USUARIO,
    CAST(VALOR_DO_RISCO AS STRING) AS VALOR_ACTUALIZADO,
    FASE_ESTADO AS FASE_DEL_CASO,
    FASE_ESTADO_4 AS ESTADO_DEL_CASO,
    OBJETO_TRATADO AS OBJETO_MOTIVO_RECLAMO,
    SAFE_CAST(NULLIF(ID_DO_PAGAMENTO, '-') AS BIGINT) AS PAYMENT_ID,
    CASE
        WHEN PAIS = 'Brasil' THEN CAST(VALOR_DO_RISCO AS STRING)
        ELSE CAST(VALOR_1_INSTANCIA AS STRING)
    END AS VL_PRIM_INSTANCIA,
    caratula AS caratula,
    parte_contraria_nome AS parte_contraria_nome,
    UNIDADE_TRATADA AS BU_RESPONSABLE,
    FASE_DESFECHO AS LEGAL_PHASE_SIMPLIFIED,
    PROCESSO_ESTADO AS LEGAL_JURISDICTION_STATE,
    EMPRESA_RESPONSAVEL AS LEGAL_COMPANY_INVOLVED,
    PROCEDIMENTO_JUDICIAL AS LEGAL_COURT_TYPE_MLB,
    PROCESSO_FORO_TRIBUNAL_ORGAO AS LEGAL_COURT_AGENCY,
    CURRENT_DATE() AS DT_UPDATE,
    CAST(CURRENT_TIMESTAMP AS DATETIME) AS AUD_INS_DTTM,
    CAST(CURRENT_TIMESTAMP AS DATETIME) AS AUD_UPD_DTTM
FROM
    `<ENV>.STG.LK_PBD_LA_ENTRADAS_E_DESFECHOS`;
