CREATE OR REPLACE TABLE `<ENV>.STG.tab_painel_embargos`
AS
WITH base AS (
  SELECT
    c.CUS_CUST_ID,
    c.CUS_FIRST_NAME,
    c.CUS_LAST_NAME,
    c.CUS_CUST_DOC_NUMBER,
    c.CUS_NICKNAME,
    -- Campo original que junta os dois
    CONCAT(c.CUS_CUST_DOC_NUMBER, '-', SUBSTR(c.CUS_CUST_DOC_NUMBER, 3, 8)) AS DOC_BUSCAVEL_FLEX,

    -- Novos campos para filtragem
    c.CUS_CUST_DOC_NUMBER AS DOC_CUIT,
    SUBSTR(c.CUS_CUST_DOC_NUMBER, 3, 8) AS DOC_DNI,

    c.SIT_SITE_ID_CUS,
    c.CUS_CUST_STATUS,
    b.AVAILABLE_AMOUNT,
    b.CURRENCY_ID,
    b.UNAV_BY_RESERVE_FOR_POTS,
    a.ASSET_MGMT_STATUS,
    a.ASSET_MGMT_PRODUCT_ID,
    IF(a.ASSET_MGMT_STATUS = 'investing', 1, 0) AS PRIORIDADE
  FROM
    `meli-bi-data.WHOWNER.LK_CUS_CUSTOMERS_DATA` c
  LEFT JOIN
    `meli-bi-data.WHOWNER.BT_MP_USER_BALANCE` b
    ON c.CUS_CUST_ID = b.CUS_CUST_ID
  LEFT JOIN
    `meli-bi-data.WHOWNER.LK_MP_INVESTFW_ACCOUNTS` a
    ON c.CUS_CUST_ID = a.CUS_CUST_ID
  WHERE
    c.CUS_CUST_STATUS = 'active'
    AND c.SIT_SITE_ID_CUS = 'MLA'
    AND b.CURRENCY_ID = 'ARS'
),

priorizado AS (
  SELECT *,
    ROW_NUMBER() OVER (
      PARTITION BY CUS_CUST_ID
      ORDER BY PRIORIDADE DESC
    ) AS RN
  FROM base
)

SELECT
  *,
  CASE
    WHEN ASSET_MGMT_STATUS = 'investing' AND ASSET_MGMT_PRODUCT_ID = 'MLA_BIND_ARS'
      THEN 'REMUNERADA BIND'
    WHEN ASSET_MGMT_STATUS = 'investing' AND ASSET_MGMT_PRODUCT_ID IN ('MLA_MELI_ARS', 'MLA_MELI_ARS_TRANS')
      THEN 'REMUNERADA ALYC'
    ELSE 'NÃO REMUNERADA'
  END AS SEGMENTO_CONTA
FROM priorizado
WHERE RN = 1;