-- ============================================================
-- ACOMPANHAMENTO_DE_TAREFAS_CORP_CX
-- ============================================================
CREATE OR REPLACE TABLE `<ENV>.STG.STG_INPUT_DATABASE_ELAW_ACOMPANHAMENTO_DE_TAREFAS_CORP_CX_FINAL` AS
SELECT
  CAST(empresa AS STRING) AS empresa,
  CAST(data_registrado AS STRING) AS data_registrado,
  CAST(processo_id AS STRING) AS processo_id,
  CAST(comarca AS STRING) AS comarca,
  CAST(numero_do_processo AS STRING) AS numero_do_processo,
  CAST(pasta AS STRING) AS pasta,
  CAST(area_do_direito AS STRING) AS area_do_direito,
  CAST(sub_area_do_direito AS STRING) AS sub_area_do_direito,
  CAST(parte_contraria_nome AS STRING) AS parte_contraria_nome,
  CAST(data_audiencia_inicial AS STRING) AS data_audiencia_inicial,
  CAST(processo_audiencia_ficticia AS STRING) AS processo_audiencia_ficticia,
  CAST(data_de_confirmacao AS STRING) AS data_de_confirmacao,
  CAST(data AS STRING) AS data,
  CAST(fase_de_workflow AS STRING) AS fase_de_workflow,
  CAST(id AS STRING) AS id,
  CAST(status AS STRING) AS status,
  CAST(tipo AS STRING) AS tipo,
  CAST(sub_tipo AS STRING) AS sub_tipo,
  CAST(usuario_confirmado AS STRING) AS usuario_confirmado,
  CAST(workflow AS STRING) AS workflow,
  CAST(pais AS STRING) AS pais,
  CAST(estado AS STRING) AS estado,
  CAST(status_1 AS STRING) AS status_1,
  CAST(tarefas_resumo_do_subsidio AS STRING) AS tarefas_resumo_do_subsidio,
  CAST(resumo_do_subsidio AS STRING) AS resumo_do_subsidio,
  CAST(page_report_escritorioresponsavel AS STRING) AS page_report_escritorioresponsavel,
  CAST(processo_valor_recompensa_action AS STRING) AS processo_valor_recompensa_action,
  CAST(data_registrado AS STRING) AS data_registrado_2,
  CAST(fase AS STRING) AS fase,
  CAST(objeto AS STRING) AS objeto,
  CAST(objeto_1 AS STRING) AS objeto_1,
  CAST(data_resultado_observacao_1_2o_instancia AS STRING) AS data_resultado_observacao_1_2o_instancia,
  CAST(resultado_observacao_4_instancia AS STRING) AS resultado_observacao_4_instancia,
  CAST(resultado_observacao_3_instancia AS STRING) AS resultado_observacao_3_instancia,
  CAST(resultado_observacao_2_4o_instancia AS STRING) AS resultado_observacao_2_4o_instancia,
  CAST(resultado_observacao_2_2o_instancia AS STRING) AS resultado_observacao_2_2o_instancia,
  CAST(resultado_observacao_1_instancia AS STRING) AS resultado_observacao_1_instancia,
  CAST(resultado_observacao_1_5o_instancia AS STRING) AS resultado_observacao_1_5o_instancia,
  CAST(resultado_observacao_1_5o_instancia_1 AS STRING) AS resultado_observacao_1_5o_instancia_1,
  CAST(resultado_observacao_1_4o_instancia AS STRING) AS resultado_observacao_1_4o_instancia,
  CAST(resultado_observacao_1_3o_instancia AS STRING) AS resultado_observacao_1_3o_instancia,
  CAST(resultado_observacao_1_2o_instancia AS STRING) AS resultado_observacao_1_2o_instancia,
  CAST(status_cg AS STRING) AS status_cg,
  CAST(usuario AS STRING) AS usuario,
  CAST(tarefas_quais_as_informacoes_necessarias AS STRING) AS tarefas_quais_as_informacoes_necessarias,
  CAST(quais_subsidios AS STRING) AS quais_subsidios,
  CAST(favor_justificar_a_alteracao_de_valor AS STRING) AS favor_justificar_a_alteracao_de_valor,
  CAST(modalidade AS STRING) AS modalidade,
  CAST(fase_2 AS STRING) AS fase_2,
  CAST(fase_1 AS STRING) AS fase_1,
  CAST(fase_estado AS STRING) AS fase_estado,
  CAST(fase_estado_1 AS STRING) AS fase_estado_1,
  CAST(procedimento_judicial AS STRING) AS procedimento_judicial,
  CAST(data_de_encerramento AS STRING) AS data_de_encerramento,
  CAST(usuario_1 AS STRING) AS usuario_1,
  CAST(subsidio_total_ou_parcial AS STRING) AS subsidio_total_ou_parcial,
  CAST(usuario_reclamou_a_cx AS STRING) AS usuario_reclamou_a_cx,
  CAST(usuario_reclamou_a_cx_1 AS STRING) AS usuario_reclamou_a_cx_1,
  CAST(data_audiencia_inicial_1 AS STRING) AS data_audiencia_inicial_1,
  CAST(advogado_responsavel AS STRING) AS advogado_responsavel,
  CAST(objeto_2 AS STRING) AS objeto_2,
  CAST(objeto_3 AS STRING) AS objeto_3,
  CAST(responsavel AS STRING) AS responsavel,
  CAST(processo_resultado AS STRING) AS processo_resultado,
  CAST(materia AS STRING) AS materia,
  CAST(tarefas_resultado_da_audiencia_grupo AS STRING) AS tarefas_resultado_da_audiencia_grupo,
  CAST(processo_apresentada_resposta_negativa AS STRING) AS processo_apresentada_resposta_negativa,
  CAST(processo_classificacao AS STRING) AS processo_classificacao,
  CAST(prazo AS STRING) AS prazo,
  CAST(descricao_evento_concluido AS STRING) AS descricao_evento_concluido,
  CAST(data_de_reativacao AS STRING) AS data_de_reativacao,
  CAST(motivo_de_reativacao AS STRING) AS motivo_de_reativacao,
  CAST(processo_data_de_reativacao AS STRING) AS processo_data_de_reativacao,
  CAST(processo_justificativa_de_reativacao AS STRING) AS processo_justificativa_de_reativacao,
  CAST(processo_vara_orgao AS STRING) AS processo_vara_orgao,
  CAST(processo_documento_de_identificacao AS STRING) AS processo_documento_de_identificacao,
  CAST(processo_qual_o_motivo_da_solicitacao_de_complementacao AS STRING) AS processo_qual_o_motivo_da_solicitacao_de_complementacao,
  CAST(processo_a_informacao_que_foi_pedida_ja_constava_no_subsidio_inicial AS STRING) AS processo_a_informacao_que_foi_pedida_ja_constava_no_subsidio_inicial
FROM `<ENV>.STG.STG_INPUT_DATABASE_ELAW_ACOMPANHAMENTO_DE_TAREFAS_CORP_CX_FINAL`;


-- ============================================================
-- TAREFAS_AGENDADAS_SUBSIDIOS_HISPANOS_CAP
-- ============================================================
CREATE OR REPLACE TABLE `<ENV>.STG.STG_INPUT_DATABASE_ELAW_TAREFAS_AGENDADAS_SUBSIDIOS_HISPANOS_CAP_FINAL` AS
SELECT
  CAST(empresa AS STRING) AS empresa,
  CAST(data_registrado AS STRING) AS data_registrado,
  CAST(processo_id AS STRING) AS processo_id,
  CAST(comarca AS STRING) AS comarca,
  CAST(numero_do_processo AS STRING) AS numero_do_processo,
  CAST(pasta AS STRING) AS pasta,
  CAST(area_do_direito AS STRING) AS area_do_direito,
  CAST(sub_area_do_direito AS STRING) AS sub_area_do_direito,
  CAST(parte_contraria_nome AS STRING) AS parte_contraria_nome,
  CAST(data_audiencia_inicial AS STRING) AS data_audiencia_inicial,
  CAST(processo_audiencia_ficticia AS STRING) AS processo_audiencia_ficticia,
  CAST(data_de_confirmacao AS STRING) AS data_de_confirmacao,
  CAST(data AS STRING) AS data,
  CAST(fase_de_workflow AS STRING) AS fase_de_workflow,
  CAST(id AS STRING) AS id,
  CAST(status AS STRING) AS status,
  CAST(tipo AS STRING) AS tipo,
  CAST(sub_tipo AS STRING) AS sub_tipo,
  CAST(usuario_confirmado AS STRING) AS usuario_confirmado,
  CAST(workflow AS STRING) AS workflow,
  CAST(pais AS STRING) AS pais,
  CAST(estado AS STRING) AS estado,
  CAST(status_1 AS STRING) AS status_1,
  CAST(tarefas_resumo_do_subsidio AS STRING) AS tarefas_resumo_do_subsidio,
  CAST(resumo_do_subsidio AS STRING) AS resumo_do_subsidio,
  CAST(page_report_escritorioresponsavel AS STRING) AS page_report_escritorioresponsavel,
  CAST(processo_valor_recompensa_action AS STRING) AS processo_valor_recompensa_action,
  CAST(data_registrado AS STRING) AS data_registrado_2,
  CAST(fase AS STRING) AS fase,
  CAST(objeto AS STRING) AS objeto,
  CAST(objeto_1 AS STRING) AS objeto_1,
  CAST(data_resultado_observacao_1_2o_instancia AS STRING) AS data_resultado_observacao_1_2o_instancia,
  CAST(resultado_observacao_4_instancia AS STRING) AS resultado_observacao_4_instancia,
  CAST(resultado_observacao_3_instancia AS STRING) AS resultado_observacao_3_instancia,
  CAST(resultado_observacao_2_4o_instancia AS STRING) AS resultado_observacao_2_4o_instancia,
  CAST(resultado_observacao_2_2o_instancia AS STRING) AS resultado_observacao_2_2o_instancia,
  CAST(resultado_observacao_1_instancia AS STRING) AS resultado_observacao_1_instancia,
  CAST(resultado_observacao_1_5o_instancia AS STRING) AS resultado_observacao_1_5o_instancia,
  CAST(resultado_observacao_1_5o_instancia_1 AS STRING) AS resultado_observacao_1_5o_instancia_1,
  CAST(resultado_observacao_1_4o_instancia AS STRING) AS resultado_observacao_1_4o_instancia,
  CAST(resultado_observacao_1_3o_instancia AS STRING) AS resultado_observacao_1_3o_instancia,
  CAST(resultado_observacao_1_2o_instancia AS STRING) AS resultado_observacao_1_2o_instancia,
  CAST(status_cg AS STRING) AS status_cg,
  CAST(usuario AS STRING) AS usuario,
  CAST(tarefas_quais_as_informacoes_necessarias AS STRING) AS tarefas_quais_as_informacoes_necessarias,
  CAST(quais_subsidios AS STRING) AS quais_subsidios,
  CAST(favor_justificar_a_alteracao_de_valor AS STRING) AS favor_justificar_a_alteracao_de_valor,
  CAST(modalidade AS STRING) AS modalidade,
  CAST(fase_2 AS STRING) AS fase_2,
  CAST(fase_1 AS STRING) AS fase_1,
  CAST(fase_estado AS STRING) AS fase_estado,
  CAST(fase_estado_1 AS STRING) AS fase_estado_1,
  CAST(procedimento_judicial AS STRING) AS procedimento_judicial,
  CAST(data_de_encerramento AS STRING) AS data_de_encerramento,
  CAST(usuario_1 AS STRING) AS usuario_1,
  CAST(subsidio_total_ou_parcial AS STRING) AS subsidio_total_ou_parcial,
  CAST(usuario_reclamou_a_cx AS STRING) AS usuario_reclamou_a_cx,
  CAST(usuario_reclamou_a_cx_1 AS STRING) AS usuario_reclamou_a_cx_1,
  CAST(data_audiencia_inicial_1 AS STRING) AS data_audiencia_inicial_1,
  CAST(advogado_responsavel AS STRING) AS advogado_responsavel,
  CAST(objeto_2 AS STRING) AS objeto_2,
  CAST(objeto_3 AS STRING) AS objeto_3,
  CAST(responsavel AS STRING) AS responsavel,
  CAST(processo_resultado AS STRING) AS processo_resultado,
  CAST(materia AS STRING) AS materia,
  CAST(tarefas_resultado_da_audiencia_grupo AS STRING) AS tarefas_resultado_da_audiencia_grupo,
  CAST(processo_apresentada_resposta_negativa AS STRING) AS processo_apresentada_resposta_negativa,
  CAST(processo_classificacao AS STRING) AS processo_classificacao,
  CAST(prazo AS STRING) AS prazo,
  CAST(descricao_evento_concluido AS STRING) AS descricao_evento_concluido,
  CAST(data_de_reativacao AS STRING) AS data_de_reativacao,
  CAST(motivo_de_reativacao AS STRING) AS motivo_de_reativacao,
  CAST(processo_data_de_reativacao AS STRING) AS processo_data_de_reativacao,
  CAST(processo_justificativa_de_reativacao AS STRING) AS processo_justificativa_de_reativacao,
  CAST(processo_vara_orgao AS STRING) AS processo_vara_orgao,
  CAST(processo_documento_de_identificacao AS STRING) AS processo_documento_de_identificacao,
  CAST(processo_qual_o_motivo_da_solicitacao_de_complementacao AS STRING) AS processo_qual_o_motivo_da_solicitacao_de_complementacao,
  CAST(processo_a_informacao_que_foi_pedida_ja_constava_no_subsidio_inicial AS STRING) AS processo_a_informacao_que_foi_pedida_ja_constava_no_subsidio_inicial,
  CAST(data_da_tarefa AS STRING) AS data_da_tarefa
FROM `<ENV>.STG.STG_INPUT_DATABASE_ELAW_TAREFAS_AGENDADAS_SUBSIDIOS_HISPANOS_CAP_FINAL`;


-- ============================================================
-- TAREFAS_AGENDADAS_SUBSIDIOS_HISPANOS_CAP_CX
-- ============================================================
CREATE OR REPLACE TABLE `<ENV>.STG.STG_INPUT_DATABASE_ELAW_TAREFAS_AGENDADAS_SUBSIDIOS_HISPANOS_CAP_CX_FINAL` AS
SELECT
  CAST(empresa AS STRING) AS empresa,
  CAST(data_registrado AS STRING) AS data_registrado,
  CAST(processo_id AS STRING) AS processo_id,
  CAST(comarca AS STRING) AS comarca,
  CAST(numero_do_processo AS STRING) AS numero_do_processo,
  CAST(pasta AS STRING) AS pasta,
  CAST(area_do_direito AS STRING) AS area_do_direito,
  CAST(sub_area_do_direito AS STRING) AS sub_area_do_direito,
  CAST(parte_contraria_nome AS STRING) AS parte_contraria_nome,
  CAST(data_audiencia_inicial AS STRING) AS data_audiencia_inicial,
  CAST(processo_audiencia_ficticia AS STRING) AS processo_audiencia_ficticia,
  CAST(data_de_confirmacao AS STRING) AS data_de_confirmacao,
  CAST(data AS STRING) AS data,
  CAST(fase_de_workflow AS STRING) AS fase_de_workflow,
  CAST(id AS STRING) AS id,
  CAST(status AS STRING) AS status,
  CAST(tipo AS STRING) AS tipo,
  CAST(sub_tipo AS STRING) AS sub_tipo,
  CAST(usuario_confirmado AS STRING) AS usuario_confirmado,
  CAST(workflow AS STRING) AS workflow,
  CAST(pais AS STRING) AS pais,
  CAST(estado AS STRING) AS estado,
  CAST(status_1 AS STRING) AS status_1,
  CAST(tarefas_resumo_do_subsidio AS STRING) AS tarefas_resumo_do_subsidio,
  CAST(resumo_do_subsidio AS STRING) AS resumo_do_subsidio,
  CAST(page_report_escritorioresponsavel AS STRING) AS page_report_escritorioresponsavel,
  CAST(processo_valor_recompensa_action AS STRING) AS processo_valor_recompensa_action,
  CAST(data_registrado AS STRING) AS data_registrado_2,
  CAST(fase AS STRING) AS fase,
  CAST(objeto AS STRING) AS objeto,
  CAST(objeto_1 AS STRING) AS objeto_1,
  CAST(data_resultado_observacao_1_2o_instancia AS STRING) AS data_resultado_observacao_1_2o_instancia,
  CAST(resultado_observacao_4_instancia AS STRING) AS resultado_observacao_4_instancia,
  CAST(resultado_observacao_3_instancia AS STRING) AS resultado_observacao_3_instancia,
  CAST(resultado_observacao_2_4o_instancia AS STRING) AS resultado_observacao_2_4o_instancia,
  CAST(resultado_observacao_2_2o_instancia AS STRING) AS resultado_observacao_2_2o_instancia,
  CAST(resultado_observacao_1_instancia AS STRING) AS resultado_observacao_1_instancia,
  CAST(resultado_observacao_1_5o_instancia AS STRING) AS resultado_observacao_1_5o_instancia,
  CAST(resultado_observacao_1_5o_instancia_1 AS STRING) AS resultado_observacao_1_5o_instancia_1,
  CAST(resultado_observacao_1_4o_instancia AS STRING) AS resultado_observacao_1_4o_instancia,
  CAST(resultado_observacao_1_3o_instancia AS STRING) AS resultado_observacao_1_3o_instancia,
  CAST(resultado_observacao_1_2o_instancia AS STRING) AS resultado_observacao_1_2o_instancia,
  CAST(status_cg AS STRING) AS status_cg,
  CAST(usuario AS STRING) AS usuario,
  CAST(tarefas_quais_as_informacoes_necessarias AS STRING) AS tarefas_quais_as_informacoes_necessarias,
  CAST(quais_subsidios AS STRING) AS quais_subsidios,
  CAST(favor_justificar_a_alteracao_de_valor AS STRING) AS favor_justificar_a_alteracao_de_valor,
  CAST(modalidade AS STRING) AS modalidade,
  CAST(fase_2 AS STRING) AS fase_2,
  CAST(fase_1 AS STRING) AS fase_1,
  CAST(fase_estado AS STRING) AS fase_estado,
  CAST(fase_estado_1 AS STRING) AS fase_estado_1,
  CAST(procedimento_judicial AS STRING) AS procedimento_judicial,
  CAST(data_de_encerramento AS STRING) AS data_de_encerramento,
  CAST(usuario_1 AS STRING) AS usuario_1,
  CAST(subsidio_total_ou_parcial AS STRING) AS subsidio_total_ou_parcial,
  CAST(usuario_reclamou_a_cx AS STRING) AS usuario_reclamou_a_cx,
  CAST(usuario_reclamou_a_cx_1 AS STRING) AS usuario_reclamou_a_cx_1,
  CAST(data_audiencia_inicial_1 AS STRING) AS data_audiencia_inicial_1,
  CAST(advogado_responsavel AS STRING) AS advogado_responsavel,
  CAST(objeto_2 AS STRING) AS objeto_2,
  CAST(objeto_3 AS STRING) AS objeto_3,
  CAST(responsavel AS STRING) AS responsavel,
  CAST(processo_resultado AS STRING) AS processo_resultado,
  CAST(materia AS STRING) AS materia,
  CAST(tarefas_resultado_da_audiencia_grupo AS STRING) AS tarefas_resultado_da_audiencia_grupo,
  CAST(processo_apresentada_resposta_negativa AS STRING) AS processo_apresentada_resposta_negativa,
  CAST(processo_classificacao AS STRING) AS processo_classificacao,
  CAST(prazo AS STRING) AS prazo,
  CAST(descricao_evento_concluido AS STRING) AS descricao_evento_concluido,
  CAST(data_de_reativacao AS STRING) AS data_de_reativacao,
  CAST(motivo_de_reativacao AS STRING) AS motivo_de_reativacao,
  CAST(processo_data_de_reativacao AS STRING) AS processo_data_de_reativacao,
  CAST(processo_justificativa_de_reativacao AS STRING) AS processo_justificativa_de_reativacao,
  CAST(processo_vara_orgao AS STRING) AS processo_vara_orgao,
  CAST(processo_documento_de_identificacao AS STRING) AS processo_documento_de_identificacao,
  CAST(processo_qual_o_motivo_da_solicitacao_de_complementacao AS STRING) AS processo_qual_o_motivo_da_solicitacao_de_complementacao,
  CAST(processo_a_informacao_que_foi_pedida_ja_constava_no_subsidio_inicial AS STRING) AS processo_a_informacao_que_foi_pedida_ja_constava_no_subsidio_inicial,
  CAST(data_da_tarefa AS STRING) AS data_da_tarefa
FROM `<ENV>.STG.STG_INPUT_DATABASE_ELAW_TAREFAS_AGENDADAS_SUBSIDIOS_HISPANOS_CAP_CX_FINAL`;


-- ============================================================
-- TAREFAS_AGENDADAS_SUBSIDIOS_HISPANOS_DR
-- ============================================================
CREATE OR REPLACE TABLE `<ENV>.STG.STG_INPUT_DATABASE_ELAW_TAREFAS_AGENDADAS_SUBSIDIOS_HISPANOS_DR_FINAL` AS
SELECT
  CAST(empresa AS STRING) AS empresa,
  CAST(data_registrado AS STRING) AS data_registrado,
  CAST(processo_id AS STRING) AS processo_id,
  CAST(comarca AS STRING) AS comarca,
  CAST(numero_do_processo AS STRING) AS numero_do_processo,
  CAST(pasta AS STRING) AS pasta,
  CAST(area_do_direito AS STRING) AS area_do_direito,
  CAST(sub_area_do_direito AS STRING) AS sub_area_do_direito,
  CAST(parte_contraria_nome AS STRING) AS parte_contraria_nome,
  CAST(data_audiencia_inicial AS STRING) AS data_audiencia_inicial,
  CAST(processo_audiencia_ficticia AS STRING) AS processo_audiencia_ficticia,
  CAST(data_de_confirmacao AS STRING) AS data_de_confirmacao,
  CAST(data AS STRING) AS data,
  CAST(fase_de_workflow AS STRING) AS fase_de_workflow,
  CAST(id AS STRING) AS id,
  CAST(status AS STRING) AS status,
  CAST(tipo AS STRING) AS tipo,
  CAST(sub_tipo AS STRING) AS sub_tipo,
  CAST(usuario_confirmado AS STRING) AS usuario_confirmado,
  CAST(workflow AS STRING) AS workflow,
  CAST(pais AS STRING) AS pais,
  CAST(estado AS STRING) AS estado,
  CAST(status_1 AS STRING) AS status_1,
  CAST(tarefas_resumo_do_subsidio AS STRING) AS tarefas_resumo_do_subsidio,
  CAST(resumo_do_subsidio AS STRING) AS resumo_do_subsidio,
  CAST(page_report_escritorioresponsavel AS STRING) AS page_report_escritorioresponsavel,
  CAST(processo_valor_recompensa_action AS STRING) AS processo_valor_recompensa_action,
  CAST(data_registrado AS STRING) AS data_registrado_2,
  CAST(fase AS STRING) AS fase,
  CAST(objeto AS STRING) AS objeto,
  CAST(objeto_1 AS STRING) AS objeto_1,
  CAST(data_resultado_observacao_1_2o_instancia AS STRING) AS data_resultado_observacao_1_2o_instancia,
  CAST(resultado_observacao_4_instancia AS STRING) AS resultado_observacao_4_instancia,
  CAST(resultado_observacao_3_instancia AS STRING) AS resultado_observacao_3_instancia,
  CAST(resultado_observacao_2_4o_instancia AS STRING) AS resultado_observacao_2_4o_instancia,
  CAST(resultado_observacao_2_2o_instancia AS STRING) AS resultado_observacao_2_2o_instancia,
  CAST(resultado_observacao_1_instancia AS STRING) AS resultado_observacao_1_instancia,
  CAST(resultado_observacao_1_5o_instancia AS STRING) AS resultado_observacao_1_5o_instancia,
  CAST(resultado_observacao_1_5o_instancia_1 AS STRING) AS resultado_observacao_1_5o_instancia_1,
  CAST(resultado_observacao_1_4o_instancia AS STRING) AS resultado_observacao_1_4o_instancia,
  CAST(resultado_observacao_1_3o_instancia AS STRING) AS resultado_observacao_1_3o_instancia,
  CAST(resultado_observacao_1_2o_instancia AS STRING) AS resultado_observacao_1_2o_instancia,
  CAST(status_cg AS STRING) AS status_cg,
  CAST(usuario AS STRING) AS usuario,
  CAST(tarefas_quais_as_informacoes_necessarias AS STRING) AS tarefas_quais_as_informacoes_necessarias,
  CAST(quais_subsidios AS STRING) AS quais_subsidios,
  CAST(favor_justificar_a_alteracao_de_valor AS STRING) AS favor_justificar_a_alteracao_de_valor,
  CAST(modalidade AS STRING) AS modalidade,
  CAST(fase_2 AS STRING) AS fase_2,
  CAST(fase_1 AS STRING) AS fase_1,
  CAST(fase_estado AS STRING) AS fase_estado,
  CAST(fase_estado_1 AS STRING) AS fase_estado_1,
  CAST(procedimento_judicial AS STRING) AS procedimento_judicial,
  CAST(data_de_encerramento AS STRING) AS data_de_encerramento,
  CAST(usuario_1 AS STRING) AS usuario_1,
  CAST(subsidio_total_ou_parcial AS STRING) AS subsidio_total_ou_parcial,
  CAST(usuario_reclamou_a_cx AS STRING) AS usuario_reclamou_a_cx,
  CAST(usuario_reclamou_a_cx_1 AS STRING) AS usuario_reclamou_a_cx_1,
  CAST(data_audiencia_inicial_1 AS STRING) AS data_audiencia_inicial_1,
  CAST(advogado_responsavel AS STRING) AS advogado_responsavel,
  CAST(objeto_2 AS STRING) AS objeto_2,
  CAST(objeto_3 AS STRING) AS objeto_3,
  CAST(responsavel AS STRING) AS responsavel,
  CAST(processo_resultado AS STRING) AS processo_resultado,
  CAST(materia AS STRING) AS materia,
  CAST(tarefas_resultado_da_audiencia_grupo AS STRING) AS tarefas_resultado_da_audiencia_grupo,
  CAST(processo_apresentada_resposta_negativa AS STRING) AS processo_apresentada_resposta_negativa,
  CAST(processo_classificacao AS STRING) AS processo_classificacao,
  CAST(prazo AS STRING) AS prazo,
  CAST(descricao_evento_concluido AS STRING) AS descricao_evento_concluido,
  CAST(data_de_reativacao AS STRING) AS data_de_reativacao,
  CAST(motivo_de_reativacao AS STRING) AS motivo_de_reativacao,
  CAST(processo_data_de_reativacao AS STRING) AS processo_data_de_reativacao,
  CAST(processo_justificativa_de_reativacao AS STRING) AS processo_justificativa_de_reativacao,
  CAST(processo_vara_orgao AS STRING) AS processo_vara_orgao,
  CAST(processo_documento_de_identificacao AS STRING) AS processo_documento_de_identificacao,
  CAST(processo_qual_o_motivo_da_solicitacao_de_complementacao AS STRING) AS processo_qual_o_motivo_da_solicitacao_de_complementacao,
  CAST(processo_a_informacao_que_foi_pedida_ja_constava_no_subsidio_inicial AS STRING) AS processo_a_informacao_que_foi_pedida_ja_constava_no_subsidio_inicial
FROM `<ENV>.STG.STG_INPUT_DATABASE_ELAW_TAREFAS_AGENDADAS_SUBSIDIOS_HISPANOS_DR_FINAL`;



-- ============================================================
-- TAREFAS_AGENDADAS_SUBSIDIOS_HISPANOS_OPS_ENLI
-- ============================================================
CREATE OR REPLACE TABLE `<ENV>.STG.STG_INPUT_DATABASE_ELAW_TAREFAS_AGENDADAS_SUBSIDIOS_HISPANOS_OPS_ENLI_FINAL` AS
SELECT
  CAST(empresa AS STRING) AS empresa,
  CAST(data_registrado AS STRING) AS data_registrado,
  CAST(processo_id AS STRING) AS processo_id,
  CAST(comarca AS STRING) AS comarca,
  CAST(numero_do_processo AS STRING) AS numero_do_processo,
  CAST(pasta AS STRING) AS pasta,
  CAST(area_do_direito AS STRING) AS area_do_direito,
  CAST(sub_area_do_direito AS STRING) AS sub_area_do_direito,
  CAST(parte_contraria_nome AS STRING) AS parte_contraria_nome,
  CAST(data_audiencia_inicial AS STRING) AS data_audiencia_inicial,
  CAST(processo_audiencia_ficticia AS STRING) AS processo_audiencia_ficticia,
  CAST(data_de_confirmacao AS STRING) AS data_de_confirmacao,
  CAST(data AS STRING) AS data,
  CAST(fase_de_workflow AS STRING) AS fase_de_workflow,
  CAST(id AS STRING) AS id,
  CAST(status AS STRING) AS status,
  CAST(tipo AS STRING) AS tipo,
  CAST(sub_tipo AS STRING) AS sub_tipo,
  CAST(usuario_confirmado AS STRING) AS usuario_confirmado,
  CAST(workflow AS STRING) AS workflow,
  CAST(pais AS STRING) AS pais,
  CAST(estado AS STRING) AS estado,
  CAST(status_1 AS STRING) AS status_1,
  CAST(tarefas_resumo_do_subsidio AS STRING) AS tarefas_resumo_do_subsidio,
  CAST(resumo_do_subsidio AS STRING) AS resumo_do_subsidio,
  CAST(page_report_escritorioresponsavel AS STRING) AS page_report_escritorioresponsavel,
  CAST(processo_valor_recompensa_action AS STRING) AS processo_valor_recompensa_action,
  CAST(data_registrado AS STRING) AS data_registrado_2,
  CAST(fase AS STRING) AS fase,
  CAST(objeto AS STRING) AS objeto,
  CAST(objeto_1 AS STRING) AS objeto_1,
  CAST(data_resultado_observacao_1_2o_instancia AS STRING) AS data_resultado_observacao_1_2o_instancia,
  CAST(resultado_observacao_4_instancia AS STRING) AS resultado_observacao_4_instancia,
  CAST(resultado_observacao_3_instancia AS STRING) AS resultado_observacao_3_instancia,
  CAST(resultado_observacao_2_4o_instancia AS STRING) AS resultado_observacao_2_4o_instancia,
  CAST(resultado_observacao_2_2o_instancia AS STRING) AS resultado_observacao_2_2o_instancia,
  CAST(resultado_observacao_1_instancia AS STRING) AS resultado_observacao_1_instancia,
  CAST(resultado_observacao_1_5o_instancia AS STRING) AS resultado_observacao_1_5o_instancia,
  CAST(resultado_observacao_1_5o_instancia_1 AS STRING) AS resultado_observacao_1_5o_instancia_1,
  CAST(resultado_observacao_1_4o_instancia AS STRING) AS resultado_observacao_1_4o_instancia,
  CAST(resultado_observacao_1_3o_instancia AS STRING) AS resultado_observacao_1_3o_instancia,
  CAST(resultado_observacao_1_2o_instancia AS STRING) AS resultado_observacao_1_2o_instancia,
  CAST(status_cg AS STRING) AS status_cg,
  CAST(usuario AS STRING) AS usuario,
  CAST(tarefas_quais_as_informacoes_necessarias AS STRING) AS tarefas_quais_as_informacoes_necessarias,
  CAST(quais_subsidios AS STRING) AS quais_subsidios,
  CAST(favor_justificar_a_alteracao_de_valor AS STRING) AS favor_justificar_a_alteracao_de_valor,
  CAST(modalidade AS STRING) AS modalidade,
  CAST(fase_2 AS STRING) AS fase_2,
  CAST(fase_1 AS STRING) AS fase_1,
  CAST(fase_estado AS STRING) AS fase_estado,
  CAST(fase_estado_1 AS STRING) AS fase_estado_1,
  CAST(procedimento_judicial AS STRING) AS procedimento_judicial,
  CAST(data_de_encerramento AS STRING) AS data_de_encerramento,
  CAST(usuario_1 AS STRING) AS usuario_1,
  CAST(subsidio_total_ou_parcial AS STRING) AS subsidio_total_ou_parcial,
  CAST(usuario_reclamou_a_cx AS STRING) AS usuario_reclamou_a_cx,
  CAST(usuario_reclamou_a_cx_1 AS STRING) AS usuario_reclamou_a_cx_1,
  CAST(data_audiencia_inicial_1 AS STRING) AS data_audiencia_inicial_1,
  CAST(advogado_responsavel AS STRING) AS advogado_responsavel,
  CAST(objeto_2 AS STRING) AS objeto_2,
  CAST(objeto_3 AS STRING) AS objeto_3,
  CAST(responsavel AS STRING) AS responsavel,
  CAST(processo_resultado AS STRING) AS processo_resultado,
  CAST(materia AS STRING) AS materia,
  CAST(tarefas_resultado_da_audiencia_grupo AS STRING) AS tarefas_resultado_da_audiencia_grupo,
  CAST(processo_apresentada_resposta_negativa AS STRING) AS processo_apresentada_resposta_negativa,
  CAST(processo_classificacao AS STRING) AS processo_classificacao,
  CAST(prazo AS STRING) AS prazo,
  CAST(descricao_evento_concluido AS STRING) AS descricao_evento_concluido,
  CAST(data_de_reativacao AS STRING) AS data_de_reativacao,
  CAST(motivo_de_reativacao AS STRING) AS motivo_de_reativacao,
  CAST(processo_data_de_reativacao AS STRING) AS processo_data_de_reativacao,
  CAST(processo_justificativa_de_reativacao AS STRING) AS processo_justificativa_de_reativacao,
  CAST(processo_vara_orgao AS STRING) AS processo_vara_orgao,
  CAST(processo_documento_de_identificacao AS STRING) AS processo_documento_de_identificacao,
  CAST(processo_qual_o_motivo_da_solicitacao_de_complementacao AS STRING) AS processo_qual_o_motivo_da_solicitacao_de_complementacao,
  CAST(processo_a_informacao_que_foi_pedida_ja_constava_no_subsidio_inicial AS STRING) AS processo_a_informacao_que_foi_pedida_ja_constava_no_subsidio_inicial
FROM `<ENV>.STG.STG_INPUT_DATABASE_ELAW_TAREFAS_AGENDADAS_SUBSIDIOS_HISPANOS_OPS_ENLI_FINAL`;



-- ============================================================
-- TAREFAS_AGENDADAS_SUBSIDIOS_HISPANOS_OPS_INTER
-- ============================================================
CREATE OR REPLACE TABLE `<ENV>.STG.STG_INPUT_DATABASE_ELAW_TAREFAS_AGENDADAS_SUBSIDIOS_HISPANOS_OPS_INTER_FINAL` AS
SELECT
  CAST(empresa AS STRING) AS empresa,
  CAST(data_registrado AS STRING) AS data_registrado,
  CAST(processo_id AS STRING) AS processo_id,
  CAST(comarca AS STRING) AS comarca,
  CAST(numero_do_processo AS STRING) AS numero_do_processo,
  CAST(pasta AS STRING) AS pasta,
  CAST(area_do_direito AS STRING) AS area_do_direito,
  CAST(sub_area_do_direito AS STRING) AS sub_area_do_direito,
  CAST(parte_contraria_nome AS STRING) AS parte_contraria_nome,
  CAST(data_audiencia_inicial AS STRING) AS data_audiencia_inicial,
  CAST(processo_audiencia_ficticia AS STRING) AS processo_audiencia_ficticia,
  CAST(data_de_confirmacao AS STRING) AS data_de_confirmacao,
  CAST(data AS STRING) AS data,
  CAST(fase_de_workflow AS STRING) AS fase_de_workflow,
  CAST(id AS STRING) AS id,
  CAST(status AS STRING) AS status,
  CAST(tipo AS STRING) AS tipo,
  CAST(sub_tipo AS STRING) AS sub_tipo,
  CAST(usuario_confirmado AS STRING) AS usuario_confirmado,
  CAST(workflow AS STRING) AS workflow,
  CAST(pais AS STRING) AS pais,
  CAST(estado AS STRING) AS estado,
  CAST(status_1 AS STRING) AS status_1,
  CAST(tarefas_resumo_do_subsidio AS STRING) AS tarefas_resumo_do_subsidio,
  CAST(resumo_do_subsidio AS STRING) AS resumo_do_subsidio,
  CAST(page_report_escritorioresponsavel AS STRING) AS page_report_escritorioresponsavel,
  CAST(processo_valor_recompensa_action AS STRING) AS processo_valor_recompensa_action,
  CAST(data_registrado AS STRING) AS data_registrado_2,
  CAST(fase AS STRING) AS fase,
  CAST(objeto AS STRING) AS objeto,
  CAST(objeto_1 AS STRING) AS objeto_1,
  CAST(data_resultado_observacao_1_2o_instancia AS STRING) AS data_resultado_observacao_1_2o_instancia,
  CAST(resultado_observacao_4_instancia AS STRING) AS resultado_observacao_4_instancia,
  CAST(resultado_observacao_3_instancia AS STRING) AS resultado_observacao_3_instancia,
  CAST(resultado_observacao_2_4o_instancia AS STRING) AS resultado_observacao_2_4o_instancia,
  CAST(resultado_observacao_2_2o_instancia AS STRING) AS resultado_observacao_2_2o_instancia,
  CAST(resultado_observacao_1_instancia AS STRING) AS resultado_observacao_1_instancia,
  CAST(resultado_observacao_1_5o_instancia AS STRING) AS resultado_observacao_1_5o_instancia,
  CAST(resultado_observacao_1_5o_instancia_1 AS STRING) AS resultado_observacao_1_5o_instancia_1,
  CAST(resultado_observacao_1_4o_instancia AS STRING) AS resultado_observacao_1_4o_instancia,
  CAST(resultado_observacao_1_3o_instancia AS STRING) AS resultado_observacao_1_3o_instancia,
  CAST(resultado_observacao_1_2o_instancia AS STRING) AS resultado_observacao_1_2o_instancia,
  CAST(status_cg AS STRING) AS status_cg,
  CAST(usuario AS STRING) AS usuario,
  CAST(tarefas_quais_as_informacoes_necessarias AS STRING) AS tarefas_quais_as_informacoes_necessarias,
  CAST(quais_subsidios AS STRING) AS quais_subsidios,
  CAST(favor_justificar_a_alteracao_de_valor AS STRING) AS favor_justificar_a_alteracao_de_valor,
  CAST(modalidade AS STRING) AS modalidade,
  CAST(fase_2 AS STRING) AS fase_2,
  CAST(fase_1 AS STRING) AS fase_1,
  CAST(fase_estado AS STRING) AS fase_estado,
  CAST(fase_estado_1 AS STRING) AS fase_estado_1,
  CAST(procedimento_judicial AS STRING) AS procedimento_judicial,
  CAST(data_de_encerramento AS STRING) AS data_de_encerramento,
  CAST(usuario_1 AS STRING) AS usuario_1,
  CAST(subsidio_total_ou_parcial AS STRING) AS subsidio_total_ou_parcial,
  CAST(usuario_reclamou_a_cx AS STRING) AS usuario_reclamou_a_cx,
  CAST(usuario_reclamou_a_cx_1 AS STRING) AS usuario_reclamou_a_cx_1,
  CAST(data_audiencia_inicial_1 AS STRING) AS data_audiencia_inicial_1,
  CAST(advogado_responsavel AS STRING) AS advogado_responsavel,
  CAST(objeto_2 AS STRING) AS objeto_2,
  CAST(objeto_3 AS STRING) AS objeto_3,
  CAST(responsavel AS STRING) AS responsavel,
  CAST(processo_resultado AS STRING) AS processo_resultado,
  CAST(materia AS STRING) AS materia,
  CAST(tarefas_resultado_da_audiencia_grupo AS STRING) AS tarefas_resultado_da_audiencia_grupo,
  CAST(processo_apresentada_resposta_negativa AS STRING) AS processo_apresentada_resposta_negativa,
  CAST(processo_classificacao AS STRING) AS processo_classificacao,
  CAST(prazo AS STRING) AS prazo,
  CAST(descricao_evento_concluido AS STRING) AS descricao_evento_concluido,
  CAST(data_de_reativacao AS STRING) AS data_de_reativacao,
  CAST(motivo_de_reativacao AS STRING) AS motivo_de_reativacao,
  CAST(processo_data_de_reativacao AS STRING) AS processo_data_de_reativacao,
  CAST(processo_justificativa_de_reativacao AS STRING) AS processo_justificativa_de_reativacao,
  CAST(processo_vara_orgao AS STRING) AS processo_vara_orgao,
  CAST(processo_documento_de_identificacao AS STRING) AS processo_documento_de_identificacao,
  CAST(processo_qual_o_motivo_da_solicitacao_de_complementacao AS STRING) AS processo_qual_o_motivo_da_solicitacao_de_complementacao,
  CAST(processo_a_informacao_que_foi_pedida_ja_constava_no_subsidio_inicial AS STRING) AS processo_a_informacao_que_foi_pedida_ja_constava_no_subsidio_inicial
FROM `<ENV>.STG.STG_INPUT_DATABASE_ELAW_TAREFAS_AGENDADAS_SUBSIDIOS_HISPANOS_OPS_INTER_FINAL`;



-- ============================================================
-- TAREFAS_AGENDADAS_AGUARDANDO_INFORMACOES
-- (Comentado: não existe base que alimente esta tabela _FINAL.)
-- ============================================================
/*
CREATE OR REPLACE TABLE `<ENV>.STG.STG_INPUT_DATABASE_ELAW_TAREFAS_AGENDADAS_AGUARDANDO_INFORMACOES_FINAL` AS
SELECT
  CAST(area_do_direito AS STRING) AS area_do_direito,
  CAST(sub_area_do_direito AS STRING) AS sub_area_do_direito,
  CAST(processo_id AS STRING) AS processo_id,
  CAST(data AS STRING) AS data,
  CAST(sub_tipo AS STRING) AS sub_tipo,
  CAST(responsavel AS STRING) AS responsavel,
  CAST(escritorio_externo AS STRING) AS escritorio_externo,
  CAST(estado AS STRING) AS estado,
  CAST(observacao AS STRING) AS observacao,
  CAST(obrigacao_de_fazer_data_da_intimacao_para_cumprimento AS STRING) AS obrigacao_de_fazer_data_da_intimacao_para_cumprimento,
  CAST(advogado_responsavel AS STRING) AS advogado_responsavel,
  CAST(processo_classificacao AS STRING) AS processo_classificacao,
  CAST(processo_empresa_demandada AS STRING) AS processo_empresa_demandada,
  CAST(objeto AS STRING) AS objeto,
  CAST(status AS STRING) AS status,
  CAST(data_de_confirmacao AS STRING) AS data_de_confirmacao,
  CAST(descricao_evento_concluido AS STRING) AS descricao_evento_concluido,
  CAST(tarefas_motivo_do_ajuste AS STRING) AS tarefas_motivo_do_ajuste
FROM `<ENV>.STG.STG_INPUT_DATABASE_ELAW_TAREFAS_AGENDADAS_AGUARDANDO_INFORMACOES`;
*/


-- ============================================================
-- TAREFAS_AGENDAMENTOS_SUBSIDIOS_CLEAN_CONFIRMADOS
-- ============================================================
CREATE OR REPLACE TABLE `<ENV>.STG.STG_INPUT_DATABASE_ELAW_TAREFAS_AGENDAMENTOS_SUBSIDIOS_CLEAN_CONFIRMADOS_FINAL` AS
SELECT
  CAST(processo_id AS STRING) AS processo_id,
  CAST(status AS STRING) AS status,
  CAST(data_registrado AS STRING) AS data_registrado,
  CAST(area_do_direito AS STRING) AS area_do_direito,
  CAST(sub_area_do_direito AS STRING) AS sub_area_do_direito,
  CAST(data_de_confirmacao AS STRING) AS data_de_confirmacao,
  CAST(fase_de_workflow AS STRING) AS fase_de_workflow,
  CAST(id AS STRING) AS id,
  CAST(status_1 AS STRING) AS status_1,
  CAST(usuario_confirmado AS STRING) AS usuario_confirmado,
  CAST(workflow AS STRING) AS workflow,
  CAST(pais AS STRING) AS pais,
  CAST(estado AS STRING) AS estado,
  CAST(data_registrado_1 AS STRING) AS data_registrado_1,
  CAST(processo_procedimento_judicial AS STRING) AS processo_procedimento_judicial,
  CAST(objeto AS STRING) AS objeto,
  CAST(objeto_1 AS STRING) AS objeto_1,
  CAST(responsavel AS STRING) AS responsavel,
  CAST(processo_classificacao AS STRING) AS processo_classificacao,
  CAST(tarefas_data_do_prazo AS STRING) AS tarefas_data_do_prazo,
  CAST(processo_prazo AS STRING) AS processo_prazo,
  CAST(processo_objeto_unidade_de_negocio AS STRING) AS processo_objeto_unidade_de_negocio,
  CAST(processo_objeto_objeto AS STRING) AS processo_objeto_objeto,
  CAST(processo_indicar_ajuste_nome_do_campo_erro_detalhamento AS STRING) AS processo_indicar_ajuste_nome_do_campo_erro_detalhamento,
  CAST(processo_informar_ajustes AS STRING) AS processo_informar_ajustes,
  CAST(processo_informar_ajustes_1 AS STRING) AS processo_informar_ajustes_1,
  CAST(processo_indicar_ajuste_nome_do_campo_erro_detalhamento_1 AS STRING) AS processo_indicar_ajuste_nome_do_campo_erro_detalhamento_1,
  CAST(processo_motivo_do_ajuste AS STRING) AS processo_motivo_do_ajuste,
  CAST(processo_pedido_de_ajuste_foi_correto AS STRING) AS processo_pedido_de_ajuste_foi_correto,
  CAST(processo_motivo_do_ajuste_1 AS STRING) AS processo_motivo_do_ajuste_1
FROM `<ENV>.STG.STG_INPUT_DATABASE_ELAW_TAREFAS_AGENDAMENTOS_SUBSIDIOS_CLEAN_CONFIRMADOS_FINAL`;


-- ============================================================
-- TAREFAS_AGENDAMENTOS_SUBSIDIOS_CLEAN_PENDENTES
-- ============================================================
CREATE OR REPLACE TABLE `<ENV>.STG.STG_INPUT_DATABASE_ELAW_TAREFAS_AGENDAMENTOS_SUBSIDIOS_CLEAN_PENDENTES_FINAL` AS
SELECT
  CAST(processo_id AS STRING) AS processo_id,
  CAST(status AS STRING) AS status,
  CAST(data_registrado AS STRING) AS data_registrado,
  CAST(area_do_direito AS STRING) AS area_do_direito,
  CAST(sub_area_do_direito AS STRING) AS sub_area_do_direito,
  CAST(data_de_confirmacao AS STRING) AS data_de_confirmacao,
  CAST(fase_de_workflow AS STRING) AS fase_de_workflow,
  CAST(id AS STRING) AS id,
  CAST(status_1 AS STRING) AS status_1,
  CAST(usuario_confirmado AS STRING) AS usuario_confirmado,
  CAST(workflow AS STRING) AS workflow,
  CAST(pais AS STRING) AS pais,
  CAST(estado AS STRING) AS estado,
  CAST(data_registrado_1 AS STRING) AS data_registrado_1,
  CAST(processo_procedimento_judicial AS STRING) AS processo_procedimento_judicial,
  CAST(objeto AS STRING) AS objeto,
  CAST(objeto_1 AS STRING) AS objeto_1,
  CAST(responsavel AS STRING) AS responsavel,
  CAST(processo_classificacao AS STRING) AS processo_classificacao,
  CAST(tarefas_data_do_prazo AS STRING) AS tarefas_data_do_prazo,
  CAST(processo_prazo AS STRING) AS processo_prazo,
  CAST(processo_objeto_unidade_de_negocio AS STRING) AS processo_objeto_unidade_de_negocio,
  CAST(processo_objeto_objeto AS STRING) AS processo_objeto_objeto,
  CAST(processo_indicar_ajuste_nome_do_campo_erro_detalhamento AS STRING) AS processo_indicar_ajuste_nome_do_campo_erro_detalhamento,
  CAST(processo_informar_ajustes AS STRING) AS processo_informar_ajustes,
  CAST(processo_informar_ajustes_1 AS STRING) AS processo_informar_ajustes_1,
  CAST(processo_indicar_ajuste_nome_do_campo_erro_detalhamento_1 AS STRING) AS processo_indicar_ajuste_nome_do_campo_erro_detalhamento_1,
  CAST(processo_motivo_do_ajuste AS STRING) AS processo_motivo_do_ajuste,
  CAST(processo_pedido_de_ajuste_foi_correto AS STRING) AS processo_pedido_de_ajuste_foi_correto,
  CAST(processo_motivo_do_ajuste_1 AS STRING) AS processo_motivo_do_ajuste_1
FROM `<ENV>.STG.STG_INPUT_DATABASE_ELAW_TAREFAS_AGENDAMENTOS_SUBSIDIOS_CLEAN_PENDENTES_FINAL`;




-- ============================================================
-- AMELIA
-- ============================================================
CREATE OR REPLACE TABLE `<ENV>.STG.LK_PBD_LA_ELAW_REPORT_AMELIA` AS
SELECT
  CAST(pais AS STRING) AS pais,
  CAST(processo_procedimento_judicial AS STRING) AS processo_procedimento_judicial,
  CAST(processo_objeto_objeto AS STRING) AS processo_objeto_objeto,
  CAST(data_audiencia_inicial AS STRING) AS data_audiencia_inicial,
  CAST(processo_audiencia_ficticia AS STRING) AS processo_audiencia_ficticia,
  CAST(processo_invoca_hipervulnerabilidad AS STRING) AS processo_invoca_hipervulnerabilidad,
  CAST(advogado_da_parte_contraria AS STRING) AS advogado_da_parte_contraria,
  CAST(processo_o_usuario_reclama_por_dois_ou_mais_produtos_diferentes AS STRING) AS processo_o_usuario_reclama_por_dois_ou_mais_produtos_diferentes,
  CAST(processo_o_documento_de_identidade_da_reclamacao_corresponde_ao_da_compra AS STRING) AS processo_o_documento_de_identidade_da_reclamacao_corresponde_ao_da_compra,
  CAST(processo_e_high_risk_confirmado_pelo_pf AS STRING) AS processo_e_high_risk_confirmado_pelo_pf,
  CAST(processo_cust_id_autor AS STRING) AS processo_cust_id_autor,
  CAST(processo_id_da_operacao_mp AS STRING) AS processo_id_da_operacao_mp,
  CAST(processo_id_do_anuncio AS STRING) AS processo_id_do_anuncio,
  CAST(parte_contraria_nome AS STRING) AS parte_contraria_nome,
  CAST(parte_contraria_cpf_cnpj AS STRING) AS parte_contraria_cpf_cnpj,
  CAST(numero_do_processo AS STRING) AS numero_do_processo,
  CAST(processo_id AS STRING) AS processo_id,
  CAST(area_do_direito AS STRING) AS area_do_direito,
  CAST(sub_area_do_direito AS STRING) AS sub_area_do_direito,
  CAST(status AS STRING) AS status,
  CAST(valor_da_causa AS STRING) AS valor_da_causa,
  CAST(data_registrado AS STRING) AS data_registrado,
  CAST(processo_o_objeto_da_reclamacao_e_pdd_on_ou_pnr_on AS STRING) AS processo_o_objeto_da_reclamacao_e_pdd_on_ou_pnr_on,
  CAST(processo_fase_estado_fase AS STRING) AS processo_fase_estado_fase,
  CAST(processo_fase_estado_estado AS STRING) AS processo_fase_estado_estado,
  CAST(processo_probabilidade_de_ganhar_ou_perder_probabilidade AS STRING) AS processo_probabilidade_de_ganhar_ou_perder_probabilidade,
  CURRENT_DATETIME() AS AUD_INS_DTTM,
  CURRENT_DATETIME() AS AUD_UPD_DTTM
FROM `<ENV>.STG.STG_INPUT_DATABASE_ELAW_AMELIA_FINAL`;



-- ============================================================
-- EXTRACAO_MULTAS
-- ============================================================
CREATE OR REPLACE TABLE `<ENV>.STG.STG_INPUT_DATABASE_ELAW_EXTRACAO_MULTAS_FINAL` AS
SELECT
  CAST(processo_id AS STRING) AS processo_id,
  CAST(data AS STRING) AS data,
  CAST(tipo AS STRING) AS tipo,
  CAST(data_registrado AS STRING) AS data_registrado
FROM `<ENV>.STG.Database_eLAW_Extracao_multas_FINAL`;



-- ============================================================
-- OBRIGACOES_DE_FAZER
-- ============================================================
CREATE OR REPLACE TABLE `<ENV>.STG.STG_INPUT_DATABASE_ELAW_OBRIGACOES_DE_FAZER_FINAL` AS
SELECT
  CAST(processo_id AS STRING) AS processo_id,
  CAST(processo_qual_a_solicitacao_da_obf AS STRING) AS processo_qual_a_solicitacao_da_obf,
  CAST(processo_cust_id_autor AS STRING) AS processo_cust_id_autor,
  CAST(processo_e_mail_do_usuario AS STRING) AS processo_e_mail_do_usuario,
  CAST(processo_adicionar_periodo_de_referencia AS STRING) AS processo_adicionar_periodo_de_referencia,
  CAST(processo_adicionar_periodo_de_referencia_grupo AS STRING) AS processo_adicionar_periodo_de_referencia_grupo,
  CAST(processo_tem_multa_fixada AS STRING) AS processo_tem_multa_fixada,
  CAST(processo_tem_multa_fixada_grupo AS STRING) AS processo_tem_multa_fixada_grupo,
  CAST(processo_prazo_para_cumprimento AS STRING) AS processo_prazo_para_cumprimento,
  CAST(processo_tipo_de_decisao AS STRING) AS processo_tipo_de_decisao,
  CAST(processo_tipo_de_decisao_grupo AS STRING) AS processo_tipo_de_decisao_grupo,
  CAST(processo_cpf AS STRING) AS processo_cpf,
  CAST(processo_id_da_operacao_mp AS STRING) AS processo_id_da_operacao_mp,
  CAST(processo_id_da_venda AS STRING) AS processo_id_da_venda,
  CAST(processo_id_do_anuncio AS STRING) AS processo_id_do_anuncio,
  CAST(processo_chave_pix AS STRING) AS processo_chave_pix,
  CAST(data_registrado AS STRING) AS data_registrado,
  CAST(area_do_direito AS STRING) AS area_do_direito,
  CAST(sub_area_do_direito AS STRING) AS sub_area_do_direito,
  CAST(data_de_confirmacao AS STRING) AS data_de_confirmacao,
  CAST(fase_de_workflow AS STRING) AS fase_de_workflow,
  CAST(id AS STRING) AS id,
  CAST(workflow AS STRING) AS workflow,
  CAST(objeto AS STRING) AS objeto,
  CAST(descricao_evento_concluido AS STRING) AS descricao_evento_concluido
FROM `<ENV>.STG.STG_INPUT_DATABASE_ELAW_OBRIGACOES_DE_FAZER`;

















-- ============================================================
-- ELAW_CONTENCIOSO_BRASIL_ONGOING
-- ============================================================
CREATE OR REPLACE TABLE `<ENV>.STG.STG_INPUT_DATABASE_ELAW_CONTENCIOSO_BRASIL_ONGOING_FINAL` AS
SELECT
  CAST(data_de_citacao AS STRING) AS data_de_citacao,
  CAST(processo_id AS STRING) AS processo_id,
  CAST(pasta AS STRING) AS pasta,
  CAST(pais AS STRING) AS pais,
  CAST(numero_do_processo AS STRING) AS numero_do_processo,
  CAST(outros_numeros AS STRING) AS outros_numeros,
  CAST(status AS STRING) AS status,
  CAST(area_do_direito AS STRING) AS area_do_direito,
  CAST(sub_area_do_direito AS STRING) AS sub_area_do_direito,
  CAST(cliente AS STRING) AS cliente,
  CAST(parte_contraria_nome AS STRING) AS parte_contraria_nome,
  CAST(cust_id_autor AS STRING) AS cust_id_autor,
  CAST(outras_partes_nao_clientes AS STRING) AS outras_partes_nao_clientes,
  CAST(page_report_escritorioresponsavel AS STRING) AS page_report_escritorioresponsavel,
  CAST(data_audiencia_inicial AS STRING) AS data_audiencia_inicial,
  CAST(advogado_responsavel AS STRING) AS advogado_responsavel,
  CAST(processo_estado AS STRING) AS processo_estado,
  CAST(processo_comarca AS STRING) AS processo_comarca,
  CAST(processo_foro_tribunal_orgao AS STRING) AS processo_foro_tribunal_orgao,
  CAST(processo_vara_orgao AS STRING) AS processo_vara_orgao,
  CAST(acao AS STRING) AS acao,
  CAST(objeto AS STRING) AS objeto,
  CAST(objeto_1 AS STRING) AS objeto_1,
  CAST(detalhamento_do_objeto AS STRING) AS detalhamento_do_objeto,
  CAST(distribuicao AS STRING) AS distribuicao,
  CAST(tipo_de_contingencia AS STRING) AS tipo_de_contingencia,
  CAST(risco AS STRING) AS risco,
  CAST(observacao AS STRING) AS observacao,
  CAST(tipo_da_audiencia_inicial AS STRING) AS tipo_da_audiencia_inicial,
  CAST(valor_da_causa AS STRING) AS valor_da_causa,
  CAST(outros_clientes_reu AS STRING) AS outros_clientes_reu,
  CAST(modalidade AS STRING) AS modalidade,
  CAST(data_registrado AS STRING) AS data_registrado,
  CAST(cpf_cnpj AS STRING) AS cpf_cnpj,
  CAST(parte_contraria_cpf AS STRING) AS parte_contraria_cpf,
  CAST(data_de_encerramento AS STRING) AS data_de_encerramento,
  CAST(data_de_registro_do_encerramento AS STRING) AS data_de_registro_do_encerramento,
  CAST(data_do_envio_ao_escritorio AS STRING) AS data_do_envio_ao_escritorio,
  CAST(procedimento_judicial AS STRING) AS procedimento_judicial,
  CAST(resumo_do_subsidio AS STRING) AS resumo_do_subsidio,
  CAST(advogado_da_parte_contraria_nome AS STRING) AS advogado_da_parte_contraria_nome,
  CAST(advogados_participantes AS STRING) AS advogados_participantes,
  CAST(advogado_da_parte_contraria_cpf AS STRING) AS advogado_da_parte_contraria_cpf,
  CAST(cust_id_contraparte AS STRING) AS cust_id_contraparte,
  CAST(id_mediacao AS STRING) AS id_mediacao,
  CAST(centro_custo_nome AS STRING) AS centro_custo_nome,
  CAST(centro_de_custo_codigo AS STRING) AS centro_de_custo_codigo,
  CAST(valor_do_risco AS STRING) AS valor_do_risco,
  CAST(comportamento_do_usuario_cx AS STRING) AS comportamento_do_usuario_cx,
  CAST(id_do_pagamento AS STRING) AS id_do_pagamento,
  CAST(fase_estado AS STRING) AS fase_estado,
  CAST(fase_estado_4 AS STRING) AS fase_estado_4,
  CAST(parte_contraria_contumaz AS STRING) AS parte_contraria_contumaz,
  CAST(advogado_parte_contraria_contumaz AS STRING) AS advogado_parte_contraria_contumaz,
  CAST(usuario AS STRING) AS usuario,
  CAST(audiencia_pendente_data AS STRING) AS audiencia_pendente_data,
  CAST(motivo_de_encerramento AS STRING) AS motivo_de_encerramento,
  CAST(caratula AS STRING) AS caratula,
  CAST(indica_menoridade AS STRING) AS indica_menoridade,
  CAST(processo_classificacao AS STRING) AS processo_classificacao,
  CAST(invoca_hipervulnerabilidad AS STRING) AS invoca_hipervulnerabilidad,
  CAST(causas_raizes AS STRING) AS causas_raizes,
  CAST(causas_raizes_1 AS STRING) AS causas_raizes_1,
  CAST(causas_raizes_2 AS STRING) AS causas_raizes_2,
  CAST(id_de_salesforce AS STRING) AS id_de_salesforce,
  CAST(modelo_de_contratacao AS STRING) AS modelo_de_contratacao,
  CAST(numero_de_envio AS STRING) AS numero_de_envio,
  CAST(usuario_reclamou_a_cx AS STRING) AS usuario_reclamou_a_cx,
  CAST(proceso_critico AS STRING) AS proceso_critico,
  CAST(cbt AS STRING) AS cbt,
  CAST(unidade_de_negocio_impactada AS STRING) AS unidade_de_negocio_impactada,
  CAST(campos_de_alteracao_de_valor_identificacao_do_pagamento AS STRING) AS campos_de_alteracao_de_valor_identificacao_do_pagamento,
  CAST(processo_cust_id_contraparte AS STRING) AS processo_cust_id_contraparte,
  CAST(processo_identificacao_do_pagamento AS STRING) AS processo_identificacao_do_pagamento,
  CAST(valor_1_instancia AS STRING) AS valor_1_instancia,
  CAST(informacoes_complementares_cust_id_contraparte AS STRING) AS informacoes_complementares_cust_id_contraparte,
  CAST(processo_cust_id_contraparte_1 AS STRING) AS processo_cust_id_contraparte_1,
  CAST(processo_apelido_contraparte AS STRING) AS processo_apelido_contraparte,
  CAST(empresa_responsavel AS STRING) AS empresa_responsavel,
  CAST(processo_identificacao_do_pagamento_1 AS STRING) AS processo_identificacao_do_pagamento_1,
  CAST(processo_empresa_demandada AS STRING) AS processo_empresa_demandada,
  CAST(hisp_subsidios_id_da_operacao_mp AS STRING) AS hisp_subsidios_id_da_operacao_mp,
  CAST(hisp_subsidios_status_do_pagamento AS STRING) AS hisp_subsidios_status_do_pagamento,
  CAST(hisp_subsidios_cust_id_autor AS STRING) AS hisp_subsidios_cust_id_autor,
  CAST(hisp_subsidios_numero_de_envio AS STRING) AS hisp_subsidios_numero_de_envio,
  CAST(processo_custid_meli AS STRING) AS processo_custid_meli,
  CAST(processo_revisado_por_dre AS STRING) AS processo_revisado_por_dre,
  CAST(processo_escritorio_do_advogado_da_parte_contraria AS STRING) AS processo_escritorio_do_advogado_da_parte_contraria,
  CAST(processo_materia AS STRING) AS processo_materia,
  CAST(justica AS STRING) AS justica,
  CAST(processo_objeto_revisado AS STRING) AS processo_objeto_revisado,
  CAST(processo_revisado_por_dre_1 AS STRING) AS processo_revisado_por_dre_1,
  CAST(forma_de_participacao AS STRING) AS forma_de_participacao,
  CAST(escritorio_externo AS STRING) AS escritorio_externo,
  CAST(pedido AS STRING) AS pedido,
  CAST(processo_apresentada_resposta_negativa AS STRING) AS processo_apresentada_resposta_negativa,
  CAST(data_de_reativacao AS STRING) AS data_de_reativacao,
  CAST(motivo_de_reativacao AS STRING) AS motivo_de_reativacao,
  CAST(acao_1 AS STRING) AS acao_1,
  CAST(valor_objeto AS STRING) AS valor_objeto,
  CAST(processo_condenacao_em_ma_fe AS STRING) AS processo_condenacao_em_ma_fe,
  CAST(processo_valor_associado_a_ma_fe AS STRING) AS processo_valor_associado_a_ma_fe,
  CAST(processo_data_denuncia AS STRING) AS processo_data_denuncia,
  CAST(processo_data_do_protocolo AS STRING) AS processo_data_do_protocolo,
  CAST(processo_data_instauracao AS STRING) AS processo_data_instauracao,
  CAST(processo_estado_da_denuncia AS STRING) AS processo_estado_da_denuncia,
  CAST(processo_tipo_de_operacao AS STRING) AS processo_tipo_de_operacao,
  CAST(processo_data_da_operacao AS STRING) AS processo_data_da_operacao,
  CAST(processo_crime AS STRING) AS processo_crime,
  CAST(processo_crime_2 AS STRING) AS processo_crime_2,
  CAST(processo_prazo AS STRING) AS processo_prazo,
  CAST(advogado_escritorio AS STRING) AS advogado_escritorio,
  CAST(processo_estado_de_la_denuncia AS STRING) AS processo_estado_de_la_denuncia,
  CAST(decisao_analise_de_responsabilidade AS STRING) AS decisao_analise_de_responsabilidade,
  CAST(processo_superendividamento AS STRING) AS processo_superendividamento
FROM
  `<ENV>.STG.STG_INPUT_DATABASE_ELAW_CONTENCIOSO_BRASIL_ONGOING`;


-- ============================================================
-- ELAW_CONTENCIOSO_HISPANOS_ONGOING
-- ============================================================
CREATE OR REPLACE TABLE `<ENV>.STG.STG_INPUT_DATABASE_ELAW_CONTENCIOSO_HISPANOS_ONGOING_FINAL` AS
SELECT
  CAST(data_de_citacao AS STRING) AS data_de_citacao,
  CAST(processo_id AS STRING) AS processo_id,
  CAST(pasta AS STRING) AS pasta,
  CAST(pais AS STRING) AS pais,
  CAST(numero_do_processo AS STRING) AS numero_do_processo,
  CAST(outros_numeros AS STRING) AS outros_numeros,
  CAST(status AS STRING) AS status,
  CAST(area_do_direito AS STRING) AS area_do_direito,
  CAST(sub_area_do_direito AS STRING) AS sub_area_do_direito,
  CAST(cliente AS STRING) AS cliente,
  CAST(parte_contraria_nome AS STRING) AS parte_contraria_nome,
  CAST(cust_id_autor AS STRING) AS cust_id_autor,
  CAST(outras_partes_nao_clientes AS STRING) AS outras_partes_nao_clientes,
  CAST(page_report_escritorioresponsavel AS STRING) AS page_report_escritorioresponsavel,
  CAST(data_audiencia_inicial AS STRING) AS data_audiencia_inicial,
  CAST(advogado_responsavel AS STRING) AS advogado_responsavel,
  CAST(processo_estado AS STRING) AS processo_estado,
  CAST(processo_comarca AS STRING) AS processo_comarca,
  CAST(processo_foro_tribunal_orgao AS STRING) AS processo_foro_tribunal_orgao,
  CAST(processo_vara_orgao AS STRING) AS processo_vara_orgao,
  CAST(acao AS STRING) AS acao,
  CAST(objeto AS STRING) AS objeto,
  CAST(objeto_1 AS STRING) AS objeto_1,
  CAST(detalhamento_do_objeto AS STRING) AS detalhamento_do_objeto,
  CAST(distribuicao AS STRING) AS distribuicao,
  CAST(tipo_de_contingencia AS STRING) AS tipo_de_contingencia,
  CAST(risco AS STRING) AS risco,
  CAST(observacao AS STRING) AS observacao,
  CAST(tipo_da_audiencia_inicial AS STRING) AS tipo_da_audiencia_inicial,
  CAST(valor_da_causa AS STRING) AS valor_da_causa,
  CAST(outros_clientes_reu AS STRING) AS outros_clientes_reu,
  CAST(modalidade AS STRING) AS modalidade,
  CAST(data_registrado AS STRING) AS data_registrado,
  CAST(cpf_cnpj AS STRING) AS cpf_cnpj,
  CAST(parte_contraria_cpf AS STRING) AS parte_contraria_cpf,
  CAST(data_de_encerramento AS STRING) AS data_de_encerramento,
  CAST(data_de_registro_do_encerramento AS STRING) AS data_de_registro_do_encerramento,
  CAST(data_do_envio_ao_escritorio AS STRING) AS data_do_envio_ao_escritorio,
  CAST(procedimento_judicial AS STRING) AS procedimento_judicial,
  CAST(resumo_do_subsidio AS STRING) AS resumo_do_subsidio,
  CAST(advogado_da_parte_contraria_nome AS STRING) AS advogado_da_parte_contraria_nome,
  CAST(advogados_participantes AS STRING) AS advogados_participantes,
  CAST(advogado_da_parte_contraria_cpf AS STRING) AS advogado_da_parte_contraria_cpf,
  CAST(cust_id_contraparte AS STRING) AS cust_id_contraparte,
  CAST(id_mediacao AS STRING) AS id_mediacao,
  CAST(centro_custo_nome AS STRING) AS centro_custo_nome,
  CAST(centro_de_custo_codigo AS STRING) AS centro_de_custo_codigo,
  CAST(valor_do_risco AS STRING) AS valor_do_risco,
  CAST(comportamento_do_usuario_cx AS STRING) AS comportamento_do_usuario_cx,
  CAST(id_do_pagamento AS STRING) AS id_do_pagamento,
  CAST(fase_estado AS STRING) AS fase_estado,
  CAST(fase_estado_4 AS STRING) AS fase_estado_4,
  CAST(parte_contraria_contumaz AS STRING) AS parte_contraria_contumaz,
  CAST(advogado_parte_contraria_contumaz AS STRING) AS advogado_parte_contraria_contumaz,
  CAST(usuario AS STRING) AS usuario,
  CAST(audiencia_pendente_data AS STRING) AS audiencia_pendente_data,
  CAST(motivo_de_encerramento AS STRING) AS motivo_de_encerramento,
  CAST(caratula AS STRING) AS caratula,
  CAST(indica_menoridade AS STRING) AS indica_menoridade,
  CAST(processo_classificacao AS STRING) AS processo_classificacao,
  CAST(invoca_hipervulnerabilidad AS STRING) AS invoca_hipervulnerabilidad,
  CAST(causas_raizes AS STRING) AS causas_raizes,
  CAST(causas_raizes_1 AS STRING) AS causas_raizes_1,
  CAST(causas_raizes_2 AS STRING) AS causas_raizes_2,
  CAST(id_de_salesforce AS STRING) AS id_de_salesforce,
  CAST(modelo_de_contratacao AS STRING) AS modelo_de_contratacao,
  CAST(numero_de_envio AS STRING) AS numero_de_envio,
  CAST(usuario_reclamou_a_cx AS STRING) AS usuario_reclamou_a_cx,
  CAST(proceso_critico AS STRING) AS proceso_critico,
  CAST(cbt AS STRING) AS cbt,
  CAST(unidade_de_negocio_impactada AS STRING) AS unidade_de_negocio_impactada,
  CAST(campos_de_alteracao_de_valor_identificacao_do_pagamento AS STRING) AS campos_de_alteracao_de_valor_identificacao_do_pagamento,
  CAST(processo_cust_id_contraparte AS STRING) AS processo_cust_id_contraparte,
  CAST(processo_identificacao_do_pagamento AS STRING) AS processo_identificacao_do_pagamento,
  CAST(valor_1_instancia AS STRING) AS valor_1_instancia,
  CAST(informacoes_complementares_cust_id_contraparte AS STRING) AS informacoes_complementares_cust_id_contraparte,
  CAST(processo_cust_id_contraparte_1 AS STRING) AS processo_cust_id_contraparte_1,
  CAST(processo_apelido_contraparte AS STRING) AS processo_apelido_contraparte,
  CAST(empresa_responsavel AS STRING) AS empresa_responsavel,
  CAST(processo_identificacao_do_pagamento_1 AS STRING) AS processo_identificacao_do_pagamento_1,
  CAST(processo_empresa_demandada AS STRING) AS processo_empresa_demandada,
  CAST(hisp_subsidios_id_da_operacao_mp AS STRING) AS hisp_subsidios_id_da_operacao_mp,
  CAST(hisp_subsidios_status_do_pagamento AS STRING) AS hisp_subsidios_status_do_pagamento,
  CAST(hisp_subsidios_cust_id_autor AS STRING) AS hisp_subsidios_cust_id_autor,
  CAST(hisp_subsidios_numero_de_envio AS STRING) AS hisp_subsidios_numero_de_envio,
  CAST(processo_custid_meli AS STRING) AS processo_custid_meli,
  CAST(processo_revisado_por_dre AS STRING) AS processo_revisado_por_dre,
  CAST(processo_escritorio_do_advogado_da_parte_contraria AS STRING) AS processo_escritorio_do_advogado_da_parte_contraria,
  CAST(processo_materia AS STRING) AS processo_materia,
  CAST(justica AS STRING) AS justica,
  CAST(processo_objeto_revisado AS STRING) AS processo_objeto_revisado,
  CAST(processo_revisado_por_dre_1 AS STRING) AS processo_revisado_por_dre_1,
  CAST(forma_de_participacao AS STRING) AS forma_de_participacao,
  CAST(escritorio_externo AS STRING) AS escritorio_externo,
  CAST(pedido AS STRING) AS pedido,
  CAST(processo_apresentada_resposta_negativa AS STRING) AS processo_apresentada_resposta_negativa,
  CAST(data_de_reativacao AS STRING) AS data_de_reativacao,
  CAST(motivo_de_reativacao AS STRING) AS motivo_de_reativacao,
  CAST(acao_1 AS STRING) AS acao_1,
  CAST(valor_objeto AS STRING) AS valor_objeto,
  CAST(processo_condenacao_em_ma_fe AS STRING) AS processo_condenacao_em_ma_fe,
  CAST(processo_valor_associado_a_ma_fe AS STRING) AS processo_valor_associado_a_ma_fe,
  CAST(processo_data_denuncia AS STRING) AS processo_data_denuncia,
  CAST(processo_data_do_protocolo AS STRING) AS processo_data_do_protocolo,
  CAST(processo_data_instauracao AS STRING) AS processo_data_instauracao,
  CAST(processo_estado_da_denuncia AS STRING) AS processo_estado_da_denuncia,
  CAST(processo_tipo_de_operacao AS STRING) AS processo_tipo_de_operacao,
  CAST(processo_data_da_operacao AS STRING) AS processo_data_da_operacao,
  CAST(processo_crime AS STRING) AS processo_crime,
  CAST(processo_crime_2 AS STRING) AS processo_crime_2,
  CAST(processo_prazo AS STRING) AS processo_prazo,
  CAST(advogado_escritorio AS STRING) AS advogado_escritorio,
  CAST(processo_estado_de_la_denuncia AS STRING) AS processo_estado_de_la_denuncia,
  CAST(decisao_analise_de_responsabilidade AS STRING) AS decisao_analise_de_responsabilidade,
  CAST(processo_superendividamento AS STRING) AS processo_superendividamento
FROM
  `<ENV>.STG.STG_INPUT_DATABASE_ELAW_CONTENCIOSO_HISPANOS_ONGOING`;



-- ============================================================
-- ELAW_CONTENCIOSO_BRASIL_OUTGOING
-- ============================================================
CREATE OR REPLACE TABLE `<ENV>.STG.STG_INPUT_DATABASE_ELAW_CONTENCIOSO_BRASIL_OUTGOING_FINAL` AS
SELECT
  CAST(data_de_citacao AS STRING) AS data_de_citacao,
  CAST(processo_id AS STRING) AS processo_id,
  CAST(pasta AS STRING) AS pasta,
  CAST(pais AS STRING) AS pais,
  CAST(numero_do_processo AS STRING) AS numero_do_processo,
  CAST(outros_numeros AS STRING) AS outros_numeros,
  CAST(status AS STRING) AS status,
  CAST(area_do_direito AS STRING) AS area_do_direito,
  CAST(sub_area_do_direito AS STRING) AS sub_area_do_direito,
  CAST(cliente AS STRING) AS cliente,
  CAST(parte_contraria_nome AS STRING) AS parte_contraria_nome,
  CAST(cust_id_autor AS STRING) AS cust_id_autor,
  CAST(outras_partes_nao_clientes AS STRING) AS outras_partes_nao_clientes,
  CAST(page_report_escritorioresponsavel AS STRING) AS page_report_escritorioresponsavel,
  CAST(data_audiencia_inicial AS STRING) AS data_audiencia_inicial,
  CAST(advogado_responsavel AS STRING) AS advogado_responsavel,
  CAST(processo_estado AS STRING) AS processo_estado,
  CAST(processo_comarca AS STRING) AS processo_comarca,
  CAST(processo_foro_tribunal_orgao AS STRING) AS processo_foro_tribunal_orgao,
  CAST(processo_vara_orgao AS STRING) AS processo_vara_orgao,
  CAST(acao AS STRING) AS acao,
  CAST(objeto AS STRING) AS objeto,
  CAST(objeto_1 AS STRING) AS objeto_1,
  CAST(detalhamento_do_objeto AS STRING) AS detalhamento_do_objeto,
  CAST(distribuicao AS STRING) AS distribuicao,
  CAST(tipo_de_contingencia AS STRING) AS tipo_de_contingencia,
  CAST(risco AS STRING) AS risco,
  CAST(observacao AS STRING) AS observacao,
  CAST(tipo_da_audiencia_inicial AS STRING) AS tipo_da_audiencia_inicial,
  CAST(valor_da_causa AS STRING) AS valor_da_causa,
  CAST(outros_clientes_reu AS STRING) AS outros_clientes_reu,
  CAST(modalidade AS STRING) AS modalidade,
  CAST(data_registrado AS STRING) AS data_registrado,
  CAST(cpf_cnpj AS STRING) AS cpf_cnpj,
  CAST(parte_contraria_cpf AS STRING) AS parte_contraria_cpf,
  CAST(data_de_encerramento AS STRING) AS data_de_encerramento,
  CAST(data_de_registro_do_encerramento AS STRING) AS data_de_registro_do_encerramento,
  CAST(data_do_envio_ao_escritorio AS STRING) AS data_do_envio_ao_escritorio,
  CAST(procedimento_judicial AS STRING) AS procedimento_judicial,
  CAST(resumo_do_subsidio AS STRING) AS resumo_do_subsidio,
  CAST(advogado_da_parte_contraria_nome AS STRING) AS advogado_da_parte_contraria_nome,
  CAST(advogados_participantes AS STRING) AS advogados_participantes,
  CAST(advogado_da_parte_contraria_cpf AS STRING) AS advogado_da_parte_contraria_cpf,
  CAST(cust_id_contraparte AS STRING) AS cust_id_contraparte,
  CAST(id_mediacao AS STRING) AS id_mediacao,
  CAST(centro_custo_nome AS STRING) AS centro_custo_nome,
  CAST(centro_de_custo_codigo AS STRING) AS centro_de_custo_codigo,
  CAST(valor_do_risco AS STRING) AS valor_do_risco,
  CAST(comportamento_do_usuario_cx AS STRING) AS comportamento_do_usuario_cx,
  CAST(id_do_pagamento AS STRING) AS id_do_pagamento,
  CAST(fase_estado AS STRING) AS fase_estado,
  CAST(fase_estado_4 AS STRING) AS fase_estado_4,
  CAST(parte_contraria_contumaz AS STRING) AS parte_contraria_contumaz,
  CAST(advogado_parte_contraria_contumaz AS STRING) AS advogado_parte_contraria_contumaz,
  CAST(usuario AS STRING) AS usuario,
  CAST(audiencia_pendente_data AS STRING) AS audiencia_pendente_data,
  CAST(motivo_de_encerramento AS STRING) AS motivo_de_encerramento,
  CAST(caratula AS STRING) AS caratula,
  CAST(indica_menoridade AS STRING) AS indica_menoridade,
  CAST(processo_classificacao AS STRING) AS processo_classificacao,
  CAST(invoca_hipervulnerabilidad AS STRING) AS invoca_hipervulnerabilidad,
  CAST(causas_raizes AS STRING) AS causas_raizes,
  CAST(causas_raizes_1 AS STRING) AS causas_raizes_1,
  CAST(causas_raizes_2 AS STRING) AS causas_raizes_2,
  CAST(id_de_salesforce AS STRING) AS id_de_salesforce,
  CAST(modelo_de_contratacao AS STRING) AS modelo_de_contratacao,
  CAST(numero_de_envio AS STRING) AS numero_de_envio,
  CAST(usuario_reclamou_a_cx AS STRING) AS usuario_reclamou_a_cx,
  CAST(proceso_critico AS STRING) AS proceso_critico,
  CAST(cbt AS STRING) AS cbt,
  CAST(unidade_de_negocio_impactada AS STRING) AS unidade_de_negocio_impactada,
  CAST(campos_de_alteracao_de_valor_identificacao_do_pagamento AS STRING) AS campos_de_alteracao_de_valor_identificacao_do_pagamento,
  CAST(processo_cust_id_contraparte AS STRING) AS processo_cust_id_contraparte,
  CAST(processo_identificacao_do_pagamento AS STRING) AS processo_identificacao_do_pagamento,
  CAST(valor_1_instancia AS STRING) AS valor_1_instancia,
  CAST(informacoes_complementares_cust_id_contraparte AS STRING) AS informacoes_complementares_cust_id_contraparte,
  CAST(processo_cust_id_contraparte_1 AS STRING) AS processo_cust_id_contraparte_1,
  CAST(processo_apelido_contraparte AS STRING) AS processo_apelido_contraparte,
  CAST(empresa_responsavel AS STRING) AS empresa_responsavel,
  CAST(processo_identificacao_do_pagamento_1 AS STRING) AS processo_identificacao_do_pagamento_1,
  CAST(processo_empresa_demandada AS STRING) AS processo_empresa_demandada,
  CAST(hisp_subsidios_id_da_operacao_mp AS STRING) AS hisp_subsidios_id_da_operacao_mp,
  CAST(hisp_subsidios_status_do_pagamento AS STRING) AS hisp_subsidios_status_do_pagamento,
  CAST(hisp_subsidios_cust_id_autor AS STRING) AS hisp_subsidios_cust_id_autor,
  CAST(hisp_subsidios_numero_de_envio AS STRING) AS hisp_subsidios_numero_de_envio,
  CAST(processo_custid_meli AS STRING) AS processo_custid_meli,
  CAST(processo_revisado_por_dre AS STRING) AS processo_revisado_por_dre,
  CAST(processo_escritorio_do_advogado_da_parte_contraria AS STRING) AS processo_escritorio_do_advogado_da_parte_contraria,
  CAST(processo_materia AS STRING) AS processo_materia,
  CAST(justica AS STRING) AS justica,
  CAST(processo_objeto_revisado AS STRING) AS processo_objeto_revisado,
  CAST(processo_revisado_por_dre_1 AS STRING) AS processo_revisado_por_dre_1,
  CAST(forma_de_participacao AS STRING) AS forma_de_participacao,
  CAST(escritorio_externo AS STRING) AS escritorio_externo,
  CAST(pedido AS STRING) AS pedido,
  CAST(processo_apresentada_resposta_negativa AS STRING) AS processo_apresentada_resposta_negativa,
  CAST(data_de_reativacao AS STRING) AS data_de_reativacao,
  CAST(motivo_de_reativacao AS STRING) AS motivo_de_reativacao,
  CAST(acao_1 AS STRING) AS acao_1,
  CAST(valor_objeto AS STRING) AS valor_objeto,
  CAST(processo_condenacao_em_ma_fe AS STRING) AS processo_condenacao_em_ma_fe,
  CAST(processo_valor_associado_a_ma_fe AS STRING) AS processo_valor_associado_a_ma_fe,
  CAST(processo_data_denuncia AS STRING) AS processo_data_denuncia,
  CAST(processo_data_do_protocolo AS STRING) AS processo_data_do_protocolo,
  CAST(processo_data_instauracao AS STRING) AS processo_data_instauracao,
  CAST(processo_estado_da_denuncia AS STRING) AS processo_estado_da_denuncia,
  CAST(processo_tipo_de_operacao AS STRING) AS processo_tipo_de_operacao,
  CAST(processo_data_da_operacao AS STRING) AS processo_data_da_operacao,
  CAST(processo_crime AS STRING) AS processo_crime,
  CAST(processo_crime_2 AS STRING) AS processo_crime_2,
  CAST(processo_prazo AS STRING) AS processo_prazo,
  CAST(advogado_escritorio AS STRING) AS advogado_escritorio,
  CAST(processo_estado_de_la_denuncia AS STRING) AS processo_estado_de_la_denuncia,
  CAST(decisao_analise_de_responsabilidade AS STRING) AS decisao_analise_de_responsabilidade,
  CAST(processo_superendividamento AS STRING) AS processo_superendividamento
FROM
  `<ENV>.STG.STG_INPUT_DATABASE_ELAW_CONTENCIOSO_BRASIL_OUTGOING_FINAL`;


-- ============================================================
-- ELAW_CONTENCIOSO_HISPANOS_OUTGOING
-- ============================================================
CREATE OR REPLACE TABLE `<ENV>.STG.STG_INPUT_DATABASE_ELAW_CONTENCIOSO_HISPANOS_OUTGOING_FINAL` AS
SELECT
  CAST(data_de_citacao AS STRING) AS data_de_citacao,
  CAST(processo_id AS STRING) AS processo_id,
  CAST(pasta AS STRING) AS pasta,
  CAST(pais AS STRING) AS pais,
  CAST(numero_do_processo AS STRING) AS numero_do_processo,
  CAST(outros_numeros AS STRING) AS outros_numeros,
  CAST(status AS STRING) AS status,
  CAST(area_do_direito AS STRING) AS area_do_direito,
  CAST(sub_area_do_direito AS STRING) AS sub_area_do_direito,
  CAST(cliente AS STRING) AS cliente,
  CAST(parte_contraria_nome AS STRING) AS parte_contraria_nome,
  CAST(cust_id_autor AS STRING) AS cust_id_autor,
  CAST(outras_partes_nao_clientes AS STRING) AS outras_partes_nao_clientes,
  CAST(page_report_escritorioresponsavel AS STRING) AS page_report_escritorioresponsavel,
  CAST(data_audiencia_inicial AS STRING) AS data_audiencia_inicial,
  CAST(advogado_responsavel AS STRING) AS advogado_responsavel,
  CAST(processo_estado AS STRING) AS processo_estado,
  CAST(processo_comarca AS STRING) AS processo_comarca,
  CAST(processo_foro_tribunal_orgao AS STRING) AS processo_foro_tribunal_orgao,
  CAST(processo_vara_orgao AS STRING) AS processo_vara_orgao,
  CAST(acao AS STRING) AS acao,
  CAST(objeto AS STRING) AS objeto,
  CAST(objeto_1 AS STRING) AS objeto_1,
  CAST(detalhamento_do_objeto AS STRING) AS detalhamento_do_objeto,
  CAST(distribuicao AS STRING) AS distribuicao,
  CAST(tipo_de_contingencia AS STRING) AS tipo_de_contingencia,
  CAST(risco AS STRING) AS risco,
  CAST(observacao AS STRING) AS observacao,
  CAST(tipo_da_audiencia_inicial AS STRING) AS tipo_da_audiencia_inicial,
  CAST(valor_da_causa AS STRING) AS valor_da_causa,
  CAST(outros_clientes_reu AS STRING) AS outros_clientes_reu,
  CAST(modalidade AS STRING) AS modalidade,
  CAST(data_registrado AS STRING) AS data_registrado,
  CAST(cpf_cnpj AS STRING) AS cpf_cnpj,
  CAST(parte_contraria_cpf AS STRING) AS parte_contraria_cpf,
  CAST(data_de_encerramento AS STRING) AS data_de_encerramento,
  CAST(data_de_registro_do_encerramento AS STRING) AS data_de_registro_do_encerramento,
  CAST(data_do_envio_ao_escritorio AS STRING) AS data_do_envio_ao_escritorio,
  CAST(procedimento_judicial AS STRING) AS procedimento_judicial,
  CAST(resumo_do_subsidio AS STRING) AS resumo_do_subsidio,
  CAST(advogado_da_parte_contraria_nome AS STRING) AS advogado_da_parte_contraria_nome,
  CAST(advogados_participantes AS STRING) AS advogados_participantes,
  CAST(advogado_da_parte_contraria_cpf AS STRING) AS advogado_da_parte_contraria_cpf,
  CAST(cust_id_contraparte AS STRING) AS cust_id_contraparte,
  CAST(id_mediacao AS STRING) AS id_mediacao,
  CAST(centro_custo_nome AS STRING) AS centro_custo_nome,
  CAST(centro_de_custo_codigo AS STRING) AS centro_de_custo_codigo,
  CAST(valor_do_risco AS STRING) AS valor_do_risco,
  CAST(comportamento_do_usuario_cx AS STRING) AS comportamento_do_usuario_cx,
  CAST(id_do_pagamento AS STRING) AS id_do_pagamento,
  CAST(fase_estado AS STRING) AS fase_estado,
  CAST(fase_estado_4 AS STRING) AS fase_estado_4,
  CAST(parte_contraria_contumaz AS STRING) AS parte_contraria_contumaz,
  CAST(advogado_parte_contraria_contumaz AS STRING) AS advogado_parte_contraria_contumaz,
  CAST(usuario AS STRING) AS usuario,
  CAST(audiencia_pendente_data AS STRING) AS audiencia_pendente_data,
  CAST(motivo_de_encerramento AS STRING) AS motivo_de_encerramento,
  CAST(caratula AS STRING) AS caratula,
  CAST(indica_menoridade AS STRING) AS indica_menoridade,
  CAST(processo_classificacao AS STRING) AS processo_classificacao,
  CAST(invoca_hipervulnerabilidad AS STRING) AS invoca_hipervulnerabilidad,
  CAST(causas_raizes AS STRING) AS causas_raizes,
  CAST(causas_raizes_1 AS STRING) AS causas_raizes_1,
  CAST(causas_raizes_2 AS STRING) AS causas_raizes_2,
  CAST(id_de_salesforce AS STRING) AS id_de_salesforce,
  CAST(modelo_de_contratacao AS STRING) AS modelo_de_contratacao,
  CAST(numero_de_envio AS STRING) AS numero_de_envio,
  CAST(usuario_reclamou_a_cx AS STRING) AS usuario_reclamou_a_cx,
  CAST(proceso_critico AS STRING) AS proceso_critico,
  CAST(cbt AS STRING) AS cbt,
  CAST(unidade_de_negocio_impactada AS STRING) AS unidade_de_negocio_impactada,
  CAST(campos_de_alteracao_de_valor_identificacao_do_pagamento AS STRING) AS campos_de_alteracao_de_valor_identificacao_do_pagamento,
  CAST(processo_cust_id_contraparte AS STRING) AS processo_cust_id_contraparte,
  CAST(processo_identificacao_do_pagamento AS STRING) AS processo_identificacao_do_pagamento,
  CAST(valor_1_instancia AS STRING) AS valor_1_instancia,
  CAST(informacoes_complementares_cust_id_contraparte AS STRING) AS informacoes_complementares_cust_id_contraparte,
  CAST(processo_cust_id_contraparte_1 AS STRING) AS processo_cust_id_contraparte_1,
  CAST(processo_apelido_contraparte AS STRING) AS processo_apelido_contraparte,
  CAST(empresa_responsavel AS STRING) AS empresa_responsavel,
  CAST(processo_identificacao_do_pagamento_1 AS STRING) AS processo_identificacao_do_pagamento_1,
  CAST(processo_empresa_demandada AS STRING) AS processo_empresa_demandada,
  CAST(hisp_subsidios_id_da_operacao_mp AS STRING) AS hisp_subsidios_id_da_operacao_mp,
  CAST(hisp_subsidios_status_do_pagamento AS STRING) AS hisp_subsidios_status_do_pagamento,
  CAST(hisp_subsidios_cust_id_autor AS STRING) AS hisp_subsidios_cust_id_autor,
  CAST(hisp_subsidios_numero_de_envio AS STRING) AS hisp_subsidios_numero_de_envio,
  CAST(processo_custid_meli AS STRING) AS processo_custid_meli,
  CAST(processo_revisado_por_dre AS STRING) AS processo_revisado_por_dre,
  CAST(processo_escritorio_do_advogado_da_parte_contraria AS STRING) AS processo_escritorio_do_advogado_da_parte_contraria,
  CAST(processo_materia AS STRING) AS processo_materia,
  CAST(justica AS STRING) AS justica,
  CAST(processo_objeto_revisado AS STRING) AS processo_objeto_revisado,
  CAST(processo_revisado_por_dre_1 AS STRING) AS processo_revisado_por_dre_1,
  CAST(forma_de_participacao AS STRING) AS forma_de_participacao,
  CAST(escritorio_externo AS STRING) AS escritorio_externo,
  CAST(pedido AS STRING) AS pedido,
  CAST(processo_apresentada_resposta_negativa AS STRING) AS processo_apresentada_resposta_negativa,
  CAST(data_de_reativacao AS STRING) AS data_de_reativacao,
  CAST(motivo_de_reativacao AS STRING) AS motivo_de_reativacao,
  CAST(acao_1 AS STRING) AS acao_1,
  CAST(valor_objeto AS STRING) AS valor_objeto,
  CAST(processo_condenacao_em_ma_fe AS STRING) AS processo_condenacao_em_ma_fe,
  CAST(processo_valor_associado_a_ma_fe AS STRING) AS processo_valor_associado_a_ma_fe,
  CAST(processo_data_denuncia AS STRING) AS processo_data_denuncia,
  CAST(processo_data_do_protocolo AS STRING) AS processo_data_do_protocolo,
  CAST(processo_data_instauracao AS STRING) AS processo_data_instauracao,
  CAST(processo_estado_da_denuncia AS STRING) AS processo_estado_da_denuncia,
  CAST(processo_tipo_de_operacao AS STRING) AS processo_tipo_de_operacao,
  CAST(processo_data_da_operacao AS STRING) AS processo_data_da_operacao,
  CAST(processo_crime AS STRING) AS processo_crime,
  CAST(processo_crime_2 AS STRING) AS processo_crime_2,
  CAST(processo_prazo AS STRING) AS processo_prazo,
  CAST(advogado_escritorio AS STRING) AS advogado_escritorio,
  CAST(processo_estado_de_la_denuncia AS STRING) AS processo_estado_de_la_denuncia,
  CAST(decisao_analise_de_responsabilidade AS STRING) AS decisao_analise_de_responsabilidade,
  CAST(processo_superendividamento AS STRING) AS processo_superendividamento
FROM
  `<ENV>.STG.STG_INPUT_DATABASE_ELAW_CONTENCIOSO_HISPANOS_OUTGOING_FINAL`;


-- ============================================================
-- ELAW_CONTENCIOSO_BRASIL_INCOMING
-- ============================================================
CREATE OR REPLACE TABLE `<ENV>.STG.STG_INPUT_DATABASE_ELAW_CONTENCIOSO_BRASIL_INCOMING_FINAL` AS
SELECT
  CAST(data_de_citacao AS STRING) AS data_de_citacao,
  CAST(processo_id AS STRING) AS processo_id,
  CAST(pasta AS STRING) AS pasta,
  CAST(pais AS STRING) AS pais,
  CAST(numero_do_processo AS STRING) AS numero_do_processo,
  CAST(outros_numeros AS STRING) AS outros_numeros,
  CAST(status AS STRING) AS status,
  CAST(area_do_direito AS STRING) AS area_do_direito,
  CAST(sub_area_do_direito AS STRING) AS sub_area_do_direito,
  CAST(cliente AS STRING) AS cliente,
  CAST(parte_contraria_nome AS STRING) AS parte_contraria_nome,
  CAST(cust_id_autor AS STRING) AS cust_id_autor,
  CAST(outras_partes_nao_clientes AS STRING) AS outras_partes_nao_clientes,
  CAST(page_report_escritorioresponsavel AS STRING) AS page_report_escritorioresponsavel,
  CAST(data_audiencia_inicial AS STRING) AS data_audiencia_inicial,
  CAST(advogado_responsavel AS STRING) AS advogado_responsavel,
  CAST(processo_estado AS STRING) AS processo_estado,
  CAST(processo_comarca AS STRING) AS processo_comarca,
  CAST(processo_foro_tribunal_orgao AS STRING) AS processo_foro_tribunal_orgao,
  CAST(processo_vara_orgao AS STRING) AS processo_vara_orgao,
  CAST(acao AS STRING) AS acao,
  CAST(objeto AS STRING) AS objeto,
  CAST(objeto_1 AS STRING) AS objeto_1,
  CAST(detalhamento_do_objeto AS STRING) AS detalhamento_do_objeto,
  CAST(distribuicao AS STRING) AS distribuicao,
  CAST(tipo_de_contingencia AS STRING) AS tipo_de_contingencia,
  CAST(risco AS STRING) AS risco,
  CAST(observacao AS STRING) AS observacao,
  CAST(tipo_da_audiencia_inicial AS STRING) AS tipo_da_audiencia_inicial,
  CAST(valor_da_causa AS STRING) AS valor_da_causa,
  CAST(outros_clientes_reu AS STRING) AS outros_clientes_reu,
  CAST(modalidade AS STRING) AS modalidade,
  CAST(data_registrado AS STRING) AS data_registrado,
  CAST(cpf_cnpj AS STRING) AS cpf_cnpj,
  CAST(parte_contraria_cpf AS STRING) AS parte_contraria_cpf,
  CAST(data_de_encerramento AS STRING) AS data_de_encerramento,
  CAST(data_de_registro_do_encerramento AS STRING) AS data_de_registro_do_encerramento,
  CAST(data_do_envio_ao_escritorio AS STRING) AS data_do_envio_ao_escritorio,
  CAST(procedimento_judicial AS STRING) AS procedimento_judicial,
  CAST(resumo_do_subsidio AS STRING) AS resumo_do_subsidio,
  CAST(advogado_da_parte_contraria_nome AS STRING) AS advogado_da_parte_contraria_nome,
  CAST(advogados_participantes AS STRING) AS advogados_participantes,
  CAST(advogado_da_parte_contraria_cpf AS STRING) AS advogado_da_parte_contraria_cpf,
  CAST(cust_id_contraparte AS STRING) AS cust_id_contraparte,
  CAST(id_mediacao AS STRING) AS id_mediacao,
  CAST(centro_custo_nome AS STRING) AS centro_custo_nome,
  CAST(centro_de_custo_codigo AS STRING) AS centro_de_custo_codigo,
  CAST(valor_do_risco AS STRING) AS valor_do_risco,
  CAST(comportamento_do_usuario_cx AS STRING) AS comportamento_do_usuario_cx,
  CAST(id_do_pagamento AS STRING) AS id_do_pagamento,
  CAST(fase_estado AS STRING) AS fase_estado,
  CAST(fase_estado_4 AS STRING) AS fase_estado_4,
  CAST(parte_contraria_contumaz AS STRING) AS parte_contraria_contumaz,
  CAST(advogado_parte_contraria_contumaz AS STRING) AS advogado_parte_contraria_contumaz,
  CAST(usuario AS STRING) AS usuario,
  CAST(audiencia_pendente_data AS STRING) AS audiencia_pendente_data,
  CAST(motivo_de_encerramento AS STRING) AS motivo_de_encerramento,
  CAST(caratula AS STRING) AS caratula,
  CAST(indica_menoridade AS STRING) AS indica_menoridade,
  CAST(processo_classificacao AS STRING) AS processo_classificacao,
  CAST(invoca_hipervulnerabilidad AS STRING) AS invoca_hipervulnerabilidad,
  CAST(causas_raizes AS STRING) AS causas_raizes,
  CAST(causas_raizes_1 AS STRING) AS causas_raizes_1,
  CAST(causas_raizes_2 AS STRING) AS causas_raizes_2,
  CAST(id_de_salesforce AS STRING) AS id_de_salesforce,
  CAST(modelo_de_contratacao AS STRING) AS modelo_de_contratacao,
  CAST(numero_de_envio AS STRING) AS numero_de_envio,
  CAST(usuario_reclamou_a_cx AS STRING) AS usuario_reclamou_a_cx,
  CAST(proceso_critico AS STRING) AS proceso_critico,
  CAST(cbt AS STRING) AS cbt,
  CAST(unidade_de_negocio_impactada AS STRING) AS unidade_de_negocio_impactada,
  CAST(campos_de_alteracao_de_valor_identificacao_do_pagamento AS STRING) AS campos_de_alteracao_de_valor_identificacao_do_pagamento,
  CAST(processo_cust_id_contraparte AS STRING) AS processo_cust_id_contraparte,
  CAST(processo_identificacao_do_pagamento AS STRING) AS processo_identificacao_do_pagamento,
  CAST(valor_1_instancia AS STRING) AS valor_1_instancia,
  CAST(informacoes_complementares_cust_id_contraparte AS STRING) AS informacoes_complementares_cust_id_contraparte,
  CAST(processo_cust_id_contraparte_1 AS STRING) AS processo_cust_id_contraparte_1,
  CAST(processo_apelido_contraparte AS STRING) AS processo_apelido_contraparte,
  CAST(empresa_responsavel AS STRING) AS empresa_responsavel,
  CAST(processo_identificacao_do_pagamento_1 AS STRING) AS processo_identificacao_do_pagamento_1,
  CAST(processo_empresa_demandada AS STRING) AS processo_empresa_demandada,
  CAST(hisp_subsidios_id_da_operacao_mp AS STRING) AS hisp_subsidios_id_da_operacao_mp,
  CAST(hisp_subsidios_status_do_pagamento AS STRING) AS hisp_subsidios_status_do_pagamento,
  CAST(hisp_subsidios_cust_id_autor AS STRING) AS hisp_subsidios_cust_id_autor,
  CAST(hisp_subsidios_numero_de_envio AS STRING) AS hisp_subsidios_numero_de_envio,
  CAST(processo_custid_meli AS STRING) AS processo_custid_meli,
  CAST(processo_revisado_por_dre AS STRING) AS processo_revisado_por_dre,
  CAST(processo_escritorio_do_advogado_da_parte_contraria AS STRING) AS processo_escritorio_do_advogado_da_parte_contraria,
  CAST(processo_materia AS STRING) AS processo_materia,
  CAST(justica AS STRING) AS justica,
  CAST(processo_objeto_revisado AS STRING) AS processo_objeto_revisado,
  CAST(processo_revisado_por_dre_1 AS STRING) AS processo_revisado_por_dre_1,
  CAST(forma_de_participacao AS STRING) AS forma_de_participacao,
  CAST(escritorio_externo AS STRING) AS escritorio_externo,
  CAST(pedido AS STRING) AS pedido,
  CAST(processo_apresentada_resposta_negativa AS STRING) AS processo_apresentada_resposta_negativa,
  CAST(data_de_reativacao AS STRING) AS data_de_reativacao,
  CAST(motivo_de_reativacao AS STRING) AS motivo_de_reativacao,
  CAST(acao_1 AS STRING) AS acao_1,
  CAST(valor_objeto AS STRING) AS valor_objeto,
  CAST(processo_condenacao_em_ma_fe AS STRING) AS processo_condenacao_em_ma_fe,
  CAST(processo_valor_associado_a_ma_fe AS STRING) AS processo_valor_associado_a_ma_fe,
  CAST(processo_data_denuncia AS STRING) AS processo_data_denuncia,
  CAST(processo_data_do_protocolo AS STRING) AS processo_data_do_protocolo,
  CAST(processo_data_instauracao AS STRING) AS processo_data_instauracao,
  CAST(processo_estado_da_denuncia AS STRING) AS processo_estado_da_denuncia,
  CAST(processo_tipo_de_operacao AS STRING) AS processo_tipo_de_operacao,
  CAST(processo_data_da_operacao AS STRING) AS processo_data_da_operacao,
  CAST(processo_crime AS STRING) AS processo_crime,
  CAST(processo_crime_2 AS STRING) AS processo_crime_2,
  CAST(processo_prazo AS STRING) AS processo_prazo,
  CAST(advogado_escritorio AS STRING) AS advogado_escritorio,
  CAST(processo_estado_de_la_denuncia AS STRING) AS processo_estado_de_la_denuncia,
  CAST(decisao_analise_de_responsabilidade AS STRING) AS decisao_analise_de_responsabilidade,
  CAST(processo_superendividamento AS STRING) AS processo_superendividamento
FROM
  `<ENV>.STG.STG_INPUT_DATABASE_ELAW_CONTENCIOSO_BRASIL_INCOMING_FINAL`;


-- ============================================================
-- ELAW_CONTENCIOSO_HISPANOS_INCOMING
-- ============================================================
CREATE OR REPLACE TABLE `<ENV>.STG.STG_INPUT_DATABASE_ELAW_CONTENCIOSO_HISPANOS_INCOMING_FINAL` AS
SELECT
  CAST(data_de_citacao AS STRING) AS data_de_citacao,
  CAST(processo_id AS STRING) AS processo_id,
  CAST(pasta AS STRING) AS pasta,
  CAST(pais AS STRING) AS pais,
  CAST(numero_do_processo AS STRING) AS numero_do_processo,
  CAST(outros_numeros AS STRING) AS outros_numeros,
  CAST(status AS STRING) AS status,
  CAST(area_do_direito AS STRING) AS area_do_direito,
  CAST(sub_area_do_direito AS STRING) AS sub_area_do_direito,
  CAST(cliente AS STRING) AS cliente,
  CAST(parte_contraria_nome AS STRING) AS parte_contraria_nome,
  CAST(cust_id_autor AS STRING) AS cust_id_autor,
  CAST(outras_partes_nao_clientes AS STRING) AS outras_partes_nao_clientes,
  CAST(page_report_escritorioresponsavel AS STRING) AS page_report_escritorioresponsavel,
  CAST(data_audiencia_inicial AS STRING) AS data_audiencia_inicial,
  CAST(advogado_responsavel AS STRING) AS advogado_responsavel,
  CAST(processo_estado AS STRING) AS processo_estado,
  CAST(processo_comarca AS STRING) AS processo_comarca,
  CAST(processo_foro_tribunal_orgao AS STRING) AS processo_foro_tribunal_orgao,
  CAST(processo_vara_orgao AS STRING) AS processo_vara_orgao,
  CAST(acao AS STRING) AS acao,
  CAST(objeto AS STRING) AS objeto,
  CAST(objeto_1 AS STRING) AS objeto_1,
  CAST(detalhamento_do_objeto AS STRING) AS detalhamento_do_objeto,
  CAST(distribuicao AS STRING) AS distribuicao,
  CAST(tipo_de_contingencia AS STRING) AS tipo_de_contingencia,
  CAST(risco AS STRING) AS risco,
  CAST(observacao AS STRING) AS observacao,
  CAST(tipo_da_audiencia_inicial AS STRING) AS tipo_da_audiencia_inicial,
  CAST(valor_da_causa AS STRING) AS valor_da_causa,
  CAST(outros_clientes_reu AS STRING) AS outros_clientes_reu,
  CAST(modalidade AS STRING) AS modalidade,
  CAST(data_registrado AS STRING) AS data_registrado,
  CAST(cpf_cnpj AS STRING) AS cpf_cnpj,
  CAST(parte_contraria_cpf AS STRING) AS parte_contraria_cpf,
  CAST(data_de_encerramento AS STRING) AS data_de_encerramento,
  CAST(data_de_registro_do_encerramento AS STRING) AS data_de_registro_do_encerramento,
  CAST(data_do_envio_ao_escritorio AS STRING) AS data_do_envio_ao_escritorio,
  CAST(procedimento_judicial AS STRING) AS procedimento_judicial,
  CAST(resumo_do_subsidio AS STRING) AS resumo_do_subsidio,
  CAST(advogado_da_parte_contraria_nome AS STRING) AS advogado_da_parte_contraria_nome,
  CAST(advogados_participantes AS STRING) AS advogados_participantes,
  CAST(advogado_da_parte_contraria_cpf AS STRING) AS advogado_da_parte_contraria_cpf,
  CAST(cust_id_contraparte AS STRING) AS cust_id_contraparte,
  CAST(id_mediacao AS STRING) AS id_mediacao,
  CAST(centro_custo_nome AS STRING) AS centro_custo_nome,
  CAST(centro_de_custo_codigo AS STRING) AS centro_de_custo_codigo,
  CAST(valor_do_risco AS STRING) AS valor_do_risco,
  CAST(comportamento_do_usuario_cx AS STRING) AS comportamento_do_usuario_cx,
  CAST(id_do_pagamento AS STRING) AS id_do_pagamento,
  CAST(fase_estado AS STRING) AS fase_estado,
  CAST(fase_estado_4 AS STRING) AS fase_estado_4,
  CAST(parte_contraria_contumaz AS STRING) AS parte_contraria_contumaz,
  CAST(advogado_parte_contraria_contumaz AS STRING) AS advogado_parte_contraria_contumaz,
  CAST(usuario AS STRING) AS usuario,
  CAST(audiencia_pendente_data AS STRING) AS audiencia_pendente_data,
  CAST(motivo_de_encerramento AS STRING) AS motivo_de_encerramento,
  CAST(caratula AS STRING) AS caratula,
  CAST(indica_menoridade AS STRING) AS indica_menoridade,
  CAST(processo_classificacao AS STRING) AS processo_classificacao,
  CAST(invoca_hipervulnerabilidad AS STRING) AS invoca_hipervulnerabilidad,
  CAST(causas_raizes AS STRING) AS causas_raizes,
  CAST(causas_raizes_1 AS STRING) AS causas_raizes_1,
  CAST(causas_raizes_2 AS STRING) AS causas_raizes_2,
  CAST(id_de_salesforce AS STRING) AS id_de_salesforce,
  CAST(modelo_de_contratacao AS STRING) AS modelo_de_contratacao,
  CAST(numero_de_envio AS STRING) AS numero_de_envio,
  CAST(usuario_reclamou_a_cx AS STRING) AS usuario_reclamou_a_cx,
  CAST(proceso_critico AS STRING) AS proceso_critico,
  CAST(cbt AS STRING) AS cbt,
  CAST(unidade_de_negocio_impactada AS STRING) AS unidade_de_negocio_impactada,
  CAST(campos_de_alteracao_de_valor_identificacao_do_pagamento AS STRING) AS campos_de_alteracao_de_valor_identificacao_do_pagamento,
  CAST(processo_cust_id_contraparte AS STRING) AS processo_cust_id_contraparte,
  CAST(processo_identificacao_do_pagamento AS STRING) AS processo_identificacao_do_pagamento,
  CAST(valor_1_instancia AS STRING) AS valor_1_instancia,
  CAST(informacoes_complementares_cust_id_contraparte AS STRING) AS informacoes_complementares_cust_id_contraparte,
  CAST(processo_cust_id_contraparte_1 AS STRING) AS processo_cust_id_contraparte_1,
  CAST(processo_apelido_contraparte AS STRING) AS processo_apelido_contraparte,
  CAST(empresa_responsavel AS STRING) AS empresa_responsavel,
  CAST(processo_identificacao_do_pagamento_1 AS STRING) AS processo_identificacao_do_pagamento_1,
  CAST(processo_empresa_demandada AS STRING) AS processo_empresa_demandada,
  CAST(hisp_subsidios_id_da_operacao_mp AS STRING) AS hisp_subsidios_id_da_operacao_mp,
  CAST(hisp_subsidios_status_do_pagamento AS STRING) AS hisp_subsidios_status_do_pagamento,
  CAST(hisp_subsidios_cust_id_autor AS STRING) AS hisp_subsidios_cust_id_autor,
  CAST(hisp_subsidios_numero_de_envio AS STRING) AS hisp_subsidios_numero_de_envio,
  CAST(processo_custid_meli AS STRING) AS processo_custid_meli,
  CAST(processo_revisado_por_dre AS STRING) AS processo_revisado_por_dre,
  CAST(processo_escritorio_do_advogado_da_parte_contraria AS STRING) AS processo_escritorio_do_advogado_da_parte_contraria,
  CAST(processo_materia AS STRING) AS processo_materia,
  CAST(justica AS STRING) AS justica,
  CAST(processo_objeto_revisado AS STRING) AS processo_objeto_revisado,
  CAST(processo_revisado_por_dre_1 AS STRING) AS processo_revisado_por_dre_1,
  CAST(forma_de_participacao AS STRING) AS forma_de_participacao,
  CAST(escritorio_externo AS STRING) AS escritorio_externo,
  CAST(pedido AS STRING) AS pedido,
  CAST(processo_apresentada_resposta_negativa AS STRING) AS processo_apresentada_resposta_negativa,
  CAST(data_de_reativacao AS STRING) AS data_de_reativacao,
  CAST(motivo_de_reativacao AS STRING) AS motivo_de_reativacao,
  CAST(acao_1 AS STRING) AS acao_1,
  CAST(valor_objeto AS STRING) AS valor_objeto,
  CAST(processo_condenacao_em_ma_fe AS STRING) AS processo_condenacao_em_ma_fe,
  CAST(processo_valor_associado_a_ma_fe AS STRING) AS processo_valor_associado_a_ma_fe,
  CAST(processo_data_denuncia AS STRING) AS processo_data_denuncia,
  CAST(processo_data_do_protocolo AS STRING) AS processo_data_do_protocolo,
  CAST(processo_data_instauracao AS STRING) AS processo_data_instauracao,
  CAST(processo_estado_da_denuncia AS STRING) AS processo_estado_da_denuncia,
  CAST(processo_tipo_de_operacao AS STRING) AS processo_tipo_de_operacao,
  CAST(processo_data_da_operacao AS STRING) AS processo_data_da_operacao,
  CAST(processo_crime AS STRING) AS processo_crime,
  CAST(processo_crime_2 AS STRING) AS processo_crime_2,
  CAST(processo_prazo AS STRING) AS processo_prazo,
  CAST(advogado_escritorio AS STRING) AS advogado_escritorio,
  CAST(processo_estado_de_la_denuncia AS STRING) AS processo_estado_de_la_denuncia,
  CAST(decisao_analise_de_responsabilidade AS STRING) AS decisao_analise_de_responsabilidade,
  CAST(processo_superendividamento AS STRING) AS processo_superendividamento
FROM
  `<ENV>.STG.STG_INPUT_DATABASE_ELAW_CONTENCIOSO_HISPANOS_INCOMING_FINAL`;

