DROP TABLE IF EXISTS <ENV>.STG.DIM_MASC_PARCEIROS;

CREATE TABLE <ENV>.STG.DIM_MASC_PARCEIROS (
    COD INT,
    nome_escritorio STRING -- Alterado de TEXT para STRING
);

INSERT INTO <ENV>.STG.DIM_MASC_PARCEIROS (COD, nome_escritorio)
VALUES
(1, 'Bulló Abogados (SEGEM)'),
(2, 'RVBR ABOGADOS LABORALES'),
(3, 'Durrieu Abogados'),
(4, 'Beccar Varela'),
(5, 'Elías Puelles'),
(6, 'Legal Design'),
(7, 'Alchouron- Berisso- Brady Alet- Fernández Pelayo & Balconi'),
(8, 'Marval, O\'Farrell & Mairal'),
(9, 'Castillejos & Escalante Abogados'),
(10, 'Magliona Abogados'),
(11, 'GLZ Abogados'),
(12, 'Law+Dgtal'),
(13, 'Marvan y Muñoz Abogados'),
(14, 'Márquez Barrera Castañeda Ramírez (MBCR)'),
(15, NULL),
(16, 'Niubox'),
(17, 'Barreiro, Oliva, De Luca, Jaca & Nicastro'),
(18, 'Pérez Alati, Grondona, Benites, Arntsen & Mártinez de Hoz (h)'),
(19, 'Martin Saldico'),
(20, 'Viramonte & Hernández Abogados'),
(21, 'Estrada & Canale Abogados'),
(22, 'Skatt Asesores Fiscales SC'),
(23, 'Legales MELI Interno'),
(24, 'Lizama'),
(25, 'Del Rio & Cia'),
(26, 'Ferrere Abogados'),
(27, 'Adrogué Marqués Zabala & Associados'),
(28, 'Estudio Cariola'),
(29, 'G. Breuer'),
(30, 'JP O´Farrell Abogados'),
(31, 'Niubox - Ecuador'),
(32, 'Alamos Squella'),
(33, 'Tanoira Cassagne'),
(34, 'Gomez Pinzon'),
(35, 'CMS Rodríguez-Azuero'),
(36, 'Otro'),
(37, 'Gordó Llobell'),
(38, 'Ecija'),
(39, 'Baker & Mckenzie'),
(40, 'Contreras Velozo'),
(41, 'Estudio Albina'),
(42, 'Mestre Mendieta'),
(43, 'PPU Legal'),
(44, 'Salt & Sergi'),
(45, 'Tufih Sahade y Miguel Carol Lugones'),
(46, 'Martens'),
(47, 'OLIVEIRA RAMOS ADVOGADOS'),
(48, 'Ouvidoria PROCON'),
(49, 'BBL Advogados'),
(50, 'Goulart Penteado');
