-- ====================================================================================
-- V2: Fonte eLaw unificada em LK_PBD_LA_ENTRADAS_E_DESFECHOS
-- Substitui o uso das 3 bases STG (INCOMING / ONGOING / OUTGOING Brasil) pela LK
-- que já consolida e deduplica por PROCESSO_ID.
-- ====================================================================================

CREATE OR REPLACE TABLE `<ENV>.STG.TBL_FINAL_CONSOLIDADA_OFICIOS_EMBARGOS` AS

WITH MaxConfirmacaoPorProcesso AS (
  SELECT
    PROCESSO_ID,
    MAX(SAFE.PARSE_DATE('%d/%m/%Y', DATA_DE_CONFIRMACAO)) AS DATA_DE_CONFIRMACAO_MAX_TAREFA,
    MAX(SAFE.PARSE_DATE('%d/%m/%Y', DATA_REGISTRADO)) AS DATA_DE_REGISTRADO_MAX_TAREFA
  FROM `<ENV>.STG.LK_PBD_LA_VW_TAREFAS_AGENDAMENTOS_CLEAN`
  WHERE DATA_DE_CONFIRMACAO IS NOT NULL
  GROUP BY PROCESSO_ID
),

-- eLaw: uma única base consolidada (LK_PBD_LA_ENTRADAS_E_DESFECHOS) + filtro Ofícios
elaw_oficios AS (
  SELECT DISTINCT
    a.PROCESSO_ID AS processo_id,
    a.STATUS,
    a.AREA_DO_DIREITO,
    a.SUB_AREA_DO_DIREITO,
    a.PAGE_REPORT_ESCRITORIORESPONSAVEL,
    a.PROCESSO_ESTADO,
    a.OBJETO,
    CAST(a.DATA_DE_CITACAO AS STRING) AS DATA_DE_CITACAO,
    CAST(a.DATA_REGISTRADO AS STRING) AS DATA_REGISTRADO,
    CAST(a.DATA_DE_ENCERRAMENTO AS STRING) AS DATA_DE_ENCERRAMENTO,
    a.VALOR_DO_RISCO,
    a.USUARIO,
    a.PROCESSO_MATERIA,
    a.ESCRITORIO_EXTERNO,
    a.PROCESSO_PRAZO,
    "Finch" AS PROVEDOR,
    "Brasil" AS Pais,
    CAST(CASE WHEN a.PROCESSO_APRESENTADA_RESPOSTA_NEGATIVA = "Sim" THEN "Sem informação" WHEN a.PROCESSO_APRESENTADA_RESPOSTA_NEGATIVA = "Não" THEN "Com informação" ELSE NULL END AS STRING) AS Tipo_Resposta,
    a.OBJETO_TRATADO AS OBJETO_NOVO,
    a.UNIDADE_TRATADA AS UNIDADE,
    a.EMPRESA_TRATADA AS EMPRESA_CODE,
    CAST(CASE WHEN a.Pais = "Brasil" AND a.STATUS = "Reativado" THEN 'S' ELSE 'N' END AS STRING) AS LEGALES_REITERATORIO,
    SAFE.PARSE_DATE('%d/%m/%Y', a.DATA_REGISTRADO) AS DATA_DE_REGISTRADO_TRATADA,
    SAFE.PARSE_DATE('%d/%m/%Y', a.DATA_DE_ENCERRAMENTO) AS DATA_DE_ENCERRAMENTO_TRATADA,
    m.DATA_DE_CONFIRMACAO_MAX_TAREFA,
    m.DATA_DE_REGISTRADO_MAX_TAREFA
  FROM `<ENV>.STG.LK_PBD_LA_ENTRADAS_E_DESFECHOS` a
  LEFT JOIN MaxConfirmacaoPorProcesso m ON m.PROCESSO_ID = a.PROCESSO_ID
  WHERE a.Pais = "Brasil"
    AND a.AREA_DO_DIREITO = "Requerimentos"
    AND a.SUB_AREA_DO_DIREITO = "Ofícios"
    AND SAFE.PARSE_DATE('%d/%m/%Y', a.DATA_REGISTRADO) > DATE '2023-01-01'
),

-- Salesforce Ofícios: incoming + outgoing + dim + status em um CTE
Oficios_Salesforce AS (
  SELECT
    inc.ISSUE_NUMBER,
    FORMAT_DATE('%d/%m/%Y', SAFE.PARSE_DATE('%d/%m/%Y', inc.ISSUE_FECHA_DE_CREACION)) AS DATA_REGISTRADO,
    FORMAT_DATE('%d/%m/%Y', SAFE.PARSE_DATE('%d/%m/%Y', out.LEGALES_FECHA_APROBacion)) AS DATA_DE_ENCERRAMENTO,
    out.ISSUE_ULTIMA_MODIFICACION_POR AS Usuario,
    "SEGEN" AS PROVEDOR,
    dim.PAIS AS pais_normalizado,
    "Informativo HSP" AS Processo_materia,
    CAST(CASE WHEN inc.RESPUESTA_NEGATIVA = 'Não' THEN 'Com informação' WHEN inc.RESPUESTA_NEGATIVA = 'Sim' THEN 'Sem informação' ELSE 'Não' END AS STRING) AS Tipo_Resposta,
    CAST(CASE WHEN TRIM(inc.LEGALES_REITERATORIO) = '1' THEN 'S' WHEN TRIM(inc.LEGALES_REITERATORIO) = '0' THEN 'N' ELSE 'N' END AS STRING) AS LEGALES_REITERATORIO,
    IF(p.ISSUE_NUMBER IS NOT NULL, "Ativo", "Encerrado") AS Status
  FROM `<ENV>.STG.SALESFORCE_INCOMING_OFICIOS` inc
  LEFT JOIN `<ENV>.STG.SALESFORCE_OUTCOMING_OFICIOS` out ON inc.ISSUE_NUMBER = out.ISSUE_NUMBER
  LEFT JOIN `<ENV>.STG.DIM_17_DIMENSAO_SIGLA_PAIS` dim ON inc.Pais = dim.Sigla
  LEFT JOIN `<ENV>.STG.SALESFORCE_PENDING_INFORMATIVOS` p ON inc.ISSUE_NUMBER = p.ISSUE_NUMBER
),

-- Salesforce Embargos: mesmo padrão
Embargos_Salesforce AS (
  SELECT
    inc.ISSUE_NUMBER,
    FORMAT_DATE('%d/%m/%Y', SAFE.PARSE_DATE('%d/%m/%Y', inc.ISSUE_FECHA_DE_CREACION)) AS DATA_REGISTRADO,
    FORMAT_DATE('%d/%m/%Y', SAFE.PARSE_DATE('%d/%m/%Y', out.LEGALES_FECHA_APROBACION)) AS DATA_DE_ENCERRAMENTO,
    out.ISSUE_ULTIMA_MODIFICACION_POR AS Usuario,
    "Enlighten" AS PROVEDOR,
    dim.PAIS AS pais_normalizado,
    "Embargos" AS Processo_materia,
    CAST(CASE WHEN inc.RESPUESTA_NEGATIVA = 'Não' THEN 'Com informação' WHEN inc.RESPUESTA_NEGATIVA = 'Sim' THEN 'Sem informação' ELSE 'Não' END AS STRING) AS Tipo_Resposta,
    CAST(CASE WHEN TRIM(inc.LEGALES_REITERATORIO) = '1' THEN 'S' WHEN TRIM(inc.LEGALES_REITERATORIO) = '0' THEN 'N' ELSE 'N' END AS STRING) AS LEGALES_REITERATORIO,
    IF(p.ISSUE_NUMBER IS NOT NULL, "Ativo", "Encerrado") AS Status
  FROM `<ENV>.STG.SALESFORCE_INCOMING_EMBARGOS` inc
  LEFT JOIN `<ENV>.STG.SALESFORCE_OUTGOING_EMBARGOS` out ON inc.ISSUE_NUMBER = out.ISSUE_NUMBER
  LEFT JOIN `<ENV>.STG.DIM_17_DIMENSAO_SIGLA_PAIS` dim ON inc.Pais = dim.Sigla
  LEFT JOIN `<ENV>.STG.SALESFORCE_PENDING_EMBARGOS_BCRA_E_NAO_BCRA` p ON inc.ISSUE_NUMBER = p.ISSUE_NUMBER
),

-- Schema unificado Salesforce (uma única expressão para Ofícios + Embargos)
Consolidado_Salesforce AS (
  SELECT
    ISSUE_NUMBER AS processo_id,
    CAST(Status AS STRING) AS STATUS,
    CAST(NULL AS STRING) AS AREA_DO_DIREITO,
    CAST(NULL AS STRING) AS SUB_AREA_DO_DIREITO,
    CAST(NULL AS STRING) AS PAGE_REPORT_ESCRITORIORESPONSAVEL,
    CAST(NULL AS STRING) AS PROCESSO_ESTADO,
    CAST(NULL AS STRING) AS OBJETO,
    CAST(NULL AS STRING) AS DATA_DE_CITACAO,
    DATA_REGISTRADO,
    DATA_DE_ENCERRAMENTO,
    CAST(NULL AS STRING) AS VALOR_DO_RISCO,
    Usuario AS USUARIO,
    Processo_materia AS PROCESSO_MATERIA,
    CAST(NULL AS STRING) AS ESCRITORIO_EXTERNO,
    CAST(NULL AS STRING) AS PROCESSO_PRAZO,
    PROVEDOR,
    pais_normalizado AS Pais,
    Tipo_Resposta,
    CAST(NULL AS STRING) AS OBJETO_NOVO,
    CAST(NULL AS STRING) AS UNIDADE,
    CAST(NULL AS STRING) AS EMPRESA_CODE,
    LEGALES_REITERATORIO,
    SAFE.PARSE_DATE('%d/%m/%Y', DATA_REGISTRADO) AS DATA_DE_REGISTRADO_TRATADA,
    SAFE.PARSE_DATE('%d/%m/%Y', DATA_DE_ENCERRAMENTO) AS DATA_DE_ENCERRAMENTO_TRATADA,
    SAFE.PARSE_DATE('%d/%m/%Y', DATA_DE_ENCERRAMENTO) AS DATA_DE_CONFIRMACAO_MAX_TAREFA,
    SAFE.PARSE_DATE('%d/%m/%Y', DATA_REGISTRADO) AS DATA_DE_REGISTRADO_MAX_TAREFA
  FROM (SELECT * FROM Oficios_Salesforce UNION ALL SELECT * FROM Embargos_Salesforce) AS sf
),

-- Consolidação final: Salesforce + eLaw, padronização e métricas em um passo
Final AS (
  SELECT DISTINCT
    processo_id,
    STATUS,
    AREA_DO_DIREITO,
    SUB_AREA_DO_DIREITO,
    PAGE_REPORT_ESCRITORIORESPONSAVEL,
    PROCESSO_ESTADO,
    OBJETO,
    SAFE.PARSE_DATE('%d/%m/%Y', DATA_DE_CITACAO) AS DATA_DE_CITACAO,
    DATA_DE_REGISTRADO_TRATADA AS DATA_DE_REGISTRADO,
    DATA_DE_ENCERRAMENTO_TRATADA AS DATA_DE_ENCERRAMENTO,
    VALOR_DO_RISCO,
    USUARIO,
    PROCESSO_MATERIA,
    ESCRITORIO_EXTERNO,
    PROCESSO_PRAZO,
    IF(PROVEDOR IN ('SEGEN', 'Enlighten'), PROVEDOR, 'Finch') AS PROVEDOR,
    Pais,
    CASE WHEN Tipo_Resposta IN ('Com informação', 'Sem informação') THEN Tipo_Resposta ELSE 'Sem informação' END AS Tipo_Reposta,
    OBJETO_NOVO,
    UNIDADE,
    EMPRESA_CODE,
    LEGALES_REITERATORIO,
    -- Maior data entre _MAX_TAREFA e _TRATADA (garante uso da data mais recente)
    COALESCE(
      GREATEST(DATA_DE_REGISTRADO_MAX_TAREFA, DATA_DE_REGISTRADO_TRATADA),
      DATA_DE_REGISTRADO_MAX_TAREFA,
      DATA_DE_REGISTRADO_TRATADA
    ) AS DATA_REGISTRADO_COMPOSTA,
    COALESCE(
      GREATEST(DATA_DE_CONFIRMACAO_MAX_TAREFA, DATA_DE_ENCERRAMENTO_TRATADA),
      DATA_DE_CONFIRMACAO_MAX_TAREFA,
      DATA_DE_ENCERRAMENTO_TRATADA
    ) AS DATA_ENCERRAMENTO_COMPOSTA,
    DATE_DIFF(
      COALESCE(GREATEST(DATA_DE_CONFIRMACAO_MAX_TAREFA, DATA_DE_ENCERRAMENTO_TRATADA), DATA_DE_CONFIRMACAO_MAX_TAREFA, DATA_DE_ENCERRAMENTO_TRATADA),
      COALESCE(GREATEST(DATA_DE_REGISTRADO_MAX_TAREFA, DATA_DE_REGISTRADO_TRATADA), DATA_DE_REGISTRADO_MAX_TAREFA, DATA_DE_REGISTRADO_TRATADA),
      DAY
    ) AS TEMPO_MEDIO_RESPOSTA
  FROM (
    SELECT * FROM Consolidado_Salesforce
    UNION ALL
    SELECT * FROM elaw_oficios
  ) AS consolidacao
)

SELECT * FROM Final;
