/*
EMBARGOS BRASIL
Esse processo é para carregar os embargos Brasil separadamente de oficios.
A validação é necessaria com os dados de embargos extraidos do elaw
[por volta 800 casos vindos em agosto de 2025, apresentados por Vale,Ju e Felipe em 19/02/2026]


*/

WITH 
elaw_oficios AS (
  SELECT DISTINCT
    a.PROCESSO_ID AS processo_id,
    a.STATUS,
    a.AREA_DO_DIREITO,
    a.SUB_AREA_DO_DIREITO,
    a.PAGE_REPORT_ESCRITORIORESPONSAVEL,
    a.PROCESSO_ESTADO,
    a.OBJETO,
    CAST(a.DATA_DE_CITACAO AS STRING) AS DATA_DE_CITACAO,
    CAST(a.DATA_REGISTRADO AS STRING) AS DATA_REGISTRADO,
    CAST(a.DATA_DE_ENCERRAMENTO AS STRING) AS DATA_DE_ENCERRAMENTO,
    a.VALOR_DO_RISCO,
    a.USUARIO,
    a.PROCESSO_MATERIA,
    a.ESCRITORIO_EXTERNO,
    a.PROCESSO_PRAZO,
    "Finch" AS PROVEDOR,
    "Brasil" AS Pais,
    CAST(CASE WHEN a.PROCESSO_APRESENTADA_RESPOSTA_NEGATIVA = "Sim" THEN "Sem informação" WHEN a.PROCESSO_APRESENTADA_RESPOSTA_NEGATIVA = "Não" THEN "Com informação" ELSE NULL END AS STRING) AS Tipo_Resposta,
    b.OBJETO_NOVO,
    b.UNIDADE,
    b.EMPRESA_CODE,
    CAST(a.LEGALES_REITERATORIO AS STRING) AS LEGALES_REITERATORIO,
    SAFE.PARSE_DATE('%d/%m/%Y', a.DATA_REGISTRADO) AS DATA_DE_REGISTRADO_TRATADA,
    SAFE.PARSE_DATE('%d/%m/%Y', a.DATA_DE_ENCERRAMENTO) AS DATA_DE_ENCERRAMENTO_TRATADA,
    m.DATA_DE_CONFIRMACAO_MAX_TAREFA,
    m.DATA_DE_REGISTRADO_MAX_TAREFA
  FROM (
    SELECT *, 'N' AS LEGALES_REITERATORIO FROM `<ENV>.STG.STG_INPUT_DATABASE_ELAW_CONTENCIOSO_BRASIL_INCOMING_FINAL` WHERE STATUS = "Ativo"
    UNION DISTINCT
    SELECT *, CASE WHEN Pais = "Brasil" AND STATUS = "Reativado" THEN 'S' ELSE 'N' END AS LEGALES_REITERATORIO FROM `<ENV>.STG.STG_INPUT_DATABASE_ELAW_CONTENCIOSO_BRASIL_ONGOING_FINAL` WHERE STATUS = "Reativado"
    UNION DISTINCT
    SELECT *, 'N' AS LEGALES_REITERATORIO FROM `<ENV>.STG.STG_INPUT_DATABASE_ELAW_CONTENCIOSO_BRASIL_OUTGOING_FINAL` WHERE STATUS = "Encerrado"
  ) a
  -- TODO: Verificar se esse join com a dimensão de objetos não esta limitando os dados
  --LEFT JOIN `<ENV>.STG.DIM_10_DIMENSAO_OBJETOS_2` b ON UPPER(a.OBJETO) = UPPER(b.OBJETO)
  --LEFT JOIN MaxConfirmacaoPorProcesso m ON m.PROCESSO_ID = a.PROCESSO_ID
  WHERE a.AREA_DO_DIREITO = "Requerimentos"
    AND a.SUB_AREA_DO_DIREITO = "Ofícios"
    AND SAFE.PARSE_DATE('%d/%m/%Y', a.DATA_REGISTRADO) > DATE '2023-01-01')