WITH subs AS (
  SELECT DISTINCT processo_id
  FROM `pdme000426-c1s7scatwm0-furyid.STG.TBL_FINAL_CONSOLIDADA_SUBSIDIOS`
)

SELECT
  SAFE.PARSE_DATE('%d/%m/%Y', DATA_DE_CITACAO) AS DATA_DE_CITACAO,
  a.PROCESSO_ID,
  a.PASTA,
  a.PAIS,
  a.NUMERO_DO_PROCESSO,
  a.OUTROS_NUMEROS,
  CASE
    WHEN A.AREA_DO_DIREITO  IN ('CORP - Cível', 'CORP - Civil') THEN 'Cível'
    WHEN A.AREA_DO_DIREITO  = 'CORP - Consumidor' THEN 'Consumidor'
    WHEN A.AREA_DO_DIREITO  = 'CORP - Criminal' THEN 'Criminal'
    WHEN A.AREA_DO_DIREITO  = 'CORP - Laboral' THEN 'Trabalhista'
    WHEN A.AREA_DO_DIREITO  = 'CORP - Tributário' THEN 'Tributário'
    WHEN A.AREA_DO_DIREITO  = 'CORP - Requerimientos' THEN 'Requerimentos'
    ELSE A.AREA_DO_DIREITO 
  END AS AREA_DO_DIREITO ,
  CASE
    WHEN A.SUB_AREA_DO_DIREITO IN ('Oficios') THEN 'Ofícios'
    WHEN A.SUB_AREA_DO_DIREITO IN ('Pre-Administrativo', 'Pré Administrativo') THEN 'Pré-Administrativo'
    ELSE A.SUB_AREA_DO_DIREITO
  END AS SUB_AREA_DO_DIREITO,
  a.CLIENTE,
  a.PARTE_CONTRARIA_NOME,
  a.CUST_ID_AUTOR,
  a.OUTRAS_PARTES_NAO_CLIENTES,
  a.PAGE_REPORT_ESCRITORIORESPONSAVEL,
  SAFE.PARSE_DATE('%d/%m/%Y', a.DATA_AUDIENCIA_INICIAL) AS DATA_AUDIENCIA_INICIAL,
  a.ADVOGADO_RESPONSAVEL,
  a.PROCESSO_ESTADO,
  a.PROCESSO_COMARCA,
  a.PROCESSO_FORO_TRIBUNAL_ORGAO,
  a.PROCESSO_VARA_ORGAO,
  a.ACAO,
  a.OBJETO,
  a.OBJETO_1,
  a.DETALHAMENTO_DO_OBJETO,
  a.DISTRIBUICAO,
  a.TIPO_DE_CONTINGENCIA,
  a.RISCO,

  -- FLAG_SUBS dinâmico
  CASE 
    WHEN s.processo_id IS NOT NULL THEN 1 
    ELSE 0 
  END AS FLAG_SUBS,

  a.OBSERVACAO,
  a.TIPO_DA_AUDIENCIA_INICIAL,
  a.VALOR_DA_CAUSA,
  a.OUTROS_CLIENTES_REU,
  a.MODALIDADE,
  SAFE.PARSE_DATE('%d/%m/%Y', a.DATA_REGISTRADO) AS DATA_REGISTRADO,
  a.CPF_CNPJ,
  SAFE.PARSE_DATE('%d/%m/%Y', a.DATA_DE_ENCERRAMENTO) AS DATA_DE_ENCERRAMENTO,
  SAFE.PARSE_DATE('%d/%m/%Y', a.DATA_DE_REGISTRO_DO_ENCERRAMENTO) AS DATA_DE_REGISTRO_DO_ENCERRAMENTO,
  SAFE.PARSE_DATE('%d/%m/%Y', a.DATA_DO_ENVIO_AO_ESCRITORIO) AS DATA_DO_ENVIO_AO_ESCRITORIO,
  a.PROCEDIMENTO_JUDICIAL,
  a.ADVOGADO_DA_PARTE_CONTRARIA_NOME,
  a.ADVOGADOS_PARTICIPANTES,
  a.ADVOGADO_DA_PARTE_CONTRARIA_CPF,
  a.CUST_ID_CONTRAPARTE,
  a.ID_MEDIACAO,
  a.CENTRO_CUSTO_NOME,
  a.CENTRO_DE_CUSTO_CODIGO,
  a.VALOR_DO_RISCO,
  a.COMPORTAMENTO_DO_USUARIO_CX,
  a.ID_DO_PAGAMENTO,
  a.FASE_ESTADO,
  a.FASE_ESTADO_4,
  a.PARTE_CONTRARIA_CONTUMAZ,
  a.ADVOGADO_PARTE_CONTRARIA_CONTUMAZ,
  a.USUARIO,
  SAFE.PARSE_DATE('%d/%m/%Y', a.AUDIENCIA_PENDENTE_DATA) AS AUDIENCIA_PENDENTE_DATA,
  a.MOTIVO_DE_ENCERRAMENTO,
  a.CARATULA,
  a.INDICA_MENORIDADE,
  a.PROCESSO_CLASSIFICACAO,
  a.INVOCA_HIPERVULNERABILIDAD,
  a.CAUSAS_RAIZES,
  a.CAUSAS_RAIZES_1,
  a.CAUSAS_RAIZES_2,
  a.ID_DE_SALESFORCE,
  a.MODELO_DE_CONTRATACAO,
  a.NUMERO_DE_ENVIO,
  a.USUARIO_RECLAMOU_A_CX,
  a.PROCESO_CRITICO,
  a.CBT,
  a.UNIDADE_DE_NEGOCIO_IMPACTADA,
  a.CAMPOS_DE_ALTERACAO_DE_VALOR_IDENTIFICACAO_DO_PAGAMENTO,
  a.PROCESSO_CUST_ID_CONTRAPARTE,
  a.PROCESSO_IDENTIFICACAO_DO_PAGAMENTO,
  a.VALOR_1_INSTANCIA,
  a.INFORMACOES_COMPLEMENTARES_CUST_ID_CONTRAPARTE,
  a.PROCESSO_CUST_ID_CONTRAPARTE_1,
  a.PROCESSO_APELIDO_CONTRAPARTE,
  a.EMPRESA_RESPONSAVEL,
  a.PROCESSO_IDENTIFICACAO_DO_PAGAMENTO_1,
  a.PROCESSO_EMPRESA_DEMANDADA,
  a.HISP_SUBSIDIOS_ID_DA_OPERACAO_MP,
  a.HISP_SUBSIDIOS_STATUS_DO_PAGAMENTO,
  a.HISP_SUBSIDIOS_CUST_ID_AUTOR,
  a.HISP_SUBSIDIOS_NUMERO_DE_ENVIO,
  a.PROCESSO_CUSTID_MELI,
  a.PROCESSO_REVISADO_POR_DRE,
  a.PROCESSO_ESCRITORIO_DO_ADVOGADO_DA_PARTE_CONTRARIA,
  a.PROCESSO_MATERIA,
  a.JUSTICA,
  a.PROCESSO_OBJETO_REVISADO,
  a.PROCESSO_REVISADO_POR_DRE_1,
  a.FORMA_DE_PARTICIPACAO,
  a.ESCRITORIO_EXTERNO,
  a.PEDIDO,
  a.PROCESSO_APRESENTADA_RESPOSTA_NEGATIVA,
  SAFE.PARSE_DATE('%d/%m/%Y', a.DATA_DE_REATIVACAO) AS DATA_DE_REATIVACAO,
  a.MOTIVO_DE_REATIVACAO,
  a.ACAO_1,
  a.VALOR_OBJETO,
  a.PROCESSO_CONDENACAO_EM_MA_FE,
  a.PROCESSO_VALOR_ASSOCIADO_A_MA_FE,
  SAFE.PARSE_DATE('%d/%m/%Y', a.PROCESSO_DATA_DENUNCIA) AS PROCESSO_DATA_DENUNCIA,
  SAFE.PARSE_DATE('%d/%m/%Y', a.PROCESSO_DATA_DO_PROTOCOLO) AS PROCESSO_DATA_DO_PROTOCOLO,
  SAFE.PARSE_DATE('%d/%m/%Y', a.PROCESSO_DATA_INSTAURACAO) AS PROCESSO_DATA_INSTAURACAO,
  a.PROCESSO_ESTADO_DA_DENUNCIA,
  a.PROCESSO_TIPO_DE_OPERACAO,
  SAFE.PARSE_DATE('%d/%m/%Y', a.PROCESSO_DATA_DA_OPERACAO) AS PROCESSO_DATA_DA_OPERACAO,
  a.PROCESSO_CRIME,
  a.PROCESSO_CRIME_2,
  a.PROCESSO_PRAZO,
  a.ADVOGADO_ESCRITORIO,
  a.PROCESSO_ESTADO_DE_LA_DENUNCIA,
  a.DECISAO_ANALISE_DE_RESPONSABILIDADE,
  a.PROCESSO_SUPERENDIVIDAMENTO,
  SAFE.PARSE_DATE('%d/%m/%Y', a.MULTA_DATA) AS MULTA_DATA,
  a.MULTA_TIPO_AJUSTADO,
  a.REGIAO,
  a.FASE_DESFECHO,
  a.OBJETO_TRATADO,
  a.UNIDADE_TRATADA,
  a.EMPRESA_TRATADA,
  a.OBJETO_CROSS,
  a.MUNDO,
  a.STATUS,
  a.CAUSA_MAIOR_200K,
  a.RISCO_MAIOR_200K,
  a.RISCO_ENTRE_100K_E_200K,
  a.CAUSA_ENTRE_100K_E_200K,
  a.AGING,
  CASE
    WHEN a.MULTA_TIPO_AJUSTADO IS NULL OR a.MULTA_TIPO_AJUSTADO = 'Outros' THEN 0
    ELSE 1
  END AS FLAG_MULTA,
  valor as valor_garantia_veiculos,
  sub_tipo as status_garantia_veiculos


FROM `pdme000426-c1s7scatwm0-furyid.STG.LK_PBD_LA_BASE_BASE_ATIVA` a
LEFT JOIN subs s
  ON a.processo_id = s.processo_id
LEFT JOIN `pdme000426-c1s7scatwm0-furyid.STG.STG_INPUT_DATABASE_ELAW_VEICULOS` B on A.PROCESSO_ID = B.PROCESSO_ID