CREATE OR REPLACE TABLE `<ENV>.STG.Tab_embargos` AS
SELECT
  deb.DEBT_USER_ID          AS DEB_DEBT_USER_ID,
  deb.DEBT_ID               AS DEB_DEBT_ID,
  deb.DEBT_TOTAL_AMOUNT     AS DEB_DEBT_TOTAL_AMOUNT,
  deb.DEBT_PAID_AMOUNT      AS DEB_DEBT_PAID_AMOUNT,
  deb.DEBT_STATUS           AS DEB_DEBT_STATUS,
  deb.DEBT_CURRENCY_ID      AS DEB_DEBT_CURRENCY_ID,
  deb.DEBT_SITE_ID          AS DEB_DEBT_SITE_ID,
  deb.DEBT_CREATED_AT       AS DEB_DEBT_CREATED_AT,
  deb.DEBT_DEBT_TYPE_ID     AS DEB_DEBT_DEBT_TYPE_ID,

  rec.RECOVERY_DESCRIPTION,
  cus.CUS_CUST_DOC_NUMBER,
  cus.CUS_FIRST_NAME,
  cus.CUS_LAST_NAME

FROM
  `meli-bi-data.WHOWNER.BT_MP_DISB_DEBT` AS deb

JOIN
  `meli-bi-data.WHOWNER.BT_DEBT_RECOVERY` AS rec
    ON deb.DEBT_ID = rec.DEBT_ID

JOIN
  `meli-bi-data.WHOWNER.LK_CUS_CUSTOMERS_DATA` AS cus
    ON deb.DEBT_USER_ID = cus.CUS_CUST_ID

WHERE
  deb.DEBT_DEBT_TYPE_ID IN (77, 437, 442, 459)
  AND deb.DEBT_CREATED_AT BETWEEN DATE('2023-01-01')
    AND DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY);
