WITH base_tratada AS (
  SELECT
    AREA_DO_DIREITO,
    SUB_AREA_DO_DIREITO,
    PROCESSO_ID,
    DATA,
    SUB_TIPO,
    RESPONSAVEL,
    ESCRITORIO_EXTERNO,
    ESTADO,
    OBSERVACAO,
    OBRIGACAO_DE_FAZER_DATA_DA_INTIMACAO_PARA_CUMPRIMENTO,
    ADVOGADO_RESPONSAVEL,
    PROCESSO_CLASSIFICACAO,
    PROCESSO_EMPRESA_DEMANDADA,
    OBJETO,
    STATUS,
    DATA_DE_CONFIRMACAO,
    DESCRICAO_EVENTO_CONCLUIDO,
    TAREFAS_MOTIVO_DO_AJUSTE,
    CURRENT_DATE() AS DATA_REF,

    -- Conversão de string para DATE considerando formato DD/MM/YYYY
    SAFE.PARSE_DATE('%d/%m/%Y', DATA) AS DATA_CONVERTIDA

  FROM
    `ddme000426-gopr4nla6zo-furyid.TBL.LK_PBD_LA_ELAW_REPORT_TAREFAS_AGENDADAS_AGUARDANDO_INFORMACOES`

  WHERE
    OBSERVACAO IS NULL
    OR NOT LOWER(OBSERVACAO) LIKE '%polo%'
)

SELECT
  *,
  ABS(DATE_DIFF(CURRENT_DATE(), DATA_CONVERTIDA, DAY)) AS SUBTRACAO,

  CASE
    WHEN DATA_CONVERTIDA IS NULL THEN 'DATA INVÁLIDA'
    WHEN DATE_DIFF(CURRENT_DATE(), DATA_CONVERTIDA, DAY) <= 15 THEN 'ATÉ 15 DIAS'
    WHEN DATE_DIFF(CURRENT_DATE(), DATA_CONVERTIDA, DAY) <= 30 THEN '16 - 30 DIAS'
    WHEN DATE_DIFF(CURRENT_DATE(), DATA_CONVERTIDA, DAY) <= 45 THEN '31 - 45 DIAS'
    WHEN DATE_DIFF(CURRENT_DATE(), DATA_CONVERTIDA, DAY) <= 60 THEN '46 - 60 DIAS'
    ELSE 'MAIOR QUE 60 DIAS'
  END AS RANGE_DIAS

FROM base_tratada
