with coco as (
    SELECT
        VERTICAL,
        IDENTIFICACAO,
        SISTEMA,
        DATA_IMPORTACAO,
        CODIGO_CHAVE_OD,
        CODIGO_CHAVE_EXTRATO,
        VALOR_TRANSACAO,
        NUMERO_BANCO_OD,
        NUMERO_AGENCIA_OD,
        NUMERO_CONTA_OD,
        TIPO_CONTA_OD,
        TIPO_PESSOA_OD,
        NOME_PESSOA_OD,
        NOME_DOC_IDENTIFICACAO,
        NUMERO_DOC_IDENTIFICACAO,
        CODIGO_DE_BARRAS,
        NOME_ENDOSSANTE_CHEQUE,
        DOC_ENDOSSANTE_CHEQUE,
        SITUACAO_IDENTIFICACAO,
        OBSERVACAO,
        DATAHORA_IMPORTACAO
    FROM
        `meli-bi-data.SBOX_LEGALES.TBL_QS_ORIGEM_DESTINO_FINCH`
    where
        NUMERO_AGENCIA_OD = "9999"
)
select
    a.CODIGO_CHAVE_EXTRATO,
    b.PAY_PAYMENT_ID
from
    coco as a
    left join WHOWNER.BT_MP_ACC_MOVEMENTS as b on CAST(a.CODIGO_CHAVE_EXTRATO AS NUMERIC) = b.MOV_MOVE_ID